package.json, yarn.lock
Use cross-env and cpy-cli to make scripts run on windows.
=> Enable cross platform development

docs/api/NetworkErrorBoundary.md, src/index.ts, src/react-integration/NetworkErrorBoundary.tsx, src/react-integration/index.ts
I didn't check that typescript is correct as I edited this on github
=> [enhance] More refined typings for NetworkErrorBoundary

package.json
Resolves https://github.com/coinbase/rest-hooks/issues/31
=> [pkg] Make @types/react a peerdep

src/react-integration/provider/__tests__/__snapshots__/middleware.tsx.snap, src/react-integration/provider/__tests__/middleware.tsx, src/react-integration/provider/middleware.ts
This also adds getState() to make this 100% redux compatible
=> [internal] Add test for warn on dispatch for enhancedReducer

src/react-integration/provider/index.tsx
Will redesign this interface in 2.0.
=> [feature] Janky SSR interface added to RestProvider

src/__tests__/common.ts, src/index.ts, src/react-integration/__tests__/integration.tsx, src/react-integration/hooks/index.ts, src/react-integration/hooks/useCache.ts, src/react-integration/hooks/useError.ts, src/react-integration/hooks/useResource.ts, src/react-integration/hooks/useResultCache.ts, src/react-integration/hooks/useRetrieve.ts, src/react-integration/hooks/useSubscription.ts, src/react-integration/index.ts, src/resource/Resource.ts, src/resource/__tests__/resource.ts, src/resource/index.ts, src/state/__tests__/networkManager.ts, src/state/__tests__/pollingSubscription.ts, src/state/__tests__/subscriptionManager.ts, src/state/selectors.ts
Useful for extending functionality.
=> Expose useError hook in rest-hooks

src/resource/Resource.ts, src/resource/__tests__/__snapshots__/resource.ts.snap, src/resource/__tests__/resource.ts
Fixes https://github.com/coinbase/rest-hooks/issues/39
=> [enhance] Throw error in dev when response is not json

src/react-integration/provider/ExternalCacheProvider.tsx
=> use relative import of types

docs/api/NetworkErrorBoundary.md, website/package.json, website/siteConfig.js, website/static/css/prism-theme.css, website/yarn.lock
Waiting on https://github.com/facebook/Docusaurus/pull/1391 to make this work
=> [docs] Fix syntax highlighting for tsx

README.md, ROADMAP.md, docs/api/MockProvider.md, docs/api/makeExternalCacheProvider.md, docs/api/makeRenderRestHook.md, docs/api/makeRestProvider.md, docs/guides/storybook.md, docs/guides/unit-testing-components.md, docs/guides/unit-testing-hooks.md, src/react-integration/__tests__/integration.tsx, src/react-integration/__tests__/subscriptions.tsx, src/test/helper.tsx, src/test/index.ts, src/test/providers.tsx, test.d.ts, website/i18n/en.json, website/package.json, website/sidebars.json, website/yarn.lock
Resolves https://github.com/coinbase/rest-hooks/issues/13
=> [docs] Add testing utility docs and guides

src/react-integration/__tests__/hooks.tsx, src/react-integration/hooks/useResource.ts, yarn.lock
Should fix https://github.com/coinbase/rest-hooks/issues/78
=> [fix] Persist promise in multi useResource() until resolution or change

docs/guides/loading-state.md
=> Significant improvements to documentation.

docs/api/RequestShape.md, docs/guides/endpoints.md, docs/guides/jsonp.md, docs/guides/network-transform.md, docs/guides/resource-types.md, docs/guides/url.md, website/i18n/en.json, website/sidebars.json
Solves https://github.com/coinbase/rest-hooks/issues/90 and https://github.com/coinbase/rest-hooks/issues/2 among other questions
=> [docs] Reorganize docs; add endpoint and url customization

src/resource/SimpleResource.ts, src/resource/__tests__/resource.ts
Fixes #81 
See issue: https://github.com/coinbase/rest-hooks/issues/81
Simple conditionals!
--- 
Always wanted to submit an open source PR, saw issue #81, seemed like a good start :) Appreciate any feedback
=> [fix] Allow Resource to have urlRoots without a trailing slash

src/resource/Resource.ts, src/resource/__tests__/resource.ts
I want to help with some Architecture clean up to help make RestHooks's codebase easier to read and to contribute from a large audience.
Some nit:
- logic abstraction
- fix some spacing
- fix some style comments
I will help with more general nits before I get into the real problems, let me know @ntucker if you don't mind those changes.
Thank you for this great library.
=> [internal] Abstracted isResponseEmpty conditional in a separate method

salus.yaml
Yarn audit was previously disabled due to issues with it not completing. Should work now
=> [internal] Yarn audit security checks in circle

salus.yaml, yarn.lock
Security is important.
Completely reset yarn.lock; disabled exception and fixed typo in scanners config.
=> [internal] Update all local packages and re-enable yarn security scan

docs/guides/endpoints.md, website/versioned_docs/version-1.6.9/guides/endpoints.md, website/versioned_docs/version-2.0/guides/endpoints.md, website/versioned_docs/version-2.1/guides/endpoints.md, website/versioned_docs/version-3.0/guides/endpoints.md
=> [docs] Fixed typo in docs

package.json, src/.babelrc, yarn.lock
=> [pkg] Upgrade babel and preset

docs/api/makeRenderRestHook.md, docs/guides/unit-testing-hooks.md, website/versioned_docs/version-3.0/api/makeRenderRestHook.md, website/versioned_docs/version-3.0/guides/unit-testing-hooks.md
=> docs: Add note about renderRestHook() wrapping with provider

.circleci/config.yml, website/i18n/en.json
More parallelism, more detailed reports
persist_to_workspace
=> internal: Split circle jobs into pieces

.circleci/config.yml, packages/normalizr/typescript-tests/array.ts, packages/normalizr/typescript-tests/array_schema.ts, packages/normalizr/typescript-tests/denormalize.ts, packages/normalizr/typescript-tests/entity.ts, packages/normalizr/typescript-tests/github.ts, packages/normalizr/typescript-tests/object.ts, packages/normalizr/typescript-tests/relationships.ts, packages/normalizr/typescript-tests/union.ts, packages/normalizr/typescript-tests/values.ts
Normalizr has special typescript tests
Add new CI entry.
=> internal: Run normalizr typescript tests

docs/api/Resource.md, docs/guides/nested-response.md, docs/guides/pagination.md, website/i18n/en.json, website/versioned_docs/version-4.1/api/Resource.md, website/versioned_docs/version-4.1/getting-started/usage.md, website/versioned_docs/version-4.1/guides/computed-properties.md, website/versioned_docs/version-4.1/guides/fetch-then-render.md, website/versioned_docs/version-4.1/guides/nested-response.md, website/versioned_docs/version-4.1/guides/no-suspense.md, website/versioned_docs/version-4.1/guides/pagination.md, website/versioned_docs/version-4.1/guides/resource-types.md, website/versioned_docs/version-4.1/guides/storybook.md, website/versioned_docs/version-4.3/getting-started/usage.md
Fixes #258.
Changed the return value requirements on `pk()`
Update docs since 4.1
=> docs: Update pk() definitions using number fields

.vscode/settings.json, docs/guides/network-transform.md, package.json, packages/rest-hooks/src/state/selectors/__tests__/useDenormalized.ts, yarn.lock
=> pkg: Upgrade to TypeScript 3.8

packages/rest-hooks/src/errors.ts
Makes it a bit more clear what action needs to be taken when this error is thrown
=> enhance: Be more descriptive for not implemented

packages/rest-hooks/src/state/actionCreators.ts
Fixes #294
This would be rather confusing.
Also throw error in dev mode for any negative values as that would make no sense.
=> fix: 0 for expiryLength should not result in default

packages/rest-hooks/src/index.ts, packages/rest-hooks/src/state/NetworkManager.ts, packages/rest-hooks/src/state/actions/createReceive.ts, packages/rest-hooks/src/state/actions/createReceiveError.ts, packages/rest-hooks/src/state/actions/index.ts, packages/rest-hooks/src/state/reducer.ts
Better organization. Will add more soon.
=> internal: Move all action creators to common directory

packages/normalizr/src/entities/__tests__/Entity.test.ts, packages/normalizr/src/entities/__tests__/__snapshots__/Entity.test.ts.snap, packages/rest-hooks/src/state/DefaultConnectionListener.ts, packages/rest-hooks/src/state/__tests__/pollingSubscription.ts, packages/rest-hooks/src/state/__tests__/subscriptionManager.ts
- Cover a few more branches
- remove accidental .only in Entity test
- fix some istanbul ignores for branches not tracked
=> internal: Improve test coverage

packages/normalizr/src/entities/Entity.ts, packages/normalizr/src/entities/__tests__/Entity.test.ts, packages/normalizr/src/entities/__tests__/__snapshots__/Entity.test.ts.snap, packages/normalizr/src/schemas/Array.js, packages/normalizr/src/schemas/__tests__/Array.test.js, packages/normalizr/src/schemas/__tests__/__snapshots__/Array.test.js.snap, packages/rest-hooks/src/resource/__tests__/__snapshots__/resource.ts.snap, packages/rest-hooks/src/resource/__tests__/resource.ts
=> enhance: Detect more cases of network mismatching schema

docs/guides/optimistic-updates.md
Fixes #317 .
Incorporate solution onlined in original issue
=> docs: Add optimistic delete example

packages/normalizr/src/entities/__tests__/Entity.test.ts, packages/normalizr/src/entities/__tests__/SimpleRecord.test.ts, packages/normalizr/src/entities/__tests__/__snapshots__/SimpleRecord.test.ts.snap, packages/normalizr/src/schema.d.ts, packages/normalizr/src/types.ts
Make sure this won't regress.
Already had 'Pagination' Record built, just needed to hook up the tests.
=> fix: Types for nested nullable Record or Entity account for not finding nested pieces

packages/core/src/endpoint/index.ts, packages/core/src/endpoint/shapes.ts, packages/core/src/endpoint/types.ts, packages/core/src/index.ts, packages/core/src/react-integration/__tests__/hooks.tsx, packages/core/src/react-integration/hooks/useFetcher.ts
Default Response for any Shapes is any. However, useFetcher() will attempt to use Denormalized<> to infer a more specific type if this is the case.
=> fix: useFetcher() return types

packages/normalizr/src/schemas/__tests__/Values.test.js, packages/normalizr/src/schemas/__tests__/__snapshots__/Values.test.js.snap
=> internal: Add test for complex schema.Values() case

packages/core/src/react-integration/hooks/useRetrieve.ts, packages/core/src/state/reducer.ts, packages/core/src/types.ts
Once component is mounted it is safe to use normal expiry times.
=> fix: Clear invalidIfStale protections on mount

packages/endpoint/src/endpoint.d.ts, packages/endpoint/src/index.ts, packages/endpoint/src/indexEndpoint.ts, packages/endpoint/src/interface.ts, packages/endpoint/src/types.ts, packages/endpoint/src/utility.ts
=> enhance: Fixup Index type; add EndpointParam

__tests__/common.ts, __tests__/tsconfig.json, jest.config.js, packages/rest-hooks/src/index.ts, packages/rest-hooks/src/resource/Resource.ts, packages/rest-hooks/src/resource/SimpleResource.ts, packages/rest-hooks/src/resource/__tests__/resource.ts, packages/rest-hooks/src/resource/paramsToString.ts, packages/rest-hooks/src/resource/types.ts, packages/rest/src/SimpleResource.ts, packages/rest/src/legacy.ts, packages/rest/tsconfig.json
Incremental upgrade path.
Next step will move legacy Resource to @rest-hooks/legacy.
Adopting new standards by importing from @rest-hooks/rest
=> enhance: Keep legacy Resource

packages/test/src/makeRenderRestHook.tsx
=> fix: Test types

.circleci/config.yml
Node 14 is about to be LTS and has been stable for a while.
New image in circleci config
=> internal: Test on node 14

packages/normalizr/src/denormalize.ts, packages/normalizr/src/entities/SimpleRecord.ts, packages/normalizr/src/normalize.ts, packages/normalizr/src/schemas/Array.js, packages/normalizr/src/schemas/Object.js
=> internal: Only import what is used

__tests__/new.ts, docs/guides/extending-endpoints.md, docs/guides/network-transform.md, packages/core/src/react-integration/__tests__/__snapshots__/hooks-endpoint.web.tsx.snap, packages/core/src/react-integration/__tests__/__snapshots__/integration-endpoint.web.tsx.snap, packages/core/src/react-integration/__tests__/__snapshots__/useCache-endpoint.tsx.snap, packages/core/src/react-integration/__tests__/__snapshots__/useResource-endpoint.web.tsx.snap, packages/core/src/react-integration/__tests__/hooks-endpoint.web.tsx, packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx, packages/core/src/react-integration/__tests__/subscriptions-endpoint.tsx, packages/core/src/react-integration/__tests__/useCache-endpoint.tsx, packages/core/src/react-integration/__tests__/useError-endpoint.tsx, packages/core/src/react-integration/__tests__/useResource-endpoint.web.tsx, packages/core/src/react-integration/hooks/useFetcher.ts, packages/core/src/react-integration/hooks/useSubscription.ts, packages/core/src/state/actions/createFetch.ts, packages/endpoint/src/endpoint.js, packages/endpoint/src/indexEndpoint.ts, packages/rest/src/SimpleResource.ts
=> internal: Test using endpoints directly

docs/api/Resource.md
=> docs: Point to deserilization docs in Resource

package.json, yarn.lock
Test against the latest TypeScript
=> internal: Run on TypeScript 4.1

package.json, yarn.lock
Keep up with latest
- Rebuild locally
=> internal: Bump build packages (minor)

.github/ISSUE_TEMPLATE/bug_report.md
People use different versions now
=> internal: Add rest-hooks version to bug report form

docs/guides/rest-types.md
Make the TL;DR example a bit more clear 
Give the definition of what is used, and link to the API docs for more details
=> docs: Improve REST types doc

packages/rest/CHANGELOG.md, packages/rest/package.json
=> internal: publish

__tests__/new.ts, docs/guides/nested-response.md, packages/rest/src/__tests__/resource-endpoint.ts
With #469, the recommended usage includes nested entities in response.
Reflect new behavior in doc guide for nested resources.
=> docs: Update nested response docs with behaviors of rest package

packages/core/CHANGELOG.md, packages/core/package.json, packages/endpoint/CHANGELOG.md, packages/endpoint/package.json, packages/hooks/CHANGELOG.md, packages/hooks/package.json, packages/legacy/CHANGELOG.md, packages/legacy/package.json, packages/normalizr/CHANGELOG.md, packages/normalizr/package.json, packages/rest-hooks/CHANGELOG.md, packages/rest-hooks/package.json, packages/rest/CHANGELOG.md, packages/rest/package.json, packages/test/CHANGELOG.md, packages/test/package.json
- @rest-hooks/core: 1.0.0-rc.1 => 1.0.0
- @rest-hooks/endpoint: 0.8.0 => 1.0.0
- @rest-hooks/hooks: 0.1.2 => 1.0.0
- @rest-hooks/legacy: 2.0.0-rc.0 => 2.0.0
- @rest-hooks/normalizr: 6.0.0-rc.0 => 6.0.0
- rest-hooks: 5.0.0-rc.1 => 5.0.0
- @rest-hooks/rest: 0.6.1 => 1.0.0
- @rest-hooks/test: 2.0.0-k.2 => 2.0.0
=> internal: Publish 5 final

README.md, packages/core/README.md, packages/rest-hooks/README.md
Will have a whole guide on this topic soon to link to.
=> docs: Update wording for 'cache lifetime' in feature list

website/i18n/en.json
This is generated when build is run, which happens on publish. I forgot to run before creating the commit to cut v5 of docs site.
=> docs: Docs site build gen update missing

README.md, packages/rest/README.md, website/core/Footer.js
Discord is working for now, but still looking to get slack to work. In the meantime no reason we can't show people a space.
=> docs: Add chat badge

README.md, docs/getting-started/endpoint.md, packages/core/README.md, packages/endpoint/README.md, packages/endpoint/package.json, packages/hooks/README.md, packages/hooks/package.json, packages/rest-hooks/README.md, packages/rest/README.md, packages/rest/package.json, packages/test/README.md
- Update links to point to current version of docs since it's launched
- Update stated sizes
- Add more example to test readme
=> docs: Link improvements, flesh out test readme

.commitlintrc.js
Like: https://github.com/ntucker/anansi/pull/70
Underlying issue: streetmix/streetmix#2213
(dependabot breaks commitlint rules
=> internal: Commit-lint rules to make dependabot work

docs/getting-started/installation.md
Better reading experience for docs
Fix the typo so the sentence makes grammatical sense
=> docs: fix typo in installation.md

docs/getting-started/installation.md, docs/guides/auth.md, packages/endpoint/README.md, packages/rest/README.md, website/siteConfig.js, website/versioned_docs/version-5.0/getting-started/installation.md, website/versioned_docs/version-5.0/guides/auth.md
=> docs: Typos and minor improvements

docs/guides/binary-fetches.md, website/i18n/en.json, website/versioned_docs/version-5.0/guides/binary-fetches.md
- Improved user experience - especially with concurrent mode
Tested this code in the concurrent mode demo
It's probably a good idea to simply release this as an npm package - however should we just make a whole package just for suspenseful media? What should we call it?
=> docs: Add suspenseful image example

docs/api/Delete.md, docs/api/useResource.md, docs/api/useRetrieve.md, website/versioned_docs/version-4.0/api/useResource.md, website/versioned_docs/version-4.0/api/useRetrieve.md, website/versioned_docs/version-5.0/api/useResource.md
Some confusion around conditions for fetching
- Make nesting level of list consistent with parenthesis logical order
- Backport reword to 4.0 docs
=> docs: Clarify when useResource, useRetrieve fetch

packages/hooks/README.md
- Fix title
- Add explanations
=> docs: Improve @rest-hooks/hooks README

__tests__/legacy.ts, docs/upgrade/upgrading-to-5.md, packages/rest-hooks/src/resource/Resource.ts, packages/rest-hooks/src/resource/SimpleResource.ts, website/versioned_docs/version-5.0/upgrade/upgrading-to-5.md
Had the methods confused.
Correct:
- fetchOptionsPlugin -> getFetchInit
- getFetchOptions -> getEndpointExtra
- Also update release notes
=> fix: Add getEndpointExtra(), getFetchInit() to legacy Resource

docs/api/useCancelling.md, docs/api/useDebounce.md, docs/api/useLoading.md, docs/api/useResource.md, docs/guides/binary-fetches.md, docs/guides/loading-state.md, website/versioned_docs/version-5.0/api/useCancelling.md, website/versioned_docs/version-5.0/api/useDebounce.md, website/versioned_docs/version-5.0/api/useLoading.md, website/versioned_docs/version-5.0/api/useResource.md, website/versioned_docs/version-5.0/guides/binary-fetches.md, website/versioned_docs/version-5.0/guides/loading-state.md
Links always help understanding and discovery
=> docs: Add links to npm packages

packages/hooks/package.json
=> docs(fix): Fix hooks package link

website/versioned_docs/version-5.0/api/PollingSubscription.md
Hadn't noticed this v1 semantics.
=> docs(fix): Polling subscription to latest usage

.github/workflows/codeql-analysis.yml
=> internal: Add codeql analysis

.github/workflows/benchmark.yml, .github/workflows/main.yml, package.json, packages/normalizr/package.json, packages/normalizr/src/__benchmarks__/benchmark.js, packages/normalizr/src/__benchmarks__/data.json, yarn.lock
Track performance improvements and regressions
https://github.com/rhysd/github-action-benchmark
As far as watching the benchmark results of examples in this repository, the amplitude of the benchmarks is about +- 10~20%. If your benchmarks use some resources such as networks or file I/O, the amplitude might be bigger.
If the amplitude is not acceptable, please prepare a stable environment to run benchmarks. GitHub action supports self-hosted runners.
=> internal: Benchmark CI

package.json, yarn.lock
=> internal(pkg): Remove husky

.github/workflows/benchmark.yml
Wish there was a way to test this more easily
=> internal(fix): Add branch name to both

packages/core/src/state/selectors/useDenormalized.ts, packages/normalizr/package.json, packages/normalizr/src/denormalize.ts, packages/normalizr/tsconfig.compile.json
Now that we know how to publish with multiple TypeScript targets, let's use some TypeScript 4 features.
=> enhance: Use namedtuples for denormalize

__tests__/UnionSchema.ts, packages/normalizr/src/schema.d.ts, packages/normalizr/src/schemas/Polymorphic.js, packages/normalizr/src/schemas/__tests__/Union.test.js, packages/normalizr/src/schemas/__tests__/__snapshots__/Union.test.js.snap
In case undefined shows up in a place a Union is expected
=> fix: Denormalizing polymoprhic with undefined no longer crashes

packages/normalizr/src/entities/Entity.ts, packages/normalizr/src/entities/__tests__/__snapshots__/Entity.test.ts.snap, packages/normalizr/src/schemas/Delete.ts, packages/normalizr/src/schemas/__tests__/Delete.test.ts, packages/normalizr/src/schemas/__tests__/__snapshots__/Delete.test.ts.snap, packages/rest-hooks/src/resource/__tests__/__snapshots__/resource.ts.snap, packages/rest/src/__tests__/__snapshots__/resource-endpoint.ts.snap, packages/rest/src/__tests__/__snapshots__/resource.ts.snap
Help when schema or response is defined wrong
=> enhance: Schema assistance for Delete

packages/core/src/react-integration/__tests__/useMeta-endpoint.tsx, packages/core/src/react-integration/hooks/useMeta.ts, packages/test/src/mockState.ts
Typo not caught due to lack of useMeta test. Adding full suite of type tests here
=> fix: useMeta() parameters type

packages/rest-hooks/src/resource/SimpleResource.ts, packages/rest/src/SimpleResource.ts
Inspired by the @ljharb suggestion in a test spec
=> enhance: Simplify url logic for Resource

docs/guides/custom-networking.md, website/versioned_docs/version-5.0/guides/custom-networking.md
=> docs: Update instructions for custom networking library

README.md, packages/rest-hooks/README.md, website/siteConfig.js
Fixes #831 .
Codesandbox just deleted the demo example
Todo example is much more instructive and has less unrelated things.
=> docs: Change demo to todolist

yarn.lock
'request' is deprecated, which adds annoying warnings
=> pkg: jsdom - no more 'request' dep

packages/experimental/src/index.ts, packages/experimental/src/rest/BaseResource.ts, packages/experimental/src/rest/Resource.ts, packages/experimental/src/rest/paramsToString.ts, packages/experimental/src/rest/types.ts
Until entity is updated
Also changes inheritance so fetch is included, and endpoints are not defined in BaseResource
=> feat: Add Resource that extends from new Entity

packages/core/src/state/__tests__/reducer.ts, packages/core/src/state/actions/createReceive.ts, packages/core/src/state/reducer.ts, packages/core/src/types.ts, packages/experimental/README.md, packages/experimental/src/createFetch.ts, website/siteConfig.js
What updates is likely dependent on args. This is especially useful for pagination
Spread in as remaining args to first update function. These can be ignored in case they are not needed.
=> enhance: Provide args to update method

packages/experimental/package.json
Reliance on new core stuff. Forgot to bump in previous commit
=> fix: Correct peerDeps

packages/experimental/src/index.ts, packages/experimental/src/rest/Resource.ts, packages/experimental/src/rest/types.ts, packages/experimental/src/types.ts
Just as the types from @rest-hooks/rest
=> feat: Export types for Resource

packages/experimental/README.md
Missed this when landing this feature.
=> docs: Add paginated() to readme

packages/normalizr/src/normalize.ts
expiry only needs to be updated once per entire normalization step. this prevents extra work when entities appear multiple times in one request
=> enhance: Improve normalization speed

packages/experimental/src/entity/Entity.ts, packages/experimental/src/entity/__tests__/__snapshots__/NewEntity.test.ts.snap, packages/normalizr/src/entities/Entity.ts
Easily customize validation - disable, enable in prod, etc.
Refactor existing block and move into protected method. Call in normalize
=> feat: Add Entity.validate()

.github/workflows/benchmark.yml
Some of the benchmarks test core now
=> internal: Run benchmarks on core package changes

packages/experimental/package.json, packages/hooks/package.json, packages/img/package.json, packages/legacy/package.json, packages/test/package.json
Now that the behavior is known for the upcoming versions, let's make sure all the packages work with it.
For those where reliance are not changing we simply add the new versions to the list of support.
=> feat: Mark compatibility with upcoming versions

packages/core/src/react-integration/hooks/useCache.ts, packages/core/src/react-integration/hooks/useError.ts, packages/core/src/react-integration/hooks/useFetcher.ts, packages/core/src/react-integration/hooks/useInvalidator.ts, packages/core/src/react-integration/hooks/useMeta.ts, packages/core/src/react-integration/hooks/useResetter.ts, packages/core/src/react-integration/hooks/useResource.ts, packages/core/src/react-integration/hooks/useRetrieve.ts, packages/core/src/react-integration/hooks/useSubscription.ts, packages/core/src/react-integration/provider/CacheProvider.tsx, packages/endpoint/src/endpoint.d.ts, packages/endpoint/src/endpoint.js, packages/endpoint/src/indexEndpoint.ts, packages/experimental/src/createFetch.ts, packages/experimental/src/rest/BaseResource.ts, packages/experimental/src/rest/Resource.ts, packages/experimental/src/useFetcher.ts, packages/hooks/src/useCancelling.ts, packages/hooks/src/useDebounce.ts, packages/hooks/src/useLoading.ts, packages/legacy/src/useStatefulResource.ts, packages/normalizr/src/entities/Entity.ts, packages/normalizr/src/schemas/Array.js, packages/normalizr/src/schemas/Delete.ts, packages/normalizr/src/schemas/Object.js, packages/normalizr/src/schemas/Union.js, packages/normalizr/src/schemas/Values.js, packages/rest-hooks/src/react-integration/NetworkErrorBoundary.tsx, packages/rest/src/Resource.ts
Easier docs discovery
https://jsdoc.app/tags-see.html
=> docs: Add doc links to jsdocs

packages/experimental/package.json, packages/hooks/package.json, packages/img/package.json
5-maintenance branch bumped these already
=> internal: Account for maintenance branch release versions

packages/core/package.json, packages/endpoint/package.json, packages/legacy/package.json, packages/normalizr/package.json, packages/rest-hooks/package.json, packages/rest/package.json, packages/test/package.json
We don't support things that don't understand conditionals
=> enhance: Remove 'fallback' package.json exports

packages/core/src/react-integration/hooks/hasUsableData.ts, packages/core/src/state/actions/createFetch.ts, packages/normalizr/src/denormalize.ts, packages/normalizr/typescript-tests/denormalize.ts, packages/rest-hooks/src/react-integration/NetworkErrorBoundary.tsx, packages/test/src/makeRenderRestHook.tsx
Simplify code and less bytes for targets that include it. Also the transpilation size has reduced, so it's not as harmful to others.
=> enhance: Use optional chaining

packages/core/CHANGELOG.md, packages/core/package.json, packages/endpoint/CHANGELOG.md, packages/endpoint/package.json, packages/experimental/CHANGELOG.md, packages/experimental/package.json, packages/hooks/CHANGELOG.md, packages/hooks/package.json, packages/img/CHANGELOG.md, packages/img/package.json, packages/legacy/CHANGELOG.md, packages/legacy/package.json, packages/legacy/rollup.config.js, packages/normalizr/CHANGELOG.md, packages/normalizr/package.json, packages/normalizr/src/__tests__/index.test.js, packages/normalizr/src/normalize.ts, packages/rest-hooks/CHANGELOG.md, packages/rest-hooks/package.json, packages/test/CHANGELOG.md, packages/test/package.json
@ljharb Is this how I do the merge updates as you suggested? Open PR then use merge rather than squash?
=> internal: Merge 5 maintenance to master

packages/core/CHANGELOG.md, packages/endpoint/CHANGELOG.md, packages/experimental/CHANGELOG.md, packages/hooks/CHANGELOG.md, packages/img/CHANGELOG.md, packages/legacy/CHANGELOG.md, packages/normalizr/CHANGELOG.md, packages/rest-hooks/CHANGELOG.md, packages/test/CHANGELOG.md
Merges 5-maintenance and resolved conflicts
=> internal: Merge 5-maintenance

docs/api/README.md
=> fix link for Managers

packages/core/src/state/reducer.ts
Fixes #1073 .
Users are liable to write functions that throw errors. In these cases
- be graceful
- be loud
- all errors in reducer's receive are console.error in devmode
- errors during Endpoint.update() are always console.error instead of reducing.
- the state will still update with whatever it had
=> enhance: Improve reducer error visibility

docs/guides/nested-response.md
Fix typo in ->  https://resthooks.io/docs/guides/nested-response
Current: defintion
Fix: definition
=> docs(fix): typo in nested-response.md

examples/todo-app/package.json, package.json, yarn.lock
New webpack config needed for webpack-dev-server v4
=> pkg: Bump anansi - compat with webpack-dev-server@4 

.github/dependabot.yml
Being on next means this gets spammy
=> internal: Dependabot - ignore react

packages/experimental/src/createInvalidate.ts, packages/experimental/src/createReset.ts, packages/experimental/src/index.ts, packages/experimental/src/useController.ts, packages/experimental/src/useFetcher.ts
- options object makes it more discoverable and explicit what is being
set while allowing for potential future options
- add action creators
- createInvalidate
- createReset
BREAKING CHANGE: useController(true) -> useController({ throttle: true
})
=> enhance: useController() takes configuration options

docs/getting-started/entity.md, website-2/docusaurus.config.js
New search integration for v2 of docusaurus.
=> docs: Update search integration

website-2/blog/2021-08-29-Experimental-useController.md, website-2/docusaurus.config.js
Document changes in https://github.com/coinbase/rest-hooks/pull/1048 and https://github.com/coinbase/rest-hooks/issues/760
=> docs: Add blog announcing experimental pkg and usecontroller

packages/core/src/index.ts, packages/core/src/state/NetworkManager.ts, packages/experimental/src/rest/BaseResource.ts, packages/legacy/src/resource/Resource.ts, packages/rest/src/Resource.ts
Easier identification of errors
=> enhance: Give errors a name

docs/getting-started/endpoint.md, docs/getting-started/entity.md, docs/introduction.md, website-2/docusaurus.config.js
- Some link fixes
- Change website copyright footer to Nathaniel.
- Logo was purchased from my own money
- Domain purchased with my own money
=> docs: Assorted minor

docs/graphql/auth.md, docs/graphql/usage.md, docs/introduction.md, jest.config.js, packages/graphql/.gitignore, packages/graphql/LICENSE, packages/graphql/README.md, packages/graphql/node.mjs, packages/graphql/package.json, packages/graphql/rollup.config.js, packages/graphql/src/GQLEndpoint.ts, packages/graphql/src/GQLEntity.ts, packages/graphql/src/GQLNetworkError.ts, packages/graphql/src/__tests__/gql.ts, packages/graphql/src/index.ts, packages/graphql/tsconfig.compile.json, packages/graphql/tsconfig.json, tsconfig-base.json, tsconfig.json, website-2/sidebars.json
Fixes #361 .
GraphQL made easy with rest hooks.
- This is a prerelease so we're not doing the same rigor of testing. However, this was validated in a real world project.
- Error handling not as elegant as @rest-hooks/rest yet.
- First version requires explicit schema passing to use. Future could interpolate from the querystring itself.
```typescript
const gql = new GQLEndpoint('https://nosy-baritone.glitch.me');
```
```typescript
class User extends GQLEntity {
readonly name: string = '';
readonly email: string = '';
}
```
```typescript
const userList = gql.query(
`{
users {
id
name
email
}
}`,
{ users: [User] },
);
const userDetail = gql.query<{ name: string }>(
`query UserDetail($name: String!) {
user(name: $name) {
id
name
email
}
}`,
{ user: User },
);
```
```tsx
const { user } = …
```
=> feat: Add @rest-hooks/graphql

website/docusaurus.config.js, website/versioned_docs/version-5.0/api/Delete.md, website/versioned_docs/version-5.0/api/Endpoint.md, website/versioned_docs/version-5.0/api/Entity.md, website/versioned_docs/version-5.0/api/Manager.md, website/versioned_docs/version-5.0/getting-started/data-dependency.md, website/versioned_docs/version-5.0/getting-started/endpoint.md, website/versioned_docs/version-5.0/getting-started/entity.md, website/versioned_docs/version-5.0/getting-started/expiry-policy.md, website/versioned_docs/version-5.0/getting-started/installation.md, website/versioned_docs/version-5.0/graphql/auth.md, website/versioned_docs/version-5.0/graphql/usage.md, website/versioned_docs/version-5.0/guides/auth.md, website/versioned_docs/version-5.0/guides/custom-networking.md, website/versioned_docs/version-5.0/guides/extending-endpoints.md, website/versioned_docs/version-5.0/introduction.md, website/versioned_docs/version-5.0/rest/usage.md, website/versioned_sidebars/version-5.0-sidebars.json
=> docs: Cut 6.0 verison for doc site

docs/api/Endpoint.md, docs/api/Entity.md, docs/api/Resource.md, docs/api/useFetcher.md, docs/getting-started/expiry-policy.md, docs/getting-started/validation.md, docs/guides/immediate-updates.md, website/package.json, website/versioned_docs/version-5.0/api/Endpoint.md, website/yarn.lock
Fixes #888
Reflect changes in 6 from 5
=> docs: Update 6.0 docs with latest

docs/api/Entity.md, docs/api/README.md, docs/api/SimpleRecord.md, docs/api/schema.md, docs/getting-started/entity.md, website/sidebars.json, website/src/pages/index.js
=> docs: More updates for 6

packages/rest-hooks/src/index.ts
Missed adding to rest-hooks package
=> feat: Export useController()

examples/github-app/src/pages/IssueDetail/index.tsx, examples/todo-app/src/pages/Home/NewTodo.tsx, examples/todo-app/src/pages/Home/TodoListComponent.tsx, examples/todo-app/src/pages/Home/TodoListItem.tsx
Demonstrate new way of doing things
=> enhance: useController() in examples

packages/core/src/controller/__tests__/fetch.tsx, packages/core/src/react-integration/__tests__/__snapshots__/integration-endpoint.web.tsx.snap, packages/core/src/react-integration/__tests__/__snapshots__/integration.web.tsx.snap, packages/core/src/react-integration/__tests__/__snapshots__/subscriptions-endpoint.tsx.snap, packages/core/src/react-integration/__tests__/endpoint-types.web.tsx, packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx, packages/core/src/react-integration/__tests__/integration-nesting.web.tsx, packages/core/src/react-integration/__tests__/integration-optimistic-endpoint.web.tsx, packages/core/src/react-integration/__tests__/integration.web.tsx, packages/core/src/react-integration/__tests__/subscriptions-endpoint.tsx, packages/core/src/react-integration/__tests__/subscriptions.tsx, packages/experimental/src/__tests__/useFetcher.ts
More sane code, integrate better with jest tooling.
Previously using vscode jest debugger didn't work on for loop tests
=> internal: Use describe.each instead of for loop

packages/core/src/react-integration/provider/BackupBoundary.tsx
=> enhance: Hoist conditional for Boundary SSR

website/docusaurus.config.js
Had it coming from the wrong existing url
=> docs(fix): Redirect

README.md, packages/core/README.md, packages/endpoint/README.md, packages/experimental/README.md, packages/graphql/README.md, packages/hooks/README.md, packages/img/README.md, packages/legacy/README.md, packages/normalizr/README.md, packages/rest-hooks/README.md, packages/rest/README.md, packages/use-enhanced-reducer/README.md
Failing PR branches shouldn't make the project look bad
=> docs: Only validate circleCI badge against master

docs/graphql/usage.md, website/package.json, website/src/components/Demo/ResourceDemo.js, website/src/components/HooksPlayground.js, website/src/components/Playground/StoreInspector.tsx, website/src/components/Playground/Tree.tsx, website/src/components/Playground/index.js, website/src/components/Playground/store.module.css, website/src/components/Playground/styles.module.css, website/src/pages/index.js, website/src/pages/index.module.css, website/yarn.lock
Better understanding of what is happening
Store is
- togglable
- persists toggle globally and between sessions (using docusaurus tab context)
=> docs: Add store inspector to playground

docs/api/Array.md, docs/api/Delete.md, docs/api/Entity.md, docs/api/Object.md, docs/api/SimpleRecord.md, docs/api/Union.md, docs/api/Values.md, docs/graphql/usage.md, docs/guides/nested-response.md, website/src/components/HooksPlayground.js, website/src/components/Playground/StoreInspector.tsx, website/src/components/Playground/Tree.tsx, website/src/components/Playground/index.js
Easier learning comes with playing.
Default to open the store so it's clear how the data is transformed.
=> docs: Use live demos for schema docs

docs/api/Controller.md, docs/api/Resource.md, docs/guides/auth.md, website/versioned_docs/version-6.1/api/Controller.md, website/versioned_docs/version-6.1/api/Resource.md, website/versioned_docs/version-6.1/guides/auth.md
In the future we will provide many different Resource implementations for different concepts like this.
=> docs: Add useFetchInit() usage implications

website/src/components/Demo/index.js
Keep homepage at 6.1
Revert this when releasing 6.2
=> docs: Homepage should use 6.1 (useResource) for now

docs/guides/optimistic-updates.md, website/versioned_docs/version-6.1/guides/optimistic-updates.md
Improve documentation.
Before:
```const { fetch } = useController();```
After:
```const { update } = useController();```
=> docs(fix): Typo on optimistic update page

website/package.json, website/yarn.lock
https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.14
=> docs(pkg): Bump docusarus

website/src/components/Playground/Tree.tsx
Breaking change from https://github.com/coinbase/rest-hooks/pull/1608
=> docs(fix): Update tree-view import to match latest version

examples/benchmark/package.json, examples/normalizr-github/package.json, examples/normalizr-redux/package.json, examples/normalizr-relationships/package.json, lerna.json, package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/endpoint/CHANGELOG.md, packages/endpoint/package.json, packages/legacy/CHANGELOG.md, packages/legacy/package.json, packages/normalizr/CHANGELOG.md, packages/normalizr/package.json, packages/rest-hooks/CHANGELOG.md, packages/rest-hooks/package.json, packages/test/CHANGELOG.md, packages/test/package.json
- @rest-hooks/core: 3.1.0-beta.2 => 3.1.0-beta.3
- @rest-hooks/endpoint: 2.1.0 => 2.2.0-beta.0
- @rest-hooks/legacy: 4.1.0-beta.1 => 4.1.0-beta.2
- @rest-hooks/normalizr: 8.1.0 => 8.2.0-beta.0
- rest-hooks: 6.2.0-beta.2 => 6.2.0-beta.3
- @rest-hooks/test: 7.1.3 => 7.2.0-beta.0
=> internal: publish pre-release

website/package.json, website/src/components/Demo/CodeProvider.tsx, website/src/components/Playground/Result.tsx, website/src/components/Playground/Tree.tsx, website/src/components/Playground/index.js, website/static/mockServiceWorker.js, website/yarn.lock
Latest beta changed exports.
Also updated can-i-use-lite
=> docs(fix): Fix site for docusaurus exports changes

.github/ISSUE_TEMPLATE/bug_report.md
Adding more relevant version information that informs bug issues
=> internal: Update bug template with more info

packages/rest-hooks/src/manager/DevtoolsManager.ts
Much easier to debug if timestamps are readable
Use `Intl` if available.
=> enhance: Format timestamps in redux devtools for ease of reading

package.json, yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-4-6
=> pkg: Typescript 4.6

packages/ssr/.gitignore, packages/ssr/LICENSE, packages/ssr/README.md, packages/ssr/node.mjs, packages/ssr/package.json, packages/ssr/rollup.config.js, packages/ssr/src/ServerDataComponent.tsx, packages/ssr/src/createPersistedStore.tsx, packages/ssr/src/index.ts, packages/ssr/tsconfig.compile.json, packages/ssr/tsconfig.json, tsconfig-base.json, tsconfig.json, yarn.lock
Ensures populated cache upon hydration.
Docs to come in later PR.
Package bootstrap copy/paste from graphql package
=> feat: Add @rest-hooks/ssr

website/docusaurus.config.js, website/package.json, website/src/components/Demo/index.js, website/yarn.lock
Just the changes for breaking between betas
https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.17
https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.16
=> docs: docusaurus 2.0.0-beta.17

website/src/components/Playground/resources/TodoResource.ts, website/static/mockServiceWorker.js
Had arg order wrong on website
=> docs(fix): Fix website demo

examples/benchmark/reducer.js, examples/github-app/package.json, examples/github-app/src/App.tsx, examples/github-app/src/RootProvider.tsx, examples/github-app/src/index.tsx, examples/github-app/src/navigation/LinkPagination.tsx, examples/github-app/src/navigation/NavBar.tsx, examples/github-app/src/pages/IssueDetail/CommentsList.tsx, examples/github-app/src/pages/IssueDetail/index.tsx, examples/github-app/src/pages/IssueList.tsx, examples/github-app/src/pages/ProfileDetail.tsx, examples/github-app/src/resources/UserResource.ts, examples/github-app/src/routing/index.tsx, examples/github-app/src/routing/routes.tsx, examples/todo-app/src/pages/Home/TodoListComponent.tsx, examples/todo-app/src/resources/TodoResource.ts, yarn.lock
Update examples to use latest best practices
=> enhance: Use @anansi/router and latest hooks

packages/core/src/controller/createOptimistic.ts, packages/core/src/controller/createReceive.ts, packages/core/src/state/createReducer.ts, packages/graphql/src/GQLEndpoint.ts, packages/normalizr/src/WeakListMap.ts, packages/rest-hooks/src/manager/PollingSubscription.ts, packages/rest-hooks/src/manager/SubscriptionManager.ts
Changes based on turning on the `exactOptionalPropertyTypes` flag
=> enhance: More exact optional type handling

packages/rest-hooks/src/index.ts
See https://github.com/coinbase/rest-hooks/pull/1866
```ts
const { data, loading, error } = useDLE(MyResource.list());
```
=> feat: Export useDLE()

examples/github-app/package.json, examples/todo-app/package.json, package.json, packages/core/src/react-integration/__tests__/hooks-endpoint.web.tsx, packages/core/src/react-integration/__tests__/hooks.web.tsx, packages/core/src/react-integration/newhooks/__tests__/useFetch.web.tsx, packages/experimental/src/hooks/__tests__/useFetch.web.tsx, yarn.lock
17->18. They also included a change to how component types work that required update to children props
=> internal: React types to 18

website/yarn.lock, yarn.lock
=> internal(pkg): Bump pacote and async

.circleci/config.yml, .github/workflows/benchmark.yml, examples/github-app/package.json, examples/todo-app/package.json
https://github.com/webpack/webpack/issues/14532
=> internal: Use node 18 for test

.github/dependabot.yml, yarn.lock
Fixes salus complaints:
```bash
Package: moment
Patched in: >=2.29.4
Dependency of: github-app
More info: https://www.npmjs.com/advisories/1080969
Severity: high
Title: Inefficient Regular Expression Complexity in moment
ID: 1080969
Line number: 13214
```
=> internal(pkg): moment (patch - security)

examples/todo-app/src/pages/Home/index.tsx, yarn.lock
rc-utils duplicates breaks antd due to context singleton mismatches.
=> internal(pkg): Consolidate babel/runtime and rc-utils

packages/core/src/state/NetworkManager.ts
Fixes #2091 .
New StrictMode feature https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state will unmount and remount all components twice. This means bad news for any imperative effects. In other words, while previously unmounting meant we could safely assume the component will be complete reset; this now could result in the component reappearing - with its previous state intact.
Due to this, we essentially want a toggle variable that simply determines whether the component is *currently* mounted. This way, if it is remounted we can process everything like it was never unmounted to begin with. In other words, unmounting must be **reversable**
Validated this fixes issues caused when using StrictMode with the Todo example
=> fix: 18.2 StrictMode compatibility

renovate.json
Trying to get this right ...trial and error as the docs are very minimal.
=> internal: Adjust renovate

docs/rest/guides/extending-endpoints.md
=> docs: Fix UserResource.current() example

website/package.json, website/yarn.lock, yarn.lock
Weird yarn patching typescript issue breaking pnp detection
=> internal(fix): Typescript package resolution to make docs site work

docs/core/guides/unit-testing-components.md, examples/github-app/src/pages/IssueDetail/CommentsList.tsx, examples/github-app/src/pages/IssueDetail/index.tsx, examples/github-app/src/pages/ProfileDetail/UserRepos.tsx, examples/github-app/src/resources/Comment.ts, examples/github-app/src/resources/Reaction.tsx, examples/github-app/src/resources/User.ts
- Improve definition patterns
- Handle edge cases
=> internal: Some improvements to github example

renovate.json, website/package.json, website/yarn.lock
New version has issues with website
=> internal: Don't update downlevel-dts

docs/core/getting-started/validation.md, packages/test/src/MockResolver.tsx, packages/test/src/mockState.ts, website/package.json, website/src/components/HooksPlayground.tsx, website/src/components/Playground/FixturePreview.tsx, website/src/components/Playground/Preview.tsx, website/src/components/Playground/StoreInspector.tsx, website/src/components/Playground/Tree.tsx, website/src/components/Playground/index.tsx, website/src/components/Playground/styles.module.css, website/yarn.lock
Better experience in docs site
=> docs: Improve live editor playground

README.md, docs/core/README.md, docs/core/api/MockResolver.md, docs/core/concepts/network-errors.md, docs/rest/api/Endpoint.md, docs/rest/api/RestEndpoint.md, docs/rest/api/createResource.md, docs/rest/guides/abort.md, docs/rest/guides/computed-properties.md, docs/rest/guides/optimistic-updates.md, packages/rest-hooks/README.md, website/src/components/Demo/index.js, website/src/components/Playground/Preview.tsx
[RestEndpoint](https://resthooks.io/rest/api/RestEndpoint)
=> docs: Random docs fixes

docs/rest/api/RestEndpoint.md, docs/rest/api/createResource.md, docs/rest/api/hookifyResource.md, docs/rest/guides/summary-list.md, packages/rest/src/RestEndpoint.d.ts, packages/rest/src/pathTypes.ts, website/docusaurus.config.js, website/sidebars-rest.js, website/src/css/customTheme.css, website/yarn.lock
More confusion-avoidance based on #2215 feedback
=> docs: Add summary list guide

docs/rest/api/Array.md, docs/rest/api/Delete.md, docs/rest/api/Entity.md, docs/rest/api/Object.md, docs/rest/api/Union.md, docs/rest/api/Values.md, docs/rest/guides/optimistic-updates.md, website/docusaurus.config.js, website/profiling-plugin.js, website/src/components/Playground/Boundary.tsx, website/src/components/Playground/FixturePreview.tsx, website/src/components/Playground/Header.tsx, website/src/components/Playground/Preview.tsx, website/src/components/Playground/PreviewBlock.tsx, website/src/components/Playground/PreviewWithScope.tsx, website/src/components/Playground/babelTransform.tsx, website/src/components/Playground/index.tsx, website/src/components/Playground/styles.module.css, website/src/css/customTheme.css, website/src/css/root.css, website/yarn.lock
Damn google bots
Turns out the problem was the CLS was not a perfect score of 0. This includes other improvements but the key was making the fonts preload properly.
https://support.google.com/webmasters/thread/184180392?hl=en
=> docs: Improve init render perf

packages/use-enhanced-reducer/src/useEnhancedReducer.ts
Imperative access to state is a valid use case, but currently restricted to use in middlewares. This means that components must bind into the React lifecycle just to use logic based on state. This manifests in reports like https://github.com/coinbase/rest-hooks/issues/2053#issuecomment-1286536353 and https://github.com/coinbase/rest-hooks/issues/1468
Provide same imperative access that middlewares get. Then can subsequently be used to bind to the controller.
=> feat: Return getState method as third arg

packages/rest/src/createResource.ts
I forgot this in the rest patch
=> enhance: Get rid of extraneous type BaseResource

README.md, docs/rest/api/Endpoint.md, docs/rest/api/Entity.md, docs/rest/api/RestEndpoint.md, docs/rest/diagrams/_endpoint_error_lifecycle.mdx, docs/rest/diagrams/_endpoint_success_lifecycle.mdx, docs/rest/diagrams/_entity_lifecycle.mdx, docs/rest/diagrams/_restendpoint_lifecycle.mdx, packages/core/README.md, packages/rest-hooks/README.md, website/blog/2022-10-23-Announcing-Rest-6.md, website/blog/2022-11-07-Lifecycle-controlflow-diagrams-mermaid.md, website/src/components/Playground/monaco-init.ts, website/yarn.lock
https://resthooks.io/blog/2022/11/07/Lifecycle-controlflow-diagrams-mermaid
=> docs: Add diagram blog post

docs/core/api/useLive.md, docs/core/getting-started/data-dependency.md, examples/nextjs/pages/api/ExchangeRates.ts, website/blog/2022-12-19-rest-hooks-7-react-native-web-nextjs.md, website/yarn.lock
Had a typo making it not work on one page. Just consolidated definitions to also make plurality consistent.
=> docs: Fix Exchange Rates api definition

docs/core/getting-started/endpoint.md, docs/rest/api/Entity.md, docs/rest/api/RestEndpoint.md, docs/rest/guides/summary-list.md, examples/github-app/src/pages/IssueDetail/index.tsx, examples/github-app/src/pages/IssueList.tsx, examples/nextjs/pages/api/hello.ts, examples/nextjs/pages/index.tsx, examples/normalizr-github/index.js, examples/normalizr-redux/index.js, examples/normalizr-redux/src/redux/index.js, examples/normalizr-redux/src/redux/modules/commits.js, examples/normalizr-redux/src/redux/modules/issues.js, examples/normalizr-redux/src/redux/modules/labels.js, examples/normalizr-redux/src/redux/modules/milestones.js, examples/normalizr-redux/src/redux/modules/pull-requests.js, examples/normalizr-relationships/index.js, examples/todo-app/src/RootProvider.tsx, examples/todo-app/src/pages/Home/TodoListItem.tsx, website/src/components/TypeScriptEditor.tsx
Also includes formatting fixes for `examples/`
=> docs: More TypeScript previews

docs/rest/guides/pagination.md, website/docusaurus.config.js, website/src/components/Demo/CodeEditor.tsx, website/src/components/Demo/index.js, website/src/components/Playground/Tree.tsx
- also fix JSONTree breaking change options for initial expanded tree
=> docs: Split application demo into multiple tabs

packages/ssr/CHANGELOG.md, packages/ssr/package.json, yarn.lock
Was supposed to be 6.3 not 7.3
=> fix: ssr peerdep

packages/core/src/manager/SubscriptionManager.ts, website/src/components/Playground/editor-types/@rest-hooks/core.d.ts
Better cleanup in prep to move to handling new actions
=> enhance: Distinctly handle legacy and new actions

packages/endpoint/src/schemas/Object.ts, packages/normalizr/src/denormalize.ts
=> enhance: Denormalize code clean and slight optimize

docs/rest/api/Endpoint.md, docs/rest/api/RestEndpoint.md, packages/endpoint/src/__tests__/endpoint.ts, packages/endpoint/src/endpoint.d.ts, packages/endpoint/src/endpoint.js, packages/graphql/src/GQLEndpoint.ts, packages/graphql/src/__tests__/gql.ts, website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts, website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts, website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
Easier Interceptors and invalidateAll
=> feat: Add Endpoint.testKey

packages/normalizr/src/WeakEntityMap.ts, packages/normalizr/src/__tests__/WeakEntityMap.test.ts, packages/normalizr/src/denormalize.ts, website/src/components/Playground/editor-types/@rest-hooks/core.d.ts, website/src/components/Playground/editor-types/@rest-hooks/normalizr.d.ts
Share `getEntity` with WeakEntityMap and unvisitEntity
=> enhance: Denormalize optimizations

.circleci/config.yml, docs/core/guides/unit-testing-components.md
=> internal: Build types in setup

.circleci/config.yml
=> internal: Test against node 14, 16

packages/react/src/hooks/types.ts, packages/react/src/hooks/useCache.ts, packages/react/src/hooks/useDLE.ts, packages/react/src/hooks/useError.ts, packages/react/src/hooks/useFetch.native.ts, packages/react/src/hooks/useFetch.ts, packages/react/src/hooks/useLive.ts, packages/react/src/hooks/useSubscription.native.tsx, packages/react/src/hooks/useSubscription.tsx, packages/react/src/hooks/useSuspense.native.ts, packages/react/src/hooks/useSuspense.ts, packages/redux/package.json, yarn.lock
You can only import from packages your declare as dep
=> fix: PnP compatibility

.changeset/hungry-files-double.md, packages/normalizr/src/normalize.ts
Faster is better
Hoist index handling logic better enabling function optimization.
=> feat: Hoist normalize index handling into function

packages/normalizr/src/normalize.ts
=> internal: Rename variables in normalize

.changeset/polite-trainers-greet.md, docs/core/api/useCache.md, examples/benchmark/core.js, packages/core/src/controller/BaseController.ts
https://www.measurethat.net/Benchmarks/Show/24691/0/min-reducer-vs-imperative-with-paths
=> enhance: Improve entity expiry calc performance in getResponse()

website/src/components/Playground/MonacoPreloads.tsx, website/src/components/Playground/PlaygroundMonacoEditor.tsx, website/src/components/Playground/PlaygroundTextEdit.tsx, website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts, website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts, website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts, website/src/components/Playground/editor-types/@rest-hooks/rest/next.d.ts, website/src/components/Playground/editor-types/rest-hooks.d.ts, website/src/components/Playground/monaco-init.ts
Easier to explore demos - especially with resources in potentially hidden areas
https://user-images.githubusercontent.com/866147/235776229-fd070381-39f6-4cc2-aa05-994a9d075bc2.mp4
- Use the new [monaco.editor.registerEditorOpener](https://github.com/microsoft/vscode/pull/177064).
- Trigger focus events which lets React side appropriately update UI
- Update CDN monaco loading to 0.38.0 and make easier to update with centralized version config.
=> docs: Handle go to definition in editor

packages/endpoint/src/schema.d.ts, packages/rest/src/extractCollection.ts, packages/rest/src/mapCollection.ts, packages/rest/src/next/createResource.ts, website/src/components/Playground/MonacoPreloads.tsx
Predictable behavior in classes.
```ts
<C extends schema.Collection>
type A = schema.Collection<Array<Todo>>
```
=> enhance: Make Collections extendable and usable as class type

.changeset/khaki-toys-worry.md, examples/github-app/src/resources/Base.ts, examples/github-app/src/resources/Comment.ts, examples/github-app/src/resources/Reaction.tsx, examples/todo-app/src/resources/PlaceholderBaseResource.ts, examples/todo-app/src/resources/TodoResource.ts, website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts, website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts, website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts, website/src/components/Playground/editor-types/@rest-hooks/rest/next.d.ts
- Validate usage
- Provide migration example
=> enhance: Use rest/next in examples

packages/normalizr/src/WeakEntityMap.ts, packages/normalizr/src/denormalize/denormalize.ts, packages/normalizr/src/denormalize/denormalizeCached.ts, packages/normalizr/src/denormalize/globalCache.ts, packages/normalizr/src/denormalize/unvisit.ts
=> enhance: Performance improvements based on deopt inspection

.changeset/early-glasses-jump.md, .changeset/few-windows-drum.md, packages/react/src/__tests__/hooks-endpoint.web.tsx, packages/react/src/components/CacheStore.tsx, packages/react/src/context.ts, packages/react/src/index.ts, packages/react/src/internal.ts, packages/redux/src/ExternalCacheProvider.tsx, website/src/components/Playground/editor-types/@data-client/react.d.ts
Previously deprecated; taking up space;
Remove DispatchContext, DenormalizeCacheContext (previously deprecated)
=> enhance: Remove DispatchContext, DenormalizeCacheContext

__tests__/new.ts, packages/core/src/manager/__tests__/networkManager.ts, packages/core/src/state/__tests__/reducer.ts, packages/react/src/__tests__/integration-endpoint.web.tsx, packages/react/src/__tests__/integration-optimistic-endpoint.web.tsx, packages/react/src/components/__tests__/backupboundary.node.tsx, packages/react/src/components/__tests__/provider.native.tsx, packages/react/src/components/__tests__/provider.node.tsx, packages/react/src/hooks/__tests__/useController/fetch.tsx
Remove certain test endpoints as being optimistic as the tests were not written under this assumption
Also improve console.error ignoring
=> internal: Fix model definitions for some test

.changeset/quick-sloths-buy.md, __tests__/new.ts, packages/react/src/__tests__/integration-optimistic-endpoint.web.tsx, packages/rest/src/createResource.ts, packages/rest/src/resourceTypes.ts
FormData is a useful way to construct payloads
Basic FormData handling with Resource in both *types* and *optimistic: true*
=> feat: Support FormData in Resource updates and creates

.changeset/flat-bees-matter.md, packages/endpoint/src/schema.d.ts, packages/endpoint/src/schemaTypes.ts, packages/endpoint/tsconfig.compile.json, packages/endpoint/tsconfig.json, website/src/components/Playground/editor-types/@data-client/endpoint.d.ts, website/src/components/Playground/editor-types/@data-client/graphql.d.ts, website/src/components/Playground/editor-types/@data-client/rest.d.ts, website/src/components/Playground/editor-types/@data-client/rest/next.d.ts
We want to minimize what's in a .d.ts
=> internal: Move type helpers for schema out to another file

.changeset/five-paws-burn.md, .changeset/tiny-dingos-count.md, docs/core/api/NetworkManager.md, docs/core/api/PollingSubscription.md, docs/core/api/SubscriptionManager.md, packages/core/src/actionTypes.ts, packages/core/src/manager/NetworkManager.ts, packages/core/src/manager/SubscriptionManager.ts, packages/core/src/manager/__tests__/__snapshots__/pollingSubscription.ts.snap, packages/core/src/state/__tests__/reducer.ts, packages/react/src/__tests__/__snapshots__/hooks-endpoint.web.tsx.snap, packages/react/src/hooks/__tests__/__snapshots__/useFetch.native.tsx.snap, packages/react/src/hooks/__tests__/__snapshots__/useFetch.web.tsx.snap, packages/react/src/hooks/__tests__/__snapshots__/useSuspense.native.tsx.snap, packages/react/src/hooks/__tests__/__snapshots__/useSuspense.web.tsx.snap, packages/ssr/src/getInitialData.ts
[RDC = Reactive Data Client](https://dataclient.io/)
=> enhance: Rename action type prefix to rdc

.github/workflows/benchmark.yml, examples/benchmark/package.json
=> internal: Use node 20 for benchmark

examples/coin-app/src/App.tsx, examples/coin-app/src/pages/AssetDetail/AssetChart.tsx, examples/coin-app/src/pages/AssetDetail/LineChart.tsx, examples/coin-app/src/pages/AssetDetail/Stats.tsx, examples/coin-app/src/pages/AssetDetail/index.tsx, examples/coin-app/src/resources/Candles.ts, examples/coin-app/src/style/main.css
=> docs: Add asset charts to coin detail page

.circleci/config.yml, examples/normalizr-github/package.json, examples/normalizr-redux/package.json, website/package.json, yarn.lock
=> internal: Explicitly include only examples needed by CI

packages/core/rollup.config.mjs, packages/endpoint/rollup.config.mjs, packages/graphql/rollup.config.mjs, packages/img/rollup.config.mjs, packages/normalizr/rollup.config.mjs, packages/react/rollup.config.mjs, packages/rest/rollup.config.mjs, packages/test/rollup.config.mjs, packages/use-enhanced-reducer/rollup.config.mjs, scripts/rollup-plugins/rollup-utils.js
=> internal: Rollup input from src instead of lib

.changeset/angry-spoons-play.md, packages/react/src/hooks/useCache.ts, packages/react/src/hooks/useDLE.native.ts, packages/react/src/hooks/useDLE.ts, packages/react/src/hooks/useFetch.native.ts, packages/react/src/hooks/useFetch.ts, packages/react/src/hooks/useSuspense.native.ts, packages/react/src/hooks/useSuspense.ts
=> enhance: Use controller.getResponseMeta() in hooks

packages/normalizr/src/normalize/addEntities.ts, packages/normalizr/src/normalize/normalize.ts
Cleaner code reading
Simplify normalize call by moving bookkeeping variables inside scope of the function using them.
=> enhance: Optimize normalize call construction
