.circleci/config.yml

- `--prefer-offline`: faster install
- `--frozen-lockfile`: fails if package.json doesn't match yarn.lock (yarn.lock should be updated)

[internal] use checksum yarn.lock and add args to yarn

---

src/state/__tests__/__snapshots__/reducer.ts.snap
src/state/__tests__/reducer.ts
src/state/reducer.ts

Fixes https://github.com/coinbase/rest-hooks/issues/21
For both rpc and purge we should simply not update state.

[fix] Gracefully handle network errors for 'rpc' and 'purge' types

---

src/react-integration/NetworkErrorBoundary.tsx

```tsx
console.log(error, error.status, Object.prototype.hasOwnProperty.call(error, 'status'));
```

[fix] Network error can have an undefined status

---

src/state/__tests__/reducer.ts
src/state/reducer.ts

Adresses #9 
lodash merge only recursively merges arrays and plain objects, not class instances.
Use lodash mergeWith and a customizer that can handle instances of Resource.
The `resourceCustomizer` function will merge Resources recursively.

[enhance] Merge changes to resource instances

---

docs/README.md
docs/api/RequestShape.md
docs/api/Resource.md
docs/guides/resource-lifetime.md
src/__tests__/common.ts
src/index.ts
src/react-integration/__tests__/__snapshots__/hooks.tsx.snap
src/react-integration/__tests__/hooks.tsx
src/react-integration/hooks/useFetcher.ts
src/resource/Resource.ts
src/resource/types.ts
src/state/NetworkManager.ts
src/state/__tests__/networkManager.ts
src/types.ts

This feature allows defining custom data and error lifetimes for resources and request shapes.
NetworkManager will pass on dataExpiryLength and errorExpiryLength from FetchAction. Defaults to NetworkManager values if undefined.
Static dataExpiryLength and errorExpiryLength fields on Resource, undefined by default. Passed to all request shapes.

[feature] Support for custom dataExpiryLength and errorExpiryLength on resources

---

src/__tests__/common.ts
src/react-integration/__tests__/integration.tsx
src/resource/Resource.ts
src/resource/__tests__/__snapshots__/resource.ts.snap
src/resource/__tests__/resource.ts

Sometimes when nested resources (server-side join) the server will only include partial results in some of the cases. This will merge them so they get the most complete picture possible.
This is especially important to support graphql which regularly includes partial results.

[enhance] Merge results from partial nested resources

---

docs/guides/network-errors.md

[docs] Remove a tiny "s" typo in network errors doc

---

docs/api/makeRenderRestHook.md
src/react-integration/__tests__/integration.tsx
src/react-integration/__tests__/subscriptions.tsx
src/test/index.ts
src/test/makeRenderRestHook.tsx
src/test/providers.tsx

- Change name of `makeRenderRestHook` file from helper to match the name of the default export.
- Change `makeRenderRestHook` to take in an array of fixtures instead of initialState so that hooks using useCache can be properly tested.
NOTE: running `yarn eslint --fix --ext .ts,.tsx src` and `yarn format` change `makeRenderRestHook` back and forth, indenting and un-indenting part of the code.
Closes https://github.com/coinbase/rest-hooks/issues/63

[breaking][test] renderRestHook() takes results fixtures in options instead of initialState

---

package.json
src/react-integration/provider/__tests__/middleware.tsx
src/react-integration/provider/middleware.ts
src/state/NetworkManager.ts
src/types/scheduler.d.ts
tsconfig.json

Before getState() would only ever return the initial value. This was not caught as it is never actually used by the existing managers.
We use a ref here so we can retrieve inside a mutable object.

[fix] Send most updated state to manager middleware

---

docs/api/README.md
docs/getting-started/installation.md
docs/getting-started/usage.md
docs/guides/immutability.md
docs/guides/loading-state.md
docs/guides/network-errors.md
website/i18n/en.json
website/sidebars.json
website/siteConfig.js

- Made API README page a bit more descriptive
- Header points of 'Resource Definitions' rather than 'guide' readme
- pulled out basics and resource definitions part of guide to top level; labeled the rest 'advanced'

[docs] Reorganize guides into new categories

---

.eslintrc
src/react-integration/hooks/useFetcher.ts
src/react-integration/hooks/useMeta.ts
src/react-integration/hooks/useResultCache.ts
src/react-integration/hooks/useRetrieve.ts
src/react-integration/hooks/useSelection.ts
src/react-integration/provider/ExternalCacheProvider.tsx

- Had to disable some lines due to params needing to be serialized to have any meaning.
- Improved useFetcher() by boxing the requestShape() since it's values are only needed at call-time in dispatch().

[fix] exhaustive-deps lint; make useFetch() recompute less

---

src/react-integration/provider/RestProvider.tsx

Default function parameters are evaluated every call (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters), so a new manager was created. By using defaultProps we enable React to only create them as the component is created.
Likely avoids issues like https://github.com/coinbase/rest-hooks/issues/78 and https://github.com/coinbase/rest-hooks/issues/50

[fix] Avoid recreating default managers by using defaultProps

---

package.json
src/test/MockProvider.tsx
src/test/makeRenderRestHook.tsx
src/test/managers.ts
src/test/mockState.ts
src/test/providers.tsx

Fixes https://github.com/coinbase/rest-hooks/issues/85

[fix][test] MockProvider should use the same context as root imports

---

rollup.config.js

https://github.com/coinbase/rest-hooks/pull/86 supposedly fixed this issue, but I somehow missed updating the 'external' specification. Tested this with a repo extensively using the testing framework here.

[fix][test] Fix build so test.cjs imports properly

---

jest.config.js
package.json
src/react-integration/context.ts
src/react-integration/hooks/useCache.ts
src/react-integration/hooks/useError.ts
src/react-integration/hooks/useFetcher.ts
src/react-integration/hooks/useInvalidator.ts
src/react-integration/hooks/useMeta.ts
src/react-integration/hooks/useResource.ts
src/react-integration/hooks/useResultCache.ts
src/react-integration/hooks/useRetrieve.ts
src/react-integration/hooks/useSelection.ts
src/react-integration/hooks/useSubscription.ts
src/react-integration/provider/ExternalCacheProvider.tsx
src/react-integration/provider/RestProvider.tsx
src/react-integration/provider/middleware.ts
src/resource/Resource.ts
src/resource/types.ts
src/state/NetworkManager.ts
src/state/PollingSubscription.ts
src/state/SubscriptionManager.ts
src/state/getEntityPath.ts
src/state/reducer.ts
src/state/selectors.ts
tsconfig.json
yarn.lock

In my issue https://github.com/grrowl/ts-transformer-imports/issues/15#issuecomment-506940292 someone pointed out that [@zerollup/ts-transform-paths](https://www.npmjs.com/package/@zerollup/ts-transform-paths) seemed to work for this. Seems to be working so far.
This time I opened the .d.ts files in /lib after a build to ensure the relative paths were there (the transform should be changing the ~/). Also after re-opening vscode, it was able to resolve all type imports in the src files as well.

[internal] Use absolute library imports

---

docs/getting-started/installation.md
package.json
rollup.config.js
src/.babelrc
yarn.lock

This makes the library more flexible to different usages.
- Different polyfill libraries can be used (helps with https://github.com/coinbase/rest-hooks/issues/25)
- Old browsers can be unsupported without adding to bundle size
- Different bundles targeting different browsers can be built.
- Potential feature-detection of polyfills

[breaking] Don't import polyfills but assume they are already loaded

---

website/blog/2019-07-10-Announcing-Rest-Hooks-2.0.md
website/i18n/en.json
website/siteConfig.js

Forgot to change this to be landing on master before deleting next branch.
Closes https://github.com/coinbase/rest-hooks/issues/95

[docs] Add blog announcing 2.0

---

src/__tests__/common.ts
src/resource/Resource.ts
src/resource/__tests__/resource.ts

Fixes https://github.com/coinbase/rest-hooks/issues/106
This maintains url's type as readonly string unless overridden. However, technically in JS people can set (this is fine as we don't enforce JS-side anyway). Setting JS side is necessary to make setting default property work. Technically this still limits descendants to only using string type for url. However, this seems unlikely to be a problem as I can't imagine something named 'url' being a number. Most likely any issues with this will be if someone uses an object type. Will revisit if that becomes an issue.

[fix] Allow Resource to have 'url' member

---

docs/guides/endpoints.md
docs/guides/network-transform.md
docs/guides/rpc.md

I found that the docs were out of date, using the latest release (2.0.3) when it came to using `SchemaBase`. The migration page says that the interface was renamed and so the docs were not correct.
This PR replaces references of the outdated interface `SchemaBase` to `SchemaDetail` in the docs.

[docs] Replace SchemaBase with SchemaDetail

---

docs/api/FetchShape.md
docs/api/useFetcher.md
docs/api/useResource.md
docs/api/useRetrieve.md
docs/api/useSubscription.md
docs/guides/custom-networking.md
docs/guides/endpoints.md
docs/guides/mocking-unfinished.md
docs/guides/network-transform.md
docs/guides/no-suspense.md
docs/guides/pagination.md
src/index.ts
src/react-integration/hooks/useError.ts
src/react-integration/hooks/useFetcher.ts
src/react-integration/hooks/useResource.ts
src/react-integration/hooks/useRetrieve.ts
src/react-integration/hooks/useSubscription.ts
src/resource/Resource.ts
src/resource/SimpleResource.ts
src/resource/index.ts
src/resource/types.ts
src/test/mockState.ts

Strings are completely legal arguments for body so they should be allowed.

[enhance] Allow string type for body (payload) parameters

---

src/fsa.ts
src/index.ts
src/resource/Resource.ts
src/state/__tests__/reducer.ts
src/state/reducer.ts
src/test/mockState.ts
src/types.ts

Bad network responses can happen even in production - catching all client side code won't help that.
Do early checks to ensure error messages are graceful and the code still runs. Remove production checks for such things. Production checks should only happen if it's conceivable that hitting those points during development of the JS will prevent the issue from happening in production. Since server code is independent of JS this cannot be reasonably expected.
- Resource.fetch() will always (including prod) guard against invalid responses
- (for actions) Payload type is more discriminatory: object | string | number. Does not allow void.
- Export new types RPCAction, PurgeAction
- Future work: make fetch return promise resolve to object | string | number instead of any.

[enhance] Handle null fetch response even in production

---

jest.config.js
package.json
src/index.ts
src/react-integration/hooks/index.ts
src/react-integration/hooks/useCache.ts
src/react-integration/hooks/useError.ts
src/react-integration/index.ts
src/state/__tests__/selectors.ts
src/state/selectors.ts
yarn.lock

Fixes #126.
Reselect's sole existence is to provide short-circuiting on a per-component basis with a memoization memory of one. This is identical to the capabilities of useMemo(), so there's no reason to add an additional dependency.
Turn our selector into a hook selector. This restricts its capability to be run inside hook contexts but that's already the assumption.

[enhance] useMemo() instead of reselect (bundle size reduction)

---

src/react-integration/NetworkErrorBoundary.tsx
src/state/__tests__/merge.tsx
src/state/__tests__/networkManager.ts
src/state/__tests__/reducer.ts
src/state/merge/isMergeable.ts
src/state/merge/mergeDeepCopy.ts
src/state/reducer.ts

Lodash.mergeWith is pretty bloated. Custom solution will be much more efficient.
Integrated deepmerge that detects .merge members

[enhance] Use own deepmerge instead of lodash.mergeWith

---

src/__tests__/common.ts
src/resource/normal.d.ts
src/state/selectors/__tests__/buildInferredResults.ts
src/state/selectors/buildInferredResults.ts

Should support full range of schema types. Types before were sloppy and non-specific.
- Adding tests for both Values and Unions in useDenormalized()
- Fleshing out all cases for typescript types - including resolving Denormalized<S> and ResultType<S>

[enhance] Fully support Union and Values schemas in types and useDenormalized()

---

src/react-integration/hooks/useResource.ts
src/react-integration/hooks/useResourceNew.ts

While it technically worked before, React would complain about the dependency list changing size. 
Let's keep it the same size by simply changing the resolution to false if a promise is not active

[fix] Keep promise sync list the same size so React doesn't complain

---

src/react-integration/__tests__/fixtures.ts
src/react-integration/__tests__/hooks.tsx
src/react-integration/hooks/useRetrieve.ts

Previously, useRetrive() (and thus also useResource()) would trigger fetches anytime the component it was used in re-rendered for any reason - so long as the data was considered stale. This is not the designated behavior.
* Breaks idempotence of render()
* Which resulted in unpredictable fetches
We were previously syncing to `dataStale` for our fetch trigger. This is bad because it is derivative data of Date.now() - which is not idempotent. By the transitive property, any component using this hook not idempotent. **General rule: only sync with values that are derived from React-controlled state (context, props, useState) and/or things that are constant.**
Issue discovered by @saivann
We need to move the check for Date.now() inside our hook callback so we don't need to sync on it. We can …

[fix] useRetrieve(): Only refetch on param changes

---

src/react-integration/__tests__/hooks.tsx
src/react-integration/__tests__/useResourceNew.tsx
src/react-integration/hooks/hasUsableData.ts
src/react-integration/hooks/useError.ts
src/react-integration/hooks/useResource.ts
src/react-integration/hooks/useResourceNew.ts
src/state/selectors/useSchemaSelect.ts

https://github.com/coinbase/rest-hooks/pull/109 incorporated some useful improvements to error mechanisms. However, after careful consideration it seems like not the best approach, so this should incorporate those improvements and some others.
* Never generate errors when params are null (previously could create fake 404 when resource wasn't found)
* Improve some typings to factor in conditional of param being null
* multi-resource requests now immediately throw error on first error and stop suspending.

[enhance] Improve useResource() error handling conditions

---

src/resource/normal.d.ts

- Fake nominal typing for schema types (since they have pretty similar signatures).
- future: should change to tracking return value of normalize as that can encode proper typings. We can use the schema provided and build on that to pretty convincingly manifest the algo. This can replace the giant ResultType and Denormalized block.
- Add missing readonly member schema
- Include Array in Schema and SchemaList def
- Add greedy resolution to Entity in ResultType and Denormalized generics.
- This means if we only have SchemaDetail or SchemaList it will resolve to T and T[] respectively. While we don't actually know this - it enables a broad base class definition for our REST shapes. In the future a better solution is to simply make those shapes a mixin and encourage more often writing own …

[enhance] Improve normalizr type expressiveness

---

src/__tests__/common.ts
src/react-integration/__tests__/__snapshots__/hooks.tsx.snap
src/react-integration/__tests__/fixtures.ts
src/react-integration/__tests__/hooks.tsx
src/react-integration/__tests__/integration.tsx
src/react-integration/hooks/useFetcher.ts
src/resource/types.ts
src/state/NetworkManager.ts
src/state/__tests__/applyUpdatersToResults.ts
src/state/__tests__/networkManager.ts
src/state/__tests__/reducer.ts
src/state/applyUpdatersToResults.ts
src/state/reducer.ts
src/types.ts

Fixes https://github.com/coinbase/rest-hooks/issues/96
Provide both the mechanism for common case optimistic updates, as well as well designed extension points for unusual cases like https://github.com/coinbase/rest-hooks/issues/124
Update the API of the function returned from `useFetcher` to take in an array of updaters:
```ts
const createArticle = useFetcher(ArticleResource.createShape());
createArticle({ id: 1 }, {}, [
[ArticleResource.listShape(), {}, (newArticle, articles) => [...articles, newArticle]]
])
```
Additionally, this supports the same case for GETs, in the case of pagination:
```ts
class PaginatedArticleResource extends Resource {
readonly id: number | null = null;
readonly title: string = '';
readonly content: string = '';
readonly author: number | null = null;
readonly …
```

[feature] Add optimistic update on create

---

package.json
src/state/selectors/__tests__/useDenormalized.ts
src/state/selectors/useDenormalized.ts
yarn.lock

The inferred state of an array nested would be something like `{ results undefined }` and this was being detected as 'found' and thus not suspending.
Added a gauntlet of tests for usedDenormalized(). Many are adapted from useSchemaSelect(), but additional use cases were added as well.

[fix] Suspend properly when loading nested array schemas

---

docs/api/Manager.md
docs/guides/redux.md
src/index.ts
src/react-integration/__tests__/hooks.tsx
src/react-integration/__tests__/useResourceNew.tsx
src/react-integration/context.ts
src/react-integration/provider/ExternalCacheProvider.tsx
src/react-integration/provider/__tests__/middleware.tsx
src/react-integration/provider/__tests__/provider.tsx
src/react-integration/provider/middleware.ts
src/react-integration/provider/usePromisifiedDispatch.ts
src/state/NetworkManager.ts
src/state/PollingSubscription.ts
src/state/RIC.ts
src/state/SubscriptionManager.ts
src/state/__tests__/networkManager.ts
src/state/__tests__/subscriptionManager.ts
src/test/managers.ts
src/test/providers.tsx
src/types.ts

React useReducer() operates differently than redux; thus needing a different middleware API. The primary difference being the async nature. State is committed async, and thus using as synchronous API doesn't allow for doing things after the state is committed or even knowing what the final state is.
Promises make this all very nice. The dispatch function now returns a promise that resolves to void. This is reflected in next(action) in the middleware API, as this eventually calls through to the promise. This also means all middleware functions must pass through that promise to work. Thankfully typescript will enforce this and help ensure this is properly followed.
This also means the NetworkManager's middleware has been cleaned up as it can now easily resolve its promises only after the …

[breaking] Make middleware async - enabling execution after commit

---

src/resource/types.ts

Fixes #120.
Void types are only valid in delete
object | string | number | boolean represents all possible JSON values.

[breaking] ReadShape and MutateShape fetch resolve to valid JSON non-void

---

docs/api/FetchShape.md
docs/api/Resource.md
docs/api/useInvalidator.md
docs/api/useResetter.md
docs/api/useSubscription.md
docs/guides/mocking-unfinished.md
docs/guides/resource-lifetime.md
src/__tests__/common.ts
src/index.ts
src/resource/SimpleResource.ts
src/resource/types.ts
src/types.ts

Fixes #144.
RequestShape was renamed FetchShape, so should its options.
- RequestOptions -> FetchOptions
- SimpleResource.getRequestOptions() -> SimpleResource.getFetchOptions()

[breaking] RequestOptions -> FetchOptions

---

README.md
docs/api/Resource.md
docs/api/useSubscription.md
docs/getting-started/usage.md
docs/guides/computed-properties.md
docs/guides/jsonp.md
docs/guides/multi-pk.md
docs/guides/nested-response.md
docs/guides/no-suspense.md
docs/guides/pagination.md
docs/guides/resource-types.md
docs/guides/storybook.md
docs/guides/url.md
src/__tests__/common.ts
src/resource/SimpleResource.ts

Fixes #118.
One of the main purposes of SimpleResource.pk() is to pass as a key in React. However, React types keys as possibly being undefined - not null so the type should reflect that here.
Switch type of pk to include undefined instead of null.

[breaking] pk() type should be string | number | undefined

---

src/resource/SimpleResource.ts

The recommended approach to entities are to have them be immutable and thus using readonly at the TypeScript level can enforce this. However, some may find repeatedly typing readonly for each field in their definitions to be cumbersome.
Define all methods returning SimpleResource to wrap the instance type in Readonly<>
Might this violate the principal of least surprise? Probably better to give them type errors when they don't expect it and can easily do something than have people actually modify their Resources as that behavior is not supported.

[breaking] Force all attributes as readonly on SimpleResource

---

package.json
src/.babelrc
yarn.lock

- IE is becoming less and less common
- Noone uses it out of the box as a developer
- Can still be built to target it by building this package inline
- This has a pretty significant reduction in shipping codesize.
Set browserslist that ignores IE as well as using @rest-hooks/normalizr version that does as well

[breaking] Drop IE support (out of the box)

---

package.json
src/index.ts
src/resource/SimpleResource.ts
src/resource/index.ts
src/resource/shapes.ts
src/resource/types.ts
src/state/selectors/useDenormalized.ts
src/types.ts
yarn.lock

3.7 just released. Ensure compatibility with the latest.
Due to repeat def conflicts https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#local-and-imported-type-declarations-now-conflict I converted more of the re-exports of pure-types to use the `export * from` pattern as the babel code still includes them due to https://github.com/babel/babel/issues/8361

[pkg] Upgrade TypeScript to 3.7

---

docs/guides/no-suspense.md
packages/rest-hooks/src/react-integration/hooks/hasUsableData.ts
website/versioned_docs/version-3.0/guides/no-suspense.md

Fixes #181 
Types were a bit out of date from 3.0 transition. Confirmed this working in both code and types in anansi example project.
Update docs in current and 3.0 release. Also remove generics (unnecessary) from hasUsableData()

docs: Update useStatefulResource() in guides

---

docs/guides/no-suspense.md
website/versioned_docs/version-3.0/guides/no-suspense.md

There's a bit more complexity with the 3.0 version of things to detect fully loaded state.
We'll have to pull the `ready` information from useDenormalized() ourselves.

docs: Make useStatefulResource() work with nested schemas

---

.circleci/config.yml
.eslintrc
.gitignore
package.json
packages/rest-hooks/jest.config.js
packages/rest-hooks/package.json
packages/rest-hooks/src/react-integration/__tests__/hooks.tsx
packages/rest-hooks/src/react-integration/__tests__/integration.tsx
packages/rest-hooks/src/react-integration/__tests__/subscriptions.tsx
packages/rest-hooks/src/react-integration/__tests__/useCache.tsx
packages/rest-hooks/src/react-integration/__tests__/useResource.tsx
packages/rest-hooks/src/tsconfig.json
packages/rest-hooks/tsconfig.compile.json
packages/rest-hooks/tsconfig.json
packages/test/package.json
packages/test/tsconfig.compile.json
packages/test/tsconfig.json
tsconfig-base.json
tsconfig.json
yarn.lock

This simplifies and makes more robust monorepo configuration
Remapping based on /src was weird. Now paths are only needed for IDE integration, and should be ignored at build.
https://www.typescriptlang.org/docs/handbook/project-references.html improve typescript speed, while eliminating the need for weird src remapping. TypeScript source maps allow editors to reference the .d.ts files while still going to the ./src when looking up in IDEs.
- lint: use wildcard tsconfig to pick up each directory's config
- circle: build from root and let tsc orchestrate build order for types via `--build` option
- publishing: run `ttsc --build` before lerna publish to build types first
- OPEN QUESTION: perhaps entire build should be done first in publish script and no build done in each dir?
- add src to …

internal: Use TypeScript project references

---

.circleci/config.yml
Dockerfile

If a package is changed, there still may be related packages that attempt to get installed around it, if those resolve to the same as in the yarn cache speed can improve.
Also save yarn cache folder.

internal: Improve circleci speed by saving yarn cache

---

package.json

normal.d.ts was renamed to schemaLegacy.d.ts in #167, but the build script was not updated
Fixes #192  .

[fix] schemaLegacy TypeScript import

---

packages/rest-hooks/src/index.ts
packages/rest-hooks/src/react-integration/index.ts
packages/rest-hooks/src/react-integration/provider/PromiseifyMiddleware.ts
packages/rest-hooks/src/react-integration/provider/index.ts
packages/test/package.json
packages/test/src/providers.tsx

Fixes #196 .
The docs listed importing PromiseifyMiddleware, but this was never exported.

fix: export PromiseifyMiddleware

---

packages/rest-hooks/package.json
salus.yaml

If a user doesn't install their type checks can fail

fix: Add lodash types

---

docs/api/Resource.md
docs/guides/network-transform.md

Fixes #185 .
Deserializing fields is a common use case when computing derived information

docs: Add deserialization fields example

---

.circleci/config.yml
Dockerfile
packages/rest-hooks/src/state/__tests__/networkManager.ts

Node 12 is in LTS, people will want to run it.
Rely on async middleware api for promise resolution as batching logic is not as consistent

fix: Tests run in node 12

---

docs/api/README.md
docs/api/Resource.md
docs/api/SimpleRecord.md
packages/rest-hooks/src/index.ts
packages/rest-hooks/src/react-integration/index.ts
packages/rest-hooks/src/resource/SimpleRecord.ts
packages/rest-hooks/src/resource/SimpleResource.ts
packages/rest-hooks/src/resource/index.ts
packages/rest-hooks/src/state/PollingSubscription.ts
packages/rest-hooks/src/state/SubscriptionManager.ts
website/i18n/en.json
website/sidebars.json

Resource needs to be split up anyway, and I realized that this is one piece that already works.
Pull data methods into SimpleRecord that SimpleResource extends.
Naming....I don't really like SimpleRecord, but not sure what else to call it. I don't want to call it Record since that's a typescript generic util type.

feat: export SimpleRecord which has the data methods of Resource

---

docs/guides/custom-networking.md
docs/guides/network-transform.md
packages/rest-hooks/src/resource/Resource.ts
packages/rest-hooks/src/resource/SimpleResource.ts

BREAKING CHANGE: Remove generic signatures to any Resource.fetch()
overrides
Generic parameters are useful if they dictate the return value, but in the case of fetch, is Promise<any> so it's completely pointless.

enhance: Resource.fetch() is no longer generic

---

docs/api/Resource.md
docs/guides/network-transform.md
docs/guides/pagination.md
packages/rest-hooks/src/resource/Resource.ts
packages/rest-hooks/src/resource/SimpleResource.ts
packages/rest-hooks/src/resource/__tests__/resource.ts

* url() and listUrl() params are no longer optional
* Removed resolveFetchData() in favor of fetchResponse().
* fetch() now calls fetchResponse()
* This means custom use of Response can be achieved by calling
fetchResponse() in custom FetchShape.fetch
Custom use of Response like for grabbing headers tends to be on a per-shape basis. This design better suites building custom fetch() functions for FetchShape.

enhance: Easier to handle http fetch headers in response

---

docs/guides/fetch-then-render.md
website/blog/2019-12-24-Rest-Hooks-4.0-Released.md
website/i18n/en.json
website/sidebars.json
website/versioned_docs/version-3.0/guides/fetch-then-render.md
website/versioned_docs/version-4.0/guides/fetch-then-render.md
website/versioned_sidebars/version-3.0-sidebars.json
website/versioned_sidebars/version-4.0-sidebars.json

Good user experiences and concurrent mode need this pattern.
- Backfill to 4.0 and 3.0 docs.
- Use existing demo https://codesandbox.io/s/concurrent-react-example-ly1ds
- Will update with better demo when any routing library actually supports this pattern

docs: Add fetch-then-render guide

---

packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/index.d.ts
packages/normalizr/src/index.js

Fixes #215.
Sometimes APIs have very simple responses. Let's not ban simple strings.
- Update types
- Add tests
- Handle strings - even empty ones
Example usage:
```typescript
static updateShape() {
return {
...super.updateShape(),
schema: '',
};
}
```

feat: Support string schemas

---

__tests__/utils.ts
docs/api/PollingSubscription.md
packages/rest-hooks/src/state/PollingSubscription.ts
packages/rest-hooks/src/state/__tests__/isOnline.ts
packages/rest-hooks/src/state/__tests__/pollingSubscription.ts
packages/rest-hooks/src/state/isOnline.ts

Fetching while offline is not only wasteful, it will result in a perfectly working website turning into network errors.
- Listen to online/offline events.
- When going online immediately dispatch a fetch.

enhance: Polling subscriptions handle offline/online

---

packages/rest-hooks/src/state/PollingSubscription.ts
packages/rest-hooks/src/state/__tests__/pollingSubscription.ts
website/versioned_docs/version-4.0/api/PollingSubscription.md

When following fetch-then-render pattern, this can simplify usage as a useRetrieve() will not longer be needed together. Is fine to use in conjunction with useResource() since fetches are all deduped.
Immediately call fetch for new subscriptions if online.

enhance: Immediately fetch polling subscriptions

---

packages/rest-hooks/src/react-integration/__tests__/hooks.tsx
packages/rest-hooks/src/react-integration/__tests__/integration.tsx
packages/rest-hooks/src/react-integration/__tests__/subscriptions.tsx
packages/rest-hooks/src/react-integration/__tests__/useCache.tsx
packages/rest-hooks/src/react-integration/__tests__/useResource.tsx
packages/rest-hooks/tsconfig.compile.json

Ambient libs for rest-hooks package were importing normalizr using relative path rather than library @rest-hooks/normalizr
- Move tsconfig.compile.json path into 'compilerOptions' as that is it's location.
- Make test imports non-relative as well

fix: Import @rest-hooks/normalizr properly

---

packages/rest-hooks/src/state/SubscriptionManager.ts

Fixes #234 .
[Redux-toolkit](https://redux-toolkit.js.org/) is a fairly popular way to use redux
Loosen types to be more flexible on actions.

fix: Make SubscriptionManager type compatible with redux-toolkit

---

packages/rest-hooks/src/react-integration/__tests__/hooks.tsx
packages/rest-hooks/src/react-integration/hooks/useFetcher.ts
packages/rest-hooks/src/react-integration/hooks/useInvalidator.ts
packages/rest-hooks/src/react-integration/hooks/useResetter.ts
packages/rest-hooks/src/react-integration/hooks/useSubscription.ts
packages/rest-hooks/src/react-integration/provider/__tests__/provider.tsx
packages/rest-hooks/src/state/NetworkManager.ts
packages/rest-hooks/src/state/PollingSubscription.ts
packages/rest-hooks/src/state/SubscriptionManager.ts
packages/rest-hooks/src/state/__tests__/networkManager.ts
packages/rest-hooks/src/state/__tests__/reducer.ts
packages/rest-hooks/src/state/__tests__/subscriptionManager.ts
packages/rest-hooks/src/state/reducer.ts
packages/rest-hooks/src/types.ts

- This ensures type-enforceability against any potential typos.
- This also allows minifiers to reduce bundle size.
Put all action type strings at the top of types.ts file.
This also exports the action types. (This increases bundle size for non-es case, but also makes easier to build custom managers)
```typescript
export const FETCH_TYPE = 'rest-hooks/fetch' as const;
export const RECEIVE_TYPE = 'rest-hooks/receive' as const;
export const RECEIVE_MUTATE_TYPE = 'rest-hooks/rpc' as const;
export const RECEIVE_DELETE_TYPE = 'rest-hooks/purge' as const;
export const RESET_TYPE = 'rest-hooks/reset' as const;
export const SUBSCRIBE_TYPE = 'rest-hooks/subscribe' as const;
export const UNSUBSCRIBE_TYPE = 'rest-hook/unsubscribe' as const;
export const INVALIDATE_TYPE = 'rest-hooks/invalidate' as …
```

enhance: Centralize action type string definitions

---

packages/rest-hooks/src/actionTypes.ts
packages/rest-hooks/src/react-integration/__tests__/hooks.tsx
packages/rest-hooks/src/react-integration/hooks/useFetcher.ts
packages/rest-hooks/src/react-integration/hooks/useInvalidator.ts
packages/rest-hooks/src/react-integration/hooks/useResetter.ts
packages/rest-hooks/src/react-integration/hooks/useSubscription.ts
packages/rest-hooks/src/react-integration/provider/__tests__/provider.tsx
packages/rest-hooks/src/state/NetworkManager.ts
packages/rest-hooks/src/state/PollingSubscription.ts
packages/rest-hooks/src/state/SubscriptionManager.ts
packages/rest-hooks/src/state/__tests__/networkManager.ts
packages/rest-hooks/src/state/__tests__/reducer.ts
packages/rest-hooks/src/state/__tests__/subscriptionManager.ts
packages/rest-hooks/src/state/reducer.ts
packages/rest-hooks/src/types.ts

Will export in future `@rest-hooks/core` package, but pollutes namespace in rest-hooks

enhance: Don't export action types

---

packages/rest-hooks/src/react-integration/__tests__/hooks.tsx
packages/rest-hooks/src/react-integration/hooks/useFetcher.ts

Delete shapes are special in that they ignore the actual fetch response, and simply use the Entity definition to lookup what entries to delete in the entities cache.
This could be confusing for those defining delete shapes, so it's important to give a heads up in this case - especially if TypeScript is not used.
throw error

enhance: Devmode: Throw error if delete shape fetched with wrong schema

---

packages/test/package.json

New package bumps every rest-hooks release for test, and only dev env is the monorepo so the peerdep will be there.

internal: Remove devDep of rest-hooks from test

---

packages/normalizr/src/__tests__/__snapshots__/index.test.js.snap
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/index.js

Say you have defaults that are null
```typescript
schema = {
pagination: {
nextData: null,
prevData: null,
},
data: [EntityThing.asSchema()],
}
```
But then you get a network response like:
```json5
{
pagination: {
nextData: { token: 'five' },
prevData: null,
},
data: { id: 'something', title: 'whatever' },
}
```
Simply guard against empty schema when visiting

fix: Support extra members of schema that are only sometimes empty

---

packages/normalizr/src/__tests__/__snapshots__/index.test.js.snap
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/index.js
packages/normalizr/src/schemas/Object.js

Say you have defaults that are null
```typescript
schema = {
pagination: {
nextData: null,
prevData: null,
},
data: [EntityThing.asSchema()],
}
```
But then you get a network response like:
```json5
{
pagination: {
nextData: { token: 'five' },
prevData: null,
},
data: { id: 'something', title: 'whatever' },
}
```
Make denormalize ok with empty schemas.

fix: Support extra members of schema that are empty in denormalize

---

packages/rest-hooks/src/state/NetworkManager.ts
packages/rest-hooks/src/state/actionCreators.ts

- Easier to read
- Enables repeat usage of action creators - for instance in optimistic update feature
```typescript
export declare function createReceive<Payload extends object | string | number = object | string | number, S extends Schema = any>(data: Payload, { schema, url, responseType, updaters, options, }: FetchAction<Payload, S>['meta'], { dataExpiryLength }: {
dataExpiryLength: number;
}): ReceiveAction<Payload, S> | RPCAction<Payload, S> | PurgeAction;
export declare function createReceiveError<S extends Schema = any>(error: any, { schema, url, responseType, options }: FetchAction<any, S>['meta'], { errorExpiryLength }: {
errorExpiryLength: number;
}): ResponseActions;
```

internal: Move action creation into own functions

---

__tests__/common.ts
docs/ROADMAP.md
docs/api/FetchShape.md
docs/guides/optimistic-updates.md
packages/rest-hooks/src/react-integration/__tests__/__snapshots__/hooks.tsx.snap
packages/rest-hooks/src/react-integration/__tests__/integration.tsx
packages/rest-hooks/src/react-integration/__tests__/useResource.tsx
packages/rest-hooks/src/react-integration/hooks/useFetcher.ts
packages/rest-hooks/src/react-integration/provider/CacheProvider.tsx
packages/rest-hooks/src/react-integration/provider/ExternalCacheProvider.tsx
packages/rest-hooks/src/react-integration/provider/__tests__/__snapshots__/provider.tsx.snap
packages/rest-hooks/src/state/NetworkManager.ts
packages/rest-hooks/src/state/__tests__/__snapshots__/reducer.ts.snap
packages/rest-hooks/src/state/__tests__/networkManager.ts
packages/rest-hooks/src/state/__tests__/reducer.ts
packages/rest-hooks/src/state/reducer.ts
packages/rest-hooks/src/state/selectors/__tests__/useDenormalized.ts
packages/rest-hooks/src/types.ts
website/i18n/en.json
website/sidebars.json

Closes #191, #179.
Make sites faster.
```typescript
class ArticleResource extends Resource {
static partialUpdateShape<T extends typeof Resource>(
this: T,
): MutateShape<
SchemaDetail<Readonly<AbstractInstanceType<T>>>,
Readonly<object>,
Partial<AbstractInstanceType<T>>
> {
return {
...super.partialUpdateShape(),
options: {
...this.getFetchOptions(),
optimisticUpdate: (params: any, body: any) => ({
id: params.id,
...body,
}),
},
};
}
static createShape<T extends typeof Resource>(this: T) {
return {
...super.createShape(),
options: {
...this.getFetchOptions(),
optimisticUpdate: (
params: Readonly<object>,
body: Readonly<object | string> | void,
) => body,
},
};
}
}
const appendUpdater = (
newArticleID: string,
articleIDs: string[] | undefined,
) => [...(articleIDs || []), newArticleID]; …
```

feat: Add optimistic updates

---

__tests__/common.ts
packages/rest-hooks/src/react-integration/__tests__/integration.tsx
packages/rest-hooks/src/state/reducer.ts

Deletes often don't return anything, but our detection for this case falsy thought there was no optimistic
Check explicitly for undefined rather than falsy

fix: Optimistic updates now trigger for results with empty string

---

packages/rest-hooks/package.json
packages/rest-hooks/src/state/NetworkManager.ts
packages/rest-hooks/src/state/SubscriptionManager.ts

Fixes #129.
Lodash is bloated and fairly outdated. Modern applications should exploit modern browser features or core-js polyfills.
Last usage of memoize is replaced by simple constructor creation

enhance: Remove lodash dependency, reducing total bundle size

---

packages/normalizr/src/index.d.ts
packages/normalizr/src/index.js
packages/rest-hooks/src/resource/SimpleRecord.ts
packages/rest-hooks/src/state/selectors/__tests__/__snapshots__/useDenormalized.ts.snap
packages/rest-hooks/src/state/selectors/__tests__/useDenormalized.ts
packages/rest-hooks/src/state/selectors/useDenormalized.ts

Fixes #249 .
- Performance
- Hooks world expects this - like useEffect, etc
- Track all entities captured in denormalize
- Serialize them
- Use that serialization as memo check for results
How does this affect performance overall? Could this be degrading non-list cases?

enhance: Keep referential equality in list views

---

packages/normalizr/package.json
packages/normalizr/rollup.config.js
website/i18n/en.json

Pointing to minified version breaks bundleaphobia (see more https://github.com/pastelsky/bundlephobia/issues/246)
Separate es builds so browser target can be latest while still targeting min/non-min for es.

fix: ES export is non-min version

---

packages/rest-hooks/src/resource/SimpleResource.ts
packages/rest-hooks/src/resource/types.ts

Fixes #209 .
Constraining acceptable params is an incredibly valuable feature; but arbitrarily defining what should be expected was previously cumbersome.
```typescript
type MyParamType = {
slug: string,
};
class MyThing extends Resource {
//...
static detailShape<T extends typeof SimpleResource>(
this: T,
) {
const shape = super.detailShape();
return shape as SetShapeParams<typeof shape, MyParamType>;
}
}
```
```tsx
// fine
const mything = useResource(MyThing.detailShape(), { slug: 'hi' });
// expected number
const mything = useResource(MyThing.detailShape(), { slug: 5 });
// somethingelse not found in type
const mything = useResource(MyThing.detailShape(), { somethingelse: 5 });
// slug expected to be here
const mything = useResource(MyThing.detailShape(), { });
```

feat: Add SetShapeParams

---

packages/rest-hooks/src/resource/SimpleResource.ts
packages/rest-hooks/src/resource/paramsToString.native.ts
packages/rest-hooks/src/resource/paramsToString.ts

Fixes #260 .
React native throw not implemented error for URLSearchParams.sort().
Use [.native.js](https://facebook.github.io/react-native/docs/platform-specific-code) extension to make a version of the module with platform specific code

fix: listUrl() on react native no longer throws error

---

packages/rest-hooks/rollup.config.js
packages/rest-hooks/src/resource/paramsToString.native.ts

Often metro bundler for react-native will use the common js version - so lets ensure it's maximum compatibility.
Read .native.ts extensions first for module resolution in CJS bundling

enhance: Commonjs bundle uses native-compatible code

---

__tests__/common.ts
packages/rest-hooks/src/react-integration/__tests__/subscriptions.tsx
packages/rest-hooks/src/react-integration/hooks/useSubscription.ts
packages/rest-hooks/src/state/SubscriptionManager.ts
packages/rest-hooks/src/state/__tests__/subscriptionManager.ts
packages/rest-hooks/src/types.ts

- This allows custom FetchShapes to include options that a custom Middleware can hook into. useSubscription was previously only pulling `pollFrequency` from options. This now includes all options in meta object.
- subscribe/unsubscribe actions now include all FetchOptions, rather than just frequency (BREAKING)
- Add 'extra' member to FetchOptions

feat: Include all FetchOptions in subscribe action

---

__tests__/common.ts
docs/guides/binary-fetches.md
packages/rest-hooks/src/react-integration/__tests__/useResource.tsx
packages/rest-hooks/src/resource/types.ts
packages/rest-hooks/src/state/selectors/buildInferredResults.ts
website/i18n/en.json
website/sidebars.json

Fixes #266.
With Rest Hooks already useful for JSON type data, it should allow for other response types like images, ArrayBuffers, etc.
Sample FetchShape:
```typescript
export const photoShape = {
type: 'read' as const,
schema: null as ArrayBuffer | null,
getFetchKey({ userId }: { userId: string }) {
return `/users/${userId}/photo`;
},
fetch: async ({ userId }: { userId: string }) => {
const response = await fetch(`/users/${userId}/photo`);
const photoArrayBuffer = await response.arrayBuffer();
return photoArrayBuffer;
},
};
```
Usage:
```tsx
const photo = useResource(photoShape, { userId });
```
useResource() ensures a response, but we're still stuck with the | null union. This is needed however to have sane defaults. Currently the only distinction is based on entities, which this cannot …

feat: Support non JSON (aka binary) fetches

---

packages/rest-hooks/src/react-integration/__tests__/integration.tsx
packages/test/src/index.ts
packages/test/src/makeRenderRestHook.tsx
packages/test/src/managers.ts

Less spam about needing to wrap in act()

fix: Poll fetches while testing should be wrapped in act

---

packages/rest-hooks/rollup.config.js
packages/rest-hooks/src/index.ts
packages/rest-hooks/src/react-integration/provider/ExternalCacheProvider.tsx
packages/rest-hooks/src/react-integration/provider/PromiseifyMiddleware.ts
packages/rest-hooks/src/react-integration/provider/index.ts
packages/use-enhanced-reducer/rollup.config.js
packages/use-enhanced-reducer/src/index.ts
packages/use-enhanced-reducer/src/types.ts
packages/use-enhanced-reducer/src/useEnhancedReducer.ts
packages/use-enhanced-reducer/src/usePromisifiedDispatch.ts
website/i18n/en.json

Had some weird edge cases in testing
- Inline use-enhanced-reducer into rest-hooks
- Target legacy for cjs bundle in use-enhanced-reducer
- Move PromiseifyMiddleware back into rest-hooks since it's only useful for externalcacheprovider

fix: Fix commonjs bundle

---

packages/rest-hooks/src/react-integration/__tests__/hooks.tsx
packages/rest-hooks/src/resource/SimpleRecord.ts
packages/rest-hooks/src/types.ts

SimpleRecord._unq is a tracker used in toString() to make referential comparisoins easier (#251 ).
Exposing this is problematic as it pollutes the structural definition of any classes inheriting from SimpleRecord. This might have been done previously due to limitations of parsing declare lines - but this seems to work now.
Removing the type declaration altogether is necessary to avoid its pollution of type compatibility
https://www.typescriptlang.org/docs/handbook/type-compatibility.html#private-and-protected-members-in-classes
Technically this is a breaking change, but it increases compatibility rather than restricts it, so it likely won't cause issues.

fix: type SimpleRecord._unq should be private

---

packages/normalizr/src/index.d.ts
packages/rest-hooks/src/state/reducer.ts
packages/rest-hooks/src/types.ts

Redux state should never be modified

internal: readonly should exist on all levels of internal state

---

packages/rest-hooks/src/state/selectors/__tests__/buildInferredResults.ts
packages/rest-hooks/src/state/selectors/buildInferredResults.ts

In case absolutely no entities of the requested type have been stored before, the index table for that particular entity will not be set. This means useCache() on index values can sometimes throw if their data isn't loaded.
Simple check addition to the if statement in buildInferredResults.

fix: useCache() with indexes but no entities ever stored

---

docs/guides/infinite-scrolling-pagination.md
website/blog/2019-10-28-Rest-Hooks-2.2-Released.md
website/i18n/en.json
website/sidebars.json
website/versioned_docs/version-3.0/guides/infinite-scrolling-pagination.md
website/versioned_sidebars/version-3.0-sidebars.json
website/versioned_sidebars/version-4.0-sidebars.json
website/versioned_sidebars/version-4.1-sidebars.json
website/versioned_sidebars/version-4.3-sidebars.json
website/versioned_sidebars/version-4.5-sidebars.json

Fixes #128
Infinite scrolling pagination is a common pattern, and is not immediately obvious how to implement.
Outline an example with a representative theoretical API.
This adds the docs to all versions since 3.0 (even tho this feature was added in 2.2 - specifying extra primitive args was not supported at the time).
Should we bother recommending UI libs for the other half?

docs: Add example for infinite scrolling pagination

---

__tests__/common.ts
docs/api/Entity.md
packages/rest-hooks/src/state/selectors/__tests__/useDenormalized.ts
packages/rest-hooks/src/state/selectors/useDenormalized.ts
website/versioned_docs/version-4.2/api/Entity.md
website/versioned_docs/version-4.3/api/Entity.md

Using indexes often means results will never appear and thus never update. buildInferredResults() thus needs to run based on new index changes.
Sidenote: This would have been caught with exhaustive-deps, but the plugin had to be disabled to make the params && getFetchKey() serialization work.
Add state.indexes to useMemo() dependency list.

fix: Index updates should possibly rerender

---

packages/rest-hooks/src/state/PollingSubscription.ts

React Native doesn't have addEventListener. Furthermore, it has it's own way of detecting online/offline. 
For now we'll just not activate offline/online detection when addEventListener isn't available.
- How can we cleanly add online/offline detection for RN
- We should figure out how to run the tests in a React Native environment so things like this never happen again.

fix: Don't throw when RN tries to poll

---

packages/normalizr/src/index.d.ts
website/i18n/en.json

Fixes #286 .
https://resthooks.io/docs/guides/binary-fetches we recommend null schema, which in JS-land enables getting the results right. However, the typescript types don't match.
Just add null to the Schema |

fix: Schema can be null (for media)

---

packages/rest-hooks/src/react-integration/__tests__/integration.tsx
packages/rest-hooks/src/react-integration/__tests__/useError.tsx
packages/rest-hooks/src/react-integration/hooks/useError.ts
packages/rest-hooks/src/state/NetworkManager.ts
packages/rest-hooks/src/state/__tests__/networkManager.ts

Fixes #300  .
Even though the state does not update, React will warn about the reducer running from render (triggered from useRetrieve()). Although React should short-circuit and not actually re-render, it doesn't harm for us to short-circuit even earlier - after all it will run less code!
Intercept all fetch dispatches in the NetworkManager that cannot cause state updates. (No optimistic response)

fix: Do not run reducer on non-optimistic fetches

---

packages/legacy/src/__tests__/useStatefulResource.tsx
packages/legacy/src/index.ts
packages/rest-hooks/src/react-integration/__tests__/useCache.tsx
packages/rest-hooks/src/react-integration/__tests__/useResource.tsx
packages/rest-hooks/src/react-integration/hooks/useCache.ts
packages/rest-hooks/src/react-integration/hooks/useExpiresAt.ts
packages/rest-hooks/src/react-integration/hooks/useRetrieve.ts
packages/rest-hooks/src/react-integration/hooks/useSubscription.ts
packages/rest-hooks/src/state/selectors/useDenormalized.ts

BREAKING CHANGE: When invalidIfStale is true, useCache() and
useStatefulResource() will no longer return entities, even if they
are in the cache
`invalidIfStale` was added, and its behavior affected suspense, which is the primary mechanism to use data. However, as other use cases expanded it became clear that equivalent behavior should be reflected in the other hooks. This is especially important when not using suspense at all - for instance when `useStatefulResource()`.
This only changes behavior when invalidIfStale is true.
In this case, we should consider the same case where useResource() would suspend and return 'empty' results. This is key for replicating the same behaviors and patterns with both `useCache()` and `useStatefulResource()`.

enhance: useCache() and useStatefulResource() respect invalidIfStale

---

packages/rest-hooks/src/state/DefaultConnectionListener.ts
packages/rest-hooks/src/state/PollingSubscription.ts

Smaller bundle size, less paths to test.
Also make a clear BrowserConnectionListener so split is only done once.

enhance: Simplify online/offline polling logic

---

packages/rest-hooks/src/react-integration/hooks/useFetcher.ts
packages/rest-hooks/src/react-integration/hooks/useResource.ts
packages/rest-hooks/src/react-integration/hooks/useRetrieve.ts

Previously it was just 'any', which is often not very helpful.
We'll grab from the fetch function as that's the simplest approach and most accurate.

enhance: Infer returntype of useFetcher()'s functions

---

packages/rest-hooks/src/resource/shapes.ts

- Using the exported shapes from Rest Hooks, such as ReadShape, is really helpful and simplifies the process of creating custom shapes. However, if you want to have a more strongly typed return value of your FetchShape fetch function you'll run into type conflicts and will have to create override to make work.
- Keep the same defaults each shape previously had, but allow fourth optional generic for fetch response
```
static detailShape<T extends typeof SimpleResource>(this: T): DetailShape<T, {}, { data: User }> {
const shape = (super.detailShape() as any) as DetailShape<T, {}, { data: User | null }>
return {
...shape,
fetch: async params => {
// data is typed correctly as User | null
const { data } = await shape.fetch(params);
if (!data) {
throw new Error()
}
// Now return value will be …
```

enhance: Add optional generic for FetchShape['fetch'] response

---

packages/normalizr/src/index.d.ts

BREAKING CHANGE: TypeScript 3.7 or higher is required. This uses type
recursion.
Previously, we used interfaces to specify recursive type algorithms as a workaround for the greedy nature of `type` in TypeScript < 3.7. This resulted in things like `ArrayDenorm<>` showing as return values, which is somewhat confusing.
Drop support for TypeScript 3.7 and implement recursive type definition.

enhance: More readable array return types

---

packages/rest-hooks/src/index.ts
packages/rest-hooks/src/react-integration/__tests__/__snapshots__/hooks.tsx.snap
packages/rest-hooks/src/react-integration/__tests__/__snapshots__/useResource.tsx.snap
packages/rest-hooks/src/react-integration/hooks/useFetcher.ts
packages/rest-hooks/src/state/__tests__/networkManager.ts
packages/rest-hooks/src/state/__tests__/reducer.ts
packages/rest-hooks/src/state/actions/createFetch.ts
packages/rest-hooks/src/types.ts

Also export actionTypes with each action string
BREAKING CHANGE: Added promise to FetchAction['meta']
This will make creating actions for various other middlewares easier. Other action creators to come.
```ts
dispatch(createFetch(
fetchShape,
params,
body,
throttle,
updateParams,
));
```
Should probably try to solidify the interface a bit since this is being exposed.

feat: Add createFetch() action creator

---

packages/rest-hooks/src/react-integration/__tests__/useResource.tsx
packages/rest-hooks/src/state/selectors/__tests__/useDenormalized.ts
packages/rest-hooks/src/state/selectors/useDenormalized.ts

Better support simple response endpoints.
With no entities, denormalization is pointless. However, what's worse is since it found all the entities it needed (since it didn't need any) - it will attempt to infer results. Inferring results is non-nonsensical with no entities as it would just be returning the schema.
Add simple schemaHasEntity() algorithm to determine whether a schema has entities. When it doesn't we short-circuit the de-normalization computation.

enhance: Schemas with no entities should not infer

---

packages/rest-hooks/src/state/__tests__/reducer.ts
packages/rest-hooks/src/state/reducer.ts
packages/rest-hooks/src/types.ts

BREAKING CHANGE: Mutation fetches now result in:
- meta entries
- results entries
Previously fetch keys were simply urls (pre 1.0), so a distinction was needed between mutate and read types. However, for some time now these have serialized to their own unique value. This is the first stage for heavily simplifying the codepaths.
This means mutates now result in new entries in the state: meta, results. This is likely valuable in some cases.
Future path to unify deletes as well?

enhance: State updates from mutate/read now the same

---

packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/normalize.ts

Allow for multiple methods of choosing value to send to pk when normalizing

fix: Allow for multiple pk methods

---

packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/entities/FlatEntity.ts
packages/normalizr/src/entities/SimpleRecord.ts
packages/normalizr/src/entities/__tests__/SimpleRecord.test.ts

Plain objects assume the value is there. SimpleRecords allow for defaults to be provided. There are times when we want to use these on things that aren't entities (with proto3).
Add normalize/denormalize that just pulls on 'object' version.
```ts
const schema = {
cards: [] as LoyaltyCard[],
pageDescription: new PageDescription(),
cardLocation: LoyaltyCardLocation.HOME_CAROUSEL,
}
```
to
```ts
class ListLoyaltyCards extends SimpleRecord {
readonly cards: LoyaltyCard[] = [];
readonly pageDescription = new PageDescription();
readonly cardLocation = LoyaltyCardLocation.HOME_CAROUSEL;
}
const schema = ListLoyaltyCards.asSchema();
```

feat: Allow SimpleRecords to be schemas

---

.eslintrc
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/entities/__tests__/Entity.test.ts
packages/normalizr/src/entities/__tests__/__snapshots__/Entity.test.ts.snap
packages/normalizr/src/schemas/__tests__/Object.test.js
packages/normalizr/src/schemas/__tests__/Values.test.js
packages/normalizr/src/schemas/__tests__/__snapshots__/Object.test.js.snap

Missing some parameters in responses is quite normal - both for CSF as well as cases where there are partial responses returned.
- filters out undefined and null pk in production rather than throwing error (this matches previous normalizr behavior)
- Improve message to make it easier to debug malformed by outputting missing, found, and unexpected keys.
- Don't care about missing pieces for triggering error
- Primarily focus on unexpected values - however only trigger if there are many keys defined to allow for usage without predefining keys.

enhance: Improve malformed entity normalization algorithm

---

docs/api/Entity.md
docs/api/Resource.md
docs/guides/nested-response.md
packages/core/src/react-integration/__tests__/hooks.tsx
packages/normalizr/src/entities/SimpleRecord.ts
packages/normalizr/src/schema.d.ts
packages/normalizr/src/schemas/__tests__/Array.test.js
packages/rest-hooks/src/resource/__tests__/__snapshots__/resource.ts.snap
packages/rest-hooks/src/resource/__tests__/resource.ts

asSchema() is deprecated, let's not references it anymore

docs: Get rid of all references to asSchema()

---

docs/api/Entity.md
packages/normalizr/src/entities/SimpleRecord.ts
packages/normalizr/src/entities/__tests__/Entity.test.ts
packages/normalizr/src/schema.d.ts
packages/normalizr/typescript-tests/entity.ts
packages/normalizr/typescript-tests/relationships.ts

'first', 'second' isn't clear on how the variables are used. Better names helps users understand how they are called, for instance in normalizing:
```ts
entities[schemaKey][id] = schema.merge(existingEntity, processedEntity);
```
(existing, incoming) implies the procedural nature, without suggesting too much about temporality - which would be dangerous as race conditions cause no guarantees for proper ordering.

enhance: Rename merge variables to (existing, incoming)

---

packages/normalizr/src/normalize.ts
packages/normalizr/src/schemas/__tests__/Array.test.js
packages/normalizr/src/schemas/__tests__/__snapshots__/Array.test.js.snap

Fixes #341  .
If an api returns json, but doesn't set content-type, the default fetch function in Resource will not json parse. This might be surprising for some - so give some clear messaging around this case.

enhance: Better dev error messaging with unexpected string to normalize

---

__tests__/common.ts
packages/core/src/react-integration/__tests__/useCache.tsx
packages/core/src/react-integration/__tests__/useResource.tsx
packages/core/src/state/selectors/__tests__/useDenormalized.ts
packages/core/src/state/selectors/useDenormalized.ts

Support schemas with no entities properly - even complex objects like { nextPage: '', array: [] }
We need to ensure we are still throwing a promise when there is no entry in the results table. This is in addition to already not inferring results.
To do this we will return `cacheResults !== undefined` for the second useDenormalized() return value. This means it is 'ready' vs previous expressed allEntitiesFound. The latter wasn't correct since it was simply passed into hasUsableData()
Types for useCache() will be wrong, since we return undefined when it isn't available. We somehow need to detect schemas that have no entities for this to work.

fix: No entity schemas should suspend when they have no results

---

__tests__/common.ts
packages/core/src/react-integration/__tests__/__snapshots__/integration.tsx.snap
packages/core/src/react-integration/__tests__/integration.tsx
packages/core/src/state/selectors/__tests__/buildInferredResults.ts
packages/core/src/state/selectors/buildInferredResults.ts
packages/core/src/state/selectors/useDenormalized.ts

Tests for SimpleRecord had been added for normalize/denormalize - however there are some custom schema integrations in rest hooks core itself.
Updated to work with new cases - also ensured solution was general to match the general pattern rather than special casing SimpleRecord:
- schemaHasEntity
- buildInferredResults
Added test for buildInferredResults as well as an integration test to cover entire useResource() pipeline.

fix: SimpleRecord as schema in useDenormalized()

---

docs/api/Entity.md
docs/api/SimpleRecord.md
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/entities/SimpleRecord.ts
packages/normalizr/src/entities/__tests__/Entity.test.ts
packages/normalizr/src/entities/__tests__/SimpleRecord.test.ts
packages/normalizr/src/entities/__tests__/__snapshots__/Entity.test.ts.snap

A way to express nested members that aren't required.
For both Entity, and SimpleRecord:
- for all members of `static schema`, if default is set, and that default is falsy - field is considered optional
- optional fields don't need to be 'found'
- fromJS() works with Records sent

feat: SimpleRecord can have optional entities by setting default to null

---

packages/core/src/react-integration/__tests__/__snapshots__/integration.web.tsx.snap
packages/core/src/react-integration/__tests__/integration.web.tsx
packages/core/src/state/NetworkManager.ts
packages/core/src/state/actions/createReceiveError.ts
packages/core/src/state/reducer.ts

- Catching errors earlier is helpful when building and understanding network endpoints.
- Also pretty key that normalize gets what it needs, or denormalize won't be able to get the correct results.
- We actually need to ensure we don't throw in the reducer or the provider will unmount.
We *must* handling the error in the reducer, or React gets confused about state updates (we don't want to redispatch in middle of a render). Therefore, we catch processing receives (where normalizr should be able to throw errors) and process those as network errors (setting the meta error). To ensure invariants with usage in functions, we check for this condition in NetworkManager so it can reject the promise.
We should probably get rid of other error handling routes in NetworkManager for simplicity - since …

fix: Normalizr errors reject and throw in useResource()

---

packages/core/src/react-integration/hooks/useExpiresAt.ts
packages/core/src/react-integration/provider/__tests__/__snapshots__/provider.tsx.snap
packages/core/src/state/__tests__/__snapshots__/reducer.ts.snap
packages/core/src/state/reducer.ts
packages/core/src/types.ts

To simulate non-caching, we set invalidIfStale to true in addition to a lower dataExpiryTime. Since suspense remounts components, if there are more than one requests like this in one suspense boundary the component might not remount until one or many of the requests have already become stale again.
This is a temporary solution since in the future we will be simply making useInvalidator trigger any shape.

fix: Protect against invalidIfStale with || request

---

__tests__/common.ts
packages/core/src/react-integration/__tests__/useResource.web.tsx
packages/normalizr/src/__tests__/__snapshots__/index.test.js.snap
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/denormalize.ts
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/entities/__tests__/SimpleRecord.test.ts
packages/normalizr/src/entities/__tests__/__snapshots__/SimpleRecord.test.ts.snap
packages/normalizr/src/normalize.ts
packages/normalizr/src/schema.d.ts
packages/normalizr/src/schemas/__tests__/Serializable.test.ts
packages/normalizr/src/schemas/__tests__/__snapshots__/Serializable.test.ts.snap
packages/normalizr/src/types.ts

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse Reviver arg in JSON.parse. This has the limitation of only having local context (immediate key and value), rather than full recursive context.
There are many types that would be much easier to operate on. Having to do this programmatically in fromJS() can not only be quite annoying and error-prone, but this limits the abilities to things inside Entities. If a simple, predictable pattern could be introduced to make this declarative, it would greatly enhance the utility of Rest Hooks.
This desire has both been expressed by the custody team, as well as RN project.
The first premise is that we want to use the 'schema' to declare transforms. This means schema will now be used to serialize/deserialize in …

feat: Declarative schema deserialization

---

__tests__/common.ts
docs/api/Resource.md
docs/guides/auth.md
docs/guides/custom-networking.md
docs/guides/network-transform.md
packages/core/src/types.ts
packages/rest-hooks/src/index.ts
packages/rest-hooks/src/resource/Resource.ts
packages/rest-hooks/src/resource/SimpleResource.ts
packages/rest-hooks/src/resource/__tests__/resource.ts

This allows using hooks in Resource.getFetchInit(), to
make context-based authentication easy.
- Removed Resource.fetchOptionsPlugin()
- Added Resource.getFetchInit() which is called in shape generators
- Resourece.fetch() interface changed to match browser fetch()
Fixes #273 .
- This allows using hooks in Resource.getFetchInit(), to make context-based authentication easy.
- More standardized interface
- Allows for body payloads that aren't just JSON.
- Removed Resource.fetchOptionsPlugin()
- Added Resource.getFetchInit() which is called in shape generators
- Changed Resource.fetch() to `static fetch(input: RequestInfo, init: RequestInit): Promise<any>`
```typescript
class AuthdResource extends Resource {
static getFetchInit = (init: RequestInit) => {
const { session } = …
```

feat: Resource.fetch() arguments reflect browser fetch()

---

docs/guides/extending-endpoints.md
docs/guides/network-errors.md

Fixes #287 .
We talk about declarative (read) api errors, but never imperative (mutate) errors.

docs: Add imperative (mutate) error handling example)

---

docs/api/DevToolsManager.md
docs/api/Manager.md
packages/core/src/react-integration/provider/CacheProvider.tsx
packages/core/src/types.ts
packages/rest-hooks/src/manager/DevToolsManager.ts
packages/rest-hooks/src/manager/index.ts
packages/rest-hooks/src/react-integration/provider/index.ts
website/i18n/en.json
website/sidebars.json

Easier for developers to know how information is flowing.
Integration with https://github.com/zalmoxisus/redux-devtools-extension via a new manager. Note this does not
allow for time-travel debugging as unclear how to make this work with react lifecycle. Using ExternalCacheProvider and manual integration still allows for this.
What about React Native? The tool suggests lookup of window, so not sure how this would be possible.
Inspired by @0xcaff

feat: Add DevToolsManager to integrate with redux-devtools

---

packages/test/src/MockProvider.tsx

The previous error MockProvider message when it received an un-mocked dispatch was unhelpful.
It tells you what action is received.

Print the action in mockDispatch, so users know what they need to mock.

---

packages/legacy/src/index.ts

Throwing an error from Resource fetcher is not caught by useStatefulResource. This fix suppresses the uncaught error but still returns it correctly.
Define .catch on maybePromise, if it exists.

[bugfix] useStatefulResource: catch maybePromise errors

---

packages/core/src/react-integration/__tests__/integration.web.tsx
packages/core/src/react-integration/__tests__/useCache.tsx
packages/core/src/react-integration/hooks/useCache.ts

useCache() was returning any type in many cases.
Explicit about return type so there are less levels of inferrencing.

fix: Inferred return of useCache()

---

packages/rest-hooks/src/react-integration/provider/index.ts

Even though DevToolsManager is split based on dev mode internally, it's still hooked up. This short circuits that whole operation.
unshift to plugins list only if NODE_ENV !== 'production'

enhance: Only include DevToolsManager in dev mode

---

__tests__/common.ts
packages/core/src/react-integration/__tests__/__snapshots__/integration.web.tsx.snap
packages/core/src/react-integration/__tests__/integration.web.tsx
packages/core/src/react-integration/hooks/useError.ts
packages/core/src/state/actions/createFetch.ts
packages/core/src/state/reducer.ts
packages/normalizr/src/normalize.ts
packages/rest/src/SimpleResource.ts

In case any of the index fields of an entity are updated, the existing entry should be removed.
To ensure overwriting existing values - use DELETED symbol.

fix: Handle entities updated with new indexes

---

docs/guides/extending-endpoints.md
docs/guides/network-transform.md
docs/guides/pagination.md
packages/core/src/react-integration/__tests__/__snapshots__/hooks.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/useResource.web.tsx.snap
packages/endpoint/src/__tests__/endpoint.ts
packages/endpoint/src/endpoint.d.ts
packages/endpoint/src/endpoint.js
packages/rest/src/SimpleResource.ts
packages/rest/src/__tests__/resource.ts

Dramatically simplifies repeated patterns like those in Resource. Now custom endpoints are more easily customized like so:
With a base like so:
```typescript
protected static endpoint() {
const init = this.getFetchInit({ method: 'GET' });
const instanceFetch = this.fetch.bind(this);
const url = this.url.bind(this);
return new Endpoint(
function (params: Readonly<object>) {
return instanceFetch(this.url(params), this.init);
},
{
...this.getEndpointExtra(),
key: function (this: any, params: Readonly<object>) {
return `${this.init.method} ${this.url(params)}`;
},
url,
init,
},
);
}
```
Now this adds extensibility holes to the endpoint itself. Allowing easy customization of both init as well as url, making defining the CRUD methods very straightforward.
```typescript
static update<T extends …
```

feat: Support extra endpoint members and inheritance

---

__tests__/new.ts
packages/rest/src/SimpleResource.ts
packages/rest/src/__tests__/__snapshots__/resource-endpoint.ts.snap
packages/rest/src/__tests__/resource-endpoint.ts

Aside from === benefits, endpoints have become somewhat more expensive. These are refereed to many times in each render, so let's try to make this as fast as possible.
Attach to class.

enhance: Memoize Resource endpoints

---

__tests__/new.ts
docs/api/Resource.md
docs/guides/auth.md
docs/guides/extending-endpoints.md
packages/core/src/react-integration/__tests__/__snapshots__/hooks-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/hooks.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/useResource-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/useResource.web.tsx.snap
packages/core/src/react-integration/__tests__/useResource-endpoint.web.tsx
packages/rest/src/SimpleResource.ts

Authentication with context requires running some code each time endpoints are called. Do we need to construct the full endpoints then?
Still memoize endpoints, but provide `runInit()` member that is run everytime the endpoint method is called. Collapsing this into the memoization function also makes the definitions more terse. Also make customizing methods easier, with a method member for endpoints.
Newly added:
- runInit()
- method
Also make memo method a protected member so it can be used to memoize other extensions.
Useful for #273
```typescript
export const AuthContext = createContext('');
export class ContextAuthdArticle extends ArticleResource {
/** Init options for fetch */
static getFetchInit(init: RequestInit): RequestInit {
/* eslint-disable-next-line */
const accessToken = …
```

enhance: Simplify endpoint memoization and provide new extensions

---

packages/endpoint/src/index.ts

Fixes #395.
.js file tries exporting AbstractInstanceType - which only exists in type-world.
Use export type

fix: Only export AbstractInstanceType in type-world

---

packages/endpoint/src/index.ts

Fixes #399
Schema is included in .js built in endpoint because it comes from normalizr and compiler doesn't know to remove it. This causes an error in javascript.
export Schema marked as `type` so it is not included in js file

fix: Export type correctly in endpoint

---

docs/guides/abort.md

Abort controller hooked directly to a fetch function can potentially cause race conditions if that fetch is deduped across the app. For now our use case this won't happen so releasing this is still quite useful, but we should warn others if they desire aborting requests sent by many components at once.
1. Many disjoint components useResource() with same parameters, requesting fetch at the same time
1. NetworkManager dedupes, making only one request in flight
1. One component decides it wants to abort that request - but the others are still interested.
1. The fetch is aborted, even though other components still want results
1. Other components will suspend forever.

docs: Add warning about abort usage

---

package.json
packages/normalizr/src/entities/__tests__/Entity.test.ts
packages/rest-hooks/src/resource/SimpleResource.ts
packages/rest/src/SimpleResource.ts
yarn.lock

TypeScript 4 doesn't allow overriding getters
Do getter in JS only

fix: TypeScript 4 compatibility

---

packages/core/src/index.ts
packages/core/src/react-integration/__tests__/__snapshots__/useFetchDispatcher.tsx.snap
packages/core/src/react-integration/__tests__/useFetchDispatcher.tsx
packages/core/src/react-integration/hooks/index.ts
packages/core/src/react-integration/hooks/useFetchDispatcher.ts
packages/core/src/react-integration/hooks/useFetcher.ts
packages/core/src/react-integration/hooks/useRetrieve.ts

Fetching unknown number of items? Never fear, this lets you use one hook with many different fetches!
We'll be using this for our fetch-as-render SSR + concurrent mode routing architecture.
This hook is always mounted.
```ts
import { dispatchFetch } from 'rest-hooks';
import { useLocale } from 'i18n';
function useRouteContext() {
const locale = useLocale();
const dispatchFetch = useFetchDispatcher();
return { locale, dispatchFetch };
}
```
Each of these routes resolveData will be run on navigation even stack.
```ts
const routes = [
{
path: '/home',
modulePath: 'Home',
resolveData: ({ dispatchFetch, locale }) => {
return dispatchFetch(
AssetResource.listShape(),
{
locale: locale?.currency,
localeCode: locale?.localeCode
}
);
},
},
{
path: '/careers/:position-id',
modulePath: 'Careers', …
```

feat: useFetchDispatcher()

---

packages/core/src/react-integration/__tests__/__snapshots__/useResource.web.tsx.snap
packages/core/src/react-integration/__tests__/useResource.web.tsx
packages/core/src/react-integration/hooks/useError.ts
packages/core/src/react-integration/hooks/useResource.ts
packages/core/src/state/actions/createReceiveError.ts
packages/core/src/state/reducer.ts
packages/test/src/mockState.ts

Fixes #408 .
In https://github.com/coinbase/rest-hooks/pull/360 we solve an infinite loop problem when the network response was invalid. This required detecting and throwing errors before suspending so it doesn't just keep suspending infinitely.
However, this means that any genuine network errors will now prevent suspending for new content.
For the one case of response value, we'll mark the error as `synthetic`. Only `synthetic` errors throw before considering suspense.
Also, Fixtures (used in various testing pieces) now support faking errors, by sending error: true.

fix: Only block suspense if errors are synthetic

---

packages/core/src/index.ts
packages/core/src/react-integration/hooks/index.ts
packages/core/src/react-integration/hooks/useInvalidateDispatcher.ts
packages/core/src/react-integration/hooks/useInvalidator.ts

Moving in a similar direction to https://github.com/coinbase/rest-hooks/pull/407. This enables variable and disjointed invalidation.

feat: Add useInvalidateDispatcher()

---

packages/core/src/state/NetworkManager.ts
packages/core/src/state/__tests__/networkManager.ts

In React Native, when the app is closed, the react tree unmounts. However, the JS runtime still persists. Because of this, module defined NetworkManagers will not be reset, but will have clean called.
Additionally, this race condition also exists with RESETs
Clean should also prepare NetworkManager to be still used.

fix: Clear promises on cleanup

---

docs/api/Array.md
docs/api/Values.md

The example shows overly complex function version, when in these simple cases a string usage is better.
- Make docs easier to navigate by using standard header levels.
- Add string schemaAttribute example

docs: More examples for Array and Values

---

__tests__/new.ts
docs/api/types.md
docs/guides/rest-types.md
packages/endpoint/src/types.ts
packages/rest/src/index.ts
packages/rest/src/types.ts
website/i18n/en.json
website/sidebars.json
website/versioned_docs/version-4.5/guides/rest-types.md
website/versioned_sidebars/version-4.5-sidebars.json

Fixes #423 .
Explicitly typing return values is encouraged by common eslint rules and helps TypeScript performance as well as reducing recursion limit hit rate. Let's make it both as easy as possible to do, and clearly explain how to do it.
- We are adding a new convenience type `RestEndpoint` as well as `RestFetch` to make explicit endpoint return types for Resource easier
- Adding thorough documentation about typing Resource endpoints

feat: Add RestEndpoint type

---

yarn.lock

`path.isStaticBlock is not a function` when building
Must be some old version so forced all babel to latest

fix: Latest babel to fix build

---

packages/test/src/FixtureManager.ts
packages/test/src/index.ts
packages/test/src/mockState.ts

Fixes #415.
In many cases, mocking network itself is inconvenient - which is why MockProvider was created. However, it is incredibly limited in its capability as it cannot handle any updates, thus cannot model imperative pieces.
We wish to have an easy, but universal solution to mocking with fixtures.
FixtureManager is initialized with fixtures it can handle and automatically dispatches receives in the normal manner when it receives a 'fetch' dispatch.
If it does not find a matching fixture for a given request, it will pass through to other managers. To fallback to normal behavior, simply include those other managers.
`fixtures.ts`
```typescript
export default {
full: [
{
request: ArticleResource.list(),
params: { maxResults: 10 },
result: [
{
id: 5,
content: 'have a merry christmas', …
```

feat: Add FixtureManager to improve testing imperative fetch

---

packages/core/src/react-integration/provider/__tests__/__snapshots__/provider.tsx.snap
packages/core/src/state/__tests__/__snapshots__/reducer.ts.snap
packages/core/src/state/__tests__/reducer.ts
packages/core/src/state/merge/mergeDeepCopy.ts
packages/core/src/state/reducer.ts
packages/core/src/types.ts

Tracking entity specific resolution time helps improve entity freshness in cases where custom data-specific merging tracking is not provided. There are several cases that will shortly be using the improved tracking of data age at an entity level:
- stale-while-revalidation staleness guarantees when inferring results
- resolving fully normalized persistence caches (@0xcaff )
Add entityMeta as top level `state` member. This tracks the same shape as entities, but with the data of { date: number }.
```typescript
entityMeta: {
readonly [entityKey: string]: {
readonly [pk: string]: { readonly date: number };
};
};
```
This affects merges by potentially changing the order of arguments sent to [SimpleRecord.merge()](https://resthooks.io/docs/next/api/SimpleRecord#static-merget-extends-typeof-simpl …

feat: Track and use entity resolution time

---

packages/core/src/index.ts

When extracting the request type from a fetch shape, `get` and `mutate` requests have the requests in either Params or Body of the fetch shape. `ParamsFromShape` was exposed from the package, but `BodyFromShape` wasn't, necessitating the method be copied into the codebase directly until it is exposed.
One line change to export `BodyFromShape` from `packages/core`.
What is the appropriate way to update the version of the package?

Expose BodyFromShape from core library

---

packages/test/src/FixtureManager.ts

The fetch comes down the render pass in children components, so the parent was already rendered at that point. We need to schedule another render call async or React complains.
Settimeout with 0

fix: FixtureManager should dispatch receive async to not break react

---

docs/api/MockResolver.md
docs/guides/storybook.md
packages/test/src/MockResolver.tsx
packages/test/src/index.ts
website/i18n/en.json
website/sidebars.json

Fixes #415.
Mocking needs to work for imperative endpoints like `update`, not just `read` endpoints as requested in #415.
Initially a new manager was added in #440 (FixtureManager) to solve this problem. However, in practice this became cumbersome for three reasons:
- Full Provider, ErrorBoundary, and Suspense would need to be established in each story.
- Integration with a users' customer managers would need to be re-specified.
- Any changing of fixtures required resetting the entire Provider.
While the first two are only somewhat annoying, the third seemed like a pretty big deal breaker.
Use `dispatch interceptor pattern` via `<MockResolver fixtures={myMockData} />`. 
Since all fetches using rest hooks require an established context, we can bind a new context to intercept dispatches …

feat: Add <MockResolver />

---

packages/rest-hooks/src/manager/DevtoolsManager.ts

Dev env checks result in different builds. Current policy is to always test full dev mode.
Add instanbul ignore lines

internal: Ignore dev env only paths for code coverage

---

docs/guides/pagination.md

I had trouble finding my own docs page :P

docs: Link to infinite scrolling guide from pagination

---

docs/guides/loading-state.md
website/versioned_docs/version-4.0/guides/loading-state.md

Fixes #454 .
Turns out using useLoadingFunction() as described didn't update the function
Add to arg list

docs: Fix bug in useLoadingFunction() function

---

lerna.json

To avoid committing directly to master, we need to have a release process that only pushes branches.
New release process:
1) `git checkout -b release`
2) `lerna version` (this will commit to the current branch and push tags, etc, but not publish)
3) open PR on github for version branch & land PR
4) publish: `yarn clean && yarn build && lerna publish from-git`
Due to this, we are adding the options to lerna version in the config.
Automate step 4

internal: Add lerna options to  cmd

---

packages/core/CHANGELOG.md
packages/core/package.json
packages/endpoint/CHANGELOG.md
packages/endpoint/package.json
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/legacy/CHANGELOG.md
packages/legacy/package.json
packages/normalizr/CHANGELOG.md
packages/normalizr/package.json
packages/rest-hooks/CHANGELOG.md
packages/rest-hooks/package.json
packages/rest/CHANGELOG.md
packages/rest/package.json
packages/test/CHANGELOG.md
packages/test/package.json

- @rest-hooks/core@1.0.0-k.5
- @rest-hooks/endpoint@0.7.3
- @rest-hooks/hooks@0.1.2
- @rest-hooks/legacy@2.0.0-k.2
- @rest-hooks/normalizr@6.0.0-k.0
- rest-hooks@5.0.0-k.5
- @rest-hooks/rest@0.5.1
- @rest-hooks/test@2.0.0-k.2

internal: publish versions

---

lerna.json
packages/core/src/react-integration/hooks/useResource.ts

`%s` only works when all packages match versions

internal: Fix publish message

---

packages/core/package.json
packages/core/src/index.ts
packages/core/src/react-integration/context.ts
packages/core/src/react-integration/hooks/useCache.ts
packages/core/src/react-integration/hooks/useResource.ts
packages/core/src/react-integration/provider/CacheProvider.tsx
packages/core/src/state/selectors/__tests__/useDenormalized.ts
packages/core/src/state/selectors/useDenormalized.ts
packages/normalizr/package.json
packages/normalizr/src/WeakListMap.ts
packages/normalizr/src/__tests__/WeakListMap.test.ts
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/denormalize.ts
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/entities/FlatEntity.ts
packages/normalizr/src/entities/__tests__/Entity.test.ts
packages/normalizr/src/index.ts
packages/normalizr/src/schema.d.ts
packages/normalizr/src/schemas/__tests__/Array.test.js
packages/normalizr/src/schemas/__tests__/Delete.test.ts
packages/normalizr/src/schemas/__tests__/Object.test.js
packages/normalizr/src/schemas/__tests__/Serializable.test.ts
packages/normalizr/src/schemas/__tests__/Union.test.js
packages/normalizr/src/schemas/__tests__/Values.test.js
packages/normalizr/src/types.ts
packages/rest-hooks/package.json

To make SSR easy, the cache itself should be easily serializable/deserializable. Currently the cache stores instances of Entities, which means any deserialization construct would have to deal with knowing how to load the Entity classes. While this may be achievable, this amount of complexity while maintaining codesplitting seems undesirable.
Since the flat entities are stored as results of fromJS() (normalized form) - they simply contain ids to their nested counterparts. This makes the typing somewhat odd, but more importantly means that denormalizing them on the fly violates referential equality expectations of any entity. In the past this hasn’t been a huge deal because we mostly don’t use nested entities in retail.
Referential guarantees are currently provided by a useDenormalized() …

enhance: Maintain referential equality globally

---

__tests__/utils.ts
packages/core/src/react-integration/__tests__/useExpiresAt.tsx
packages/core/src/react-integration/__tests__/useResource-endpoint.web.tsx
packages/core/src/react-integration/__tests__/useResource.web.tsx
packages/core/src/react-integration/hooks/index.ts
packages/core/src/react-integration/hooks/useCache.ts
packages/core/src/react-integration/hooks/useExpiresAt.ts
packages/core/src/react-integration/hooks/useResource.ts
packages/core/src/react-integration/hooks/useRetrieve.ts
packages/core/src/react-integration/provider/__tests__/__snapshots__/provider.tsx.snap
packages/core/src/state/__tests__/__snapshots__/reducer.ts.snap
packages/core/src/state/__tests__/reducer.ts
packages/core/src/state/reducer.ts
packages/core/src/state/selectors/__tests__/useDenormalized.ts
packages/core/src/state/selectors/useDenormalized.ts
packages/core/src/types.ts
packages/legacy/package.json
packages/legacy/src/index.ts
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/denormalize.ts
packages/normalizr/src/entities/__tests__/Entity.test.ts
packages/normalizr/src/schemas/__tests__/Array.test.js
packages/normalizr/src/schemas/__tests__/Delete.test.ts
packages/normalizr/src/schemas/__tests__/Object.test.js
packages/normalizr/src/schemas/__tests__/Serializable.test.ts
packages/normalizr/src/schemas/__tests__/Union.test.js
packages/normalizr/src/schemas/__tests__/Values.test.js

In other words: don't extraneously refetch fresh data.
BREAKING CHANGE: useResource() inferred endpoint will sometimes
not trigger a fetch if entities are fresh enough
Fixes #460 .
Also requested by: @melissafzhang @dgcoffman 
Continuation of: #439
Allows liberal use of useResource()
- When a detail (inferrable) useResouce() is in a nested component of a list result, will not trigger `N` fetches
- Any other case where manual useCache() tracking was used.
- Previously inferred results were set to expiry time of 0, which meant they would try to fetch if they could
- Now this is computed based on the 'oldest' (or soonest to expire) entity of those used.
- If any entities are missing, the full result was not inferred and thus expiry is 0.
- Also went back to previous denormalize() design …

enhance: Inferred endpoints expiry based on entities

---

packages/core/CHANGELOG.md
packages/core/package.json
packages/endpoint/CHANGELOG.md
packages/endpoint/package.json
packages/legacy/CHANGELOG.md
packages/legacy/package.json
packages/normalizr/CHANGELOG.md
packages/normalizr/package.json
packages/rest-hooks/CHANGELOG.md
packages/rest-hooks/package.json

- @rest-hooks/core@1.0.0-rc.0
- @rest-hooks/endpoint@0.7.4
- @rest-hooks/legacy@2.0.0-rc.0
- @rest-hooks/normalizr@6.0.0-rc.0
- rest-hooks@5.0.0-rc.0
`yarn lerna version --no-push --preid=rc`

internal: publish 5 rc.0

---

packages/rest/src/SimpleResource.ts

This makes return values really verbose
Focus on best practices of Resource fields marking as readonly

enhance: Remove Readonly on Resource endpoint schemas

---

packages/core/src/react-integration/__tests__/__snapshots__/integration-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/integration.web.tsx.snap
packages/core/src/state/selectors/__tests__/useDenormalized.ts
packages/rest/src/SimpleResource.ts

(Resource extends from Entity instead of FlatEntity)
BREAKING CHANGE: Resources will resolve with any nested
entities from their schemas, rather than the `pk` of those
entities
With referential equality guarantees (#403), fully denormalizing Resources with nested members now makes sense
and is performant.
Using `rest-hooks` package retains the old `Resource` and `SimpleResource` behavior. The new adoption and recommended
method of defining Resources is via `@rest-hooks/rest` package. Eventually the `rest-hooks` version will be removed.

feat: Resources can have nested entities

---

packages/core/src/endpoint/shapes.ts
packages/core/src/endpoint/types.ts
packages/core/src/index.ts
packages/core/src/react-integration/hooks/useError.ts
packages/core/src/react-integration/hooks/useFetchDispatcher.ts
packages/core/src/react-integration/hooks/useFetcher.ts
packages/core/src/react-integration/hooks/useInvalidateDispatcher.ts
packages/core/src/react-integration/hooks/useInvalidator.ts
packages/core/src/react-integration/hooks/useSubscription.ts
packages/core/src/state/actions/createFetch.ts
packages/core/src/state/actions/createReceive.ts
packages/core/src/state/actions/createReceiveError.ts
packages/core/src/state/applyUpdatersToResults.ts
packages/core/src/state/selectors/buildInferredResults.ts
packages/core/src/state/selectors/getEntityPath.ts
packages/core/src/state/selectors/useDenormalized.ts
packages/core/src/types.ts
packages/endpoint/src/index.ts

BREAKING CHANGE: Remove `normalize`, `denormalize`; use
`normalizr` package for those
The goal of endpoints package is to allow people to publish endpoints independent of all implementation details.
Previously, we distinguished this by ignoring the react implementation, however the processing elements like `normalizr` and `denormalize` could change independent of interfaces. For instance, this just happened. However, if we can keep the interfaces non-breaking changes for many years, this means people can use their existing network definitions without worry for a very long time.
- Only export the definitions themselves.
- Also change imports in core so normalizr is only used for processing utilities.
Should we perhaps split normalizr package in two so we aren't importing normalizr and only …

enhance: `endpoint` package only exports definitions

---

package.json
yarn.lock

https://github.com/conventional-changelog/commitlint/blob/master/CHANGELOG.md drops node <10 and lerna <3. Added engine in root package (not published but used for dev) that we need node 10.

internal: Bump commitlint

---

package.json
yarn.lock

Better organized, easier to read release messages
- updated packages
- tested here via `yarn lerna version --no-push --no-git-tag-version`
* Remove `normalize`, `denormalize`; use
`normalizr` package for those
* Resources will resolve with any nested
entities from their schemas, rather than the `pk` of those
entities
* Resources can have nested entities ([#469](https://github.com/coinbase/rest-hooks/issues/469)) ([4eeeaae](https://github.com/coinbase/rest-hooks/commit/4eeeaae1026715be4e72a66cd94d81934f2b0ce7))
* `endpoint` package only exports definitions ([#473](https://github.com/coinbase/rest-hooks/issues/473)) ([51dcafe](https://github.com/coinbase/rest-hooks/commit/51dcafe98631998a1db1959f2796d7122d96960b))

internal: Use custom template for release gen

---

.github/workflows/commitlint.yml
package.json

Currently we lint on commit, which is a fairly large amount of friction for contributions. What we really need is to simply enforce conventions for a PR merge.
Adding this GH action. If this works well, will remove the per-commit enforcement

internal: Use github action to enforce commitlint

---

docs/getting-started/installation.md
docs/guides/legacy-browser.md
website/i18n/en.json
website/sidebars.json

High friction due to complex instructions.
- Both hard to follow
- Hard to understand when needed
- Makes the install page look long and complex
- Move instructions to distinct page
- Update instructions to use better tooling

docs: Improve legacy browser instructions

---

__tests__/new.ts
docs/guides/rest-types.md
packages/core/src/react-integration/__tests__/endpoint-types.web.tsx
packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx
packages/core/src/react-integration/hooks/useFetchDispatcher.ts
packages/core/src/react-integration/hooks/useFetcher.ts
packages/rest/src/SimpleResource.ts
packages/rest/src/types.ts

Ensure override Resource patterns work in all cases.
- RestFetch params: object -> any
- object no longer widens, so overrides break with `{ id: number }` or the like (even though this matches, due to the directionality)
- useFetcher matches 'any' properly
Also:
- updated tests & docs with all known cases to ensure our recommendations work

enhance: Widen RestFetch types to make overriding not break

---

docs/guides/resource-lifetime.md

This is just a `typo fix` in `docs/guides/resource-lifetime.md` doc file.

docs: Fix typo

---

README.md
docs/guides/network-transform.md
docs/guides/rest-types.md
packages/core/README.md
packages/rest-hooks/README.md
website/versioned_docs/version-5.0.0/guides/network-transform.md
website/versioned_docs/version-5.0.0/guides/rest-types.md

- More links in readmes
- Add details around `super` typescript limitations to rest-type docs
- Add design note in 'network tranform' section

docs: Improve rest-types and network transform

---

packages/core/src/state/selectors/useDenormalized.ts
packages/normalizr/src/denormalize.ts

Named tuples were introduced in TypeScript 4. They are nice, but TypeScript doesn't have a backwards compatibility compiler, so we cannot use features in exported types that are supported.
Removed named tuple usage in denormalize, useDenormalized. There are still some internal usages but those don't get exported.

fix: Support TypeScript <4

---

packages/legacy/src/__tests__/fixtures.ts
packages/legacy/src/__tests__/useStatefulResource.tsx

https://github.com/airbytehq/airbyte/pull/1736#discussion_r561338401 mentioned that in previous versions of rest-hooks/legacy (`useStatefulResource()`) the loading prop was sometimes incorrect.
Add a new test for when `useStatefulResource()` params change.

internal: Add test for useStatefulResource() param changes

---

packages/normalizr/src/entities/SimpleRecord.ts
packages/rest-hooks/src/resource/SimpleResource.ts
packages/rest-hooks/src/resource/__tests__/resource.ts
packages/rest/src/__tests__/resource-endpoint.ts

Integration into VS code came after these were deprecated. This should give nice indications in IDEs that support.

enhance: Add jsdocs deprecations to deprecated methods

---

packages/test/src/MockResolver.tsx

Subscriptions cause fetches - which means components using subscriptions that are mocked will still cause a normal fetch
Since fixtures currently don't support any time-series based changes, simply blocked the mocked subscription dispatches will produce desired results.

fix: MockResolver intercepts subscriptions matching fixtures

---

packages/rest-hooks/src/manager/PollingSubscription.ts
packages/rest-hooks/src/manager/SubscriptionManager.ts
packages/rest-hooks/src/manager/__tests__/__snapshots__/pollingSubscription-endpoint.ts.snap
packages/rest-hooks/src/manager/__tests__/pollingSubscription-endpoint.ts
packages/rest-hooks/src/manager/__tests__/pollingSubscription.ts

Navigating always prompts a fetch when there is a subscription - effectively ignoring TTL policies.
Hold off first polling fetch til after data is stale.

fix: Wait til data is stale for first poll

---

packages/core/src/react-integration/__tests__/__snapshots__/integration-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/integration.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/useResource-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/useResource.web.tsx.snap
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/entities/__tests__/Entity.test.ts
packages/normalizr/src/entities/__tests__/__snapshots__/Entity.test.ts.snap

Fixes #492 .
As good as heuristics might be, until we allow full validation control, this could get annoying sometimes.
Add [Entity](https://resthooks.io/docs/api/Entity) member:
`protected declare static automaticValidation?: 'warn' | 'silent';`
Can throw errors
Will only ever warn in console
Does not do any validation beyond normal PK/nested entities, etc.
> Note: None of this validation occurs in production builds

enhance: Add `static automaticValidation` to Entity

---

packages/test/package.json
yarn.lock

3.6 accidentally introduced a breaking change. More here: https://github.com/testing-library/react-hooks-testing-library/issues/554
Disallow major versions beyond 3.5.

fix: Disallow breaking 3.6 version of @testing-library/react-hooks

---

docs/guides/extending-endpoints.md
website/versioned_docs/version-5.0/guides/extending-endpoints.md

In custom endpoints docs, the code example is wrong:
```js
export default class CommentResource extends Resource {
static detail<T extends typeof Resource>(this: T) {
return super.detail.extend({
schema: { data: this },
});
}
```
Updated **.detail** to **.detail()**
```js
export default class CommentResource extends Resource {
static detail<T extends typeof Resource>(this: T) {
return super.detail().extend({
schema: { data: this },
});
}
```

Fixed code example of extending detail endpoint

---

packages/rest/src/SimpleResource.ts

We widened our params in https://github.com/coinbase/rest-hooks/pull/479 but missed delete because it has a special override

fix: Widen Resource.delete() just like other endpoints

---

packages/rest/package.json

Allow matching of v1. Noticed this when using npm instead of yarn and it tried to resolve with v0.6. Realized v1 is breaking from 0.x
Add a union for peerDep of endpoint.

enhance: Expand matches peerdeps for endpoint

---

docs/getting-started/installation.md
website/versioned_docs/version-5.0/getting-started/installation.md

Current docs does not mention that you need to install `@rest-hooks/rest` to use the library.

docs: Added @rest-hooks/rest package to installation guide

---

packages/endpoint/src/endpoint.js

[CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) disallows calling Function(), which means in some scenarios the Endpoint class would not work.
Using `Object.setPrototypeOf(self, new.target.prototype);` we can still make instances inherit from Function without using `this` and thus, being forced to call `super()`, which is disallowed.
This does mean we cannot use class assignments, so moved those to constructor. This should work on children though.
A benefit of this method is we no longer have the hacky eval-like string.
This won't work in IE, so we need a detection mechanism to use the old method

fix: Ensure Endpoint doesn't trigger CSP

---

docs/api/makeRenderRestHook.md
docs/guides/custom-networking.md
docs/guides/redux.md
docs/guides/unit-testing-hooks.md
package.json
packages/core/src/react-integration/__tests__/__snapshots__/integration-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/integration.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/subscriptions-endpoint.tsx.snap
packages/core/src/react-integration/__tests__/endpoint-types.web.tsx
packages/core/src/react-integration/__tests__/hooks-endpoint.web.tsx
packages/core/src/react-integration/__tests__/hooks.web.tsx
packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx
packages/core/src/react-integration/__tests__/integration.web.tsx
packages/core/src/react-integration/__tests__/subscriptions-endpoint.tsx
packages/core/src/react-integration/__tests__/subscriptions.tsx
packages/core/src/react-integration/__tests__/useCache-endpoint.tsx
packages/core/src/react-integration/__tests__/useCache.tsx
packages/core/src/react-integration/__tests__/useError-endpoint.tsx
packages/core/src/react-integration/__tests__/useError.tsx
packages/core/src/react-integration/__tests__/useExpiresAt.tsx
packages/core/src/react-integration/__tests__/useResource-endpoint.web.tsx
packages/core/src/react-integration/__tests__/useResource.web.tsx
packages/core/src/react-integration/provider/__tests__/provider.tsx
packages/legacy/src/__tests__/useStatefulResource.tsx
packages/test/package.json
packages/test/src/makeRenderRestHook.tsx
packages/test/src/providers.tsx
packages/use-enhanced-reducer/src/__tests__/middleware.tsx
website/versioned_docs/version-5.0/guides/redux.md
yarn.lock

- result.current, result.error is now `undefined` after suspense, rather than `null`
-  interval will now default to 50ms in async utils
-  timeout will now default to 1000ms in async utils
-  suppressErrors has been removed from async utils
- Adjust types so that react renderer exports don't required extra generic parameter
- Importing from renderHook and act from @testing-library/react-hooks will now auto-detect which renderer to used based on the project's dependencies
- peerDependencies are now optional to support different dependencies being required
- This means there will be no warning if the dependency is not installed at all, but it will still warn if an incompatible version is installed
- Auto-detection won't work with bundlers (e.g. Webpack). Please use as …

pkg: react-hooks-testing-library major

---

docs/api/MockProvider.md
packages/test/README.md
website/versioned_docs/version-5.0/api/MockProvider.md

- Forgot to escape `<`
- Test example: Suspense never occurs when using a fixture

docs: Typo fix + better test example

---

packages/core/package.json
packages/endpoint/package.json
packages/hooks/package.json
packages/normalizr/package.json
packages/rest-hooks/package.json
packages/rest/package.json
yarn.lock

Having multiple @babel/runtimes with nesting creates some interesting issues when building. 
After a more thorough investigation of https://github.com/babel/babel/pull/10853 I have realized that 7.12 is simply the requirement to work with webpack 5, but interop with babel/core will work. This is due to the new package exports directives - which are processed by webpack 5 only.
Thus, users of webpack 5, should ensure they run only babel 7.12+ and also hoist it to ensure a single version. Other users should not care.
To reduce the chance of non-hoisted runtimes, we relax our requirements to what 4.5.9 was. This should enable no new introduced of non-hoisted runtimes.

pkg: Relax @babel/runtime requirement to ^7.7.2

---

docs/guides/rest-types.md
website/versioned_docs/version-5.0/api/NetworkErrorBoundary.md
website/versioned_docs/version-5.0/api/makeRenderRestHook.md
website/versioned_docs/version-5.0/guides/custom-networking.md
website/versioned_docs/version-5.0/guides/rest-types.md
website/versioned_docs/version-5.0/guides/unit-testing-hooks.md

- Add small detail to NetworkErrorBoundary 
- Format some docs files
- Typo in rest-types
- Update v5 docs with some master updates that were missed

docs: Minor typos, update 5 docs with master changes

---

__tests__/legacy.ts
packages/core/src/react-integration/__tests__/__snapshots__/useResource-legacy.web.tsx.snap
packages/core/src/react-integration/__tests__/useResource-legacy.web.tsx
packages/rest-hooks/src/resource/SimpleResource.ts

Since `Resource`s in 'rest-hooks' package (vs `@rest-hooks/rest`) are only for legacy, ease upgrade path.
It's still very unlikely to cause problems, but this should make things absolutely easy.
`warn` still so people are aware, but if they were using it before it's likely working correctly.
In the case of building new Resources off 'rest-hooks' import, it won't bring as many benefits; but more important to get everyone on 5 smoothly.

enhance: legacy Resource should only warn on validation problems

---

packages/test/package.json
packages/test/rollup.config.js
packages/test/tsconfig.json

Only having commonjs works fine when importing in node context. However, things like MockResolver are meant to be used with storybook which builds via webpack. This creates two problems
- testing library ends up being pulled in, which isn't build for webpack
- optional redux import only works with actual cjs as bundlers don't run the exception
By providing an es6 module version, webpack will pick this up and skip over the modules that are not used - namely the ones that depend on optional redux or testing library
There used to be an issue where having non cjs version of test caused loading of both cjs and es6 versions of rest hooks context. I believe this was due to bundling as I could not find a "module" entry since 'test' split into its own package.

fix: Gracefully handle webpack builds

---

package.json
packages/core/package.json
packages/legacy/package.json
packages/rest-hooks/package.json

Eliminate need for version bumps on release in each package
Hoisting removes the entry in each package.json per package

internal(pkg): Hoist @rest-hooks/test inclusion

---

docs/api/makeRenderRestHook.md
docs/api/mockInitialState.md
docs/guides/storybook.md
docs/guides/unit-testing-components.md
docs/guides/unit-testing-hooks.md
website/i18n/en.json
website/versioned_docs/version-5.0/api/makeRenderRestHook.md
website/versioned_docs/version-5.0/api/mockInitialState.md
website/versioned_docs/version-5.0/getting-started/installation.md
website/versioned_docs/version-5.0/guides/storybook.md
website/versioned_docs/version-5.0/guides/unit-testing-components.md
website/versioned_docs/version-5.0/guides/unit-testing-hooks.md

- MockResolver instead of MockProvider everywhere
- Update `Fixture` interface everywhere
- Update unit testing components example

docs: Update testing guides with latest best practices

---

packages/rest-hooks/src/resource/Resource.ts
packages/rest-hooks/src/resource/__tests__/resource.ts
packages/rest/src/Resource.ts
packages/rest/src/__tests__/resource-endpoint.ts

Fixes #550  .
For certain payloads this obviously isn't the correct header.
- No body, or string body - set default 'Content-Type' header to 'application/json'
- User's init will always override this, which can be specified in many places
- Only for those using `Resource`

fix: Support non-JSON payloads (like FormData)

---

docs/api/types.md
docs/api/useError.md
docs/api/useMeta.md
packages/core/src/index.ts
packages/core/src/react-integration/hooks/index.ts
packages/core/src/react-integration/hooks/useError.ts
packages/core/src/react-integration/hooks/useResource.ts
packages/core/src/types.ts
packages/legacy/package.json
packages/rest-hooks/src/index.ts
packages/rest-hooks/src/react-integration/NetworkErrorBoundary.tsx
packages/rest-hooks/src/react-integration/index.ts
website/versioned_docs/version-5.0/api/types.md
website/versioned_docs/version-5.0/api/useError.md
website/versioned_docs/version-5.0/api/useMeta.md

For those using built in fetch, we can be assured the error might show up as NetworkError. If we expose this in a union at the very least they can test for it
- Establish central NetworkError definition
- Spread through all error code
- Update docs
Maybe we should have a way of allowing users to customize what their error types are?

enhance: Improve error type preciseness

---

.github/dependabot.yml

`dependencies` is in standard list for new repos

internal: Change dependabot label to more standard

---

docs/api/types.md
packages/rest/src/SimpleResource.ts
packages/rest/src/types.ts
website/versioned_docs/version-5.0/api/types.md

- Reduce complexity of return types based on inference
- This makes the types more readable to user
- Also can help typescript performance - reducing chance of triggering recursion depth limit (I have theory that https://github.com/coinbase/rest-hooks/issues/569 was caused by this)
- Shows example in code of how to explicitly type return values of endpoints
Add `this` definition to `RestFetch`

enhance: Explicitly defined Resource endpoint return types

---

packages/core/CHANGELOG.md
packages/core/package.json
packages/legacy/CHANGELOG.md
packages/legacy/package.json
packages/rest-hooks/CHANGELOG.md
packages/rest-hooks/package.json
packages/rest/CHANGELOG.md
packages/rest/package.json

- @rest-hooks/core: 1.0.3 => 1.0.4
- @rest-hooks/legacy: 2.0.1 => 2.0.2
- rest-hooks: 5.0.5 => 5.0.6
- @rest-hooks/rest: 1.0.3 => 1.0.4

internal: publish

---

docs/api/types.md
docs/api/useError.md
docs/api/useMeta.md
packages/core/src/react-integration/hooks/useError.ts
packages/core/src/react-integration/hooks/useResource.ts
packages/core/src/types.ts
packages/legacy/package.json
website/versioned_docs/version-5.0/api/types.md
website/versioned_docs/version-5.0/api/useError.md
website/versioned_docs/version-5.0/api/useMeta.md

https://github.com/coinbase/rest-hooks/pull/571 improved some of the types, but it made type discrimination harder
By keeping key members - but making them unknown in the case of types we don't control (things thrown by users - since there's no type enforcement there) - this allows us to check those members to discriminate.

enhance: Make type discrimination easier in error types

---

__tests__/new.ts
packages/core/src/endpoint/shapes.ts
packages/core/src/endpoint/types.ts
packages/core/src/react-integration/__tests__/useResource-endpoint.web.tsx
packages/core/src/state/actions/createFetch.ts
packages/core/src/state/actions/createReceive.ts
packages/core/src/state/actions/createReceiveError.ts
packages/core/src/state/selectors/useDenormalized.ts
packages/core/src/types.ts
packages/endpoint/src/types.ts
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/denormalize.ts
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/normalize.ts
packages/rest-hooks/src/manager/PollingSubscription.ts
packages/rest-hooks/src/manager/SubscriptionManager.ts

`undefined` is a sensible symbol to demonstrate lack of processing.
This is the canonical way to represent Endpoint schema's that should just 'pass through' the input. However, for backwards compatibility, we have have been setting schema to `null` if it is undefined.
Fully realizing support to undefined schemas is the first step to properly supported non-backcompat endpoints.
I chose not to convert the hooks FetchShapes as that stage of conversion will occur when they accept Endpoints instead of FetchShapes. Instead, all non-FetchShape places with schema are marked as Schema | undefined.
There are many places where we want to only process *actual* schemas. It seems like a better naming convention to defined those as `Schema` and other places with the union. Furthermore, most places where …

enhance: Support 'undefined' as schema

---

packages/legacy/rollup.config.js

unpkg name should be specific to package
Rollup update. eslint rules also applied here

fix: Rollup name for @rest-hooks/legacy

---

packages/endpoint/src/endpoint.js
packages/normalizr/src/__tests__/__snapshots__/index.test.js.snap
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/denormalize.ts
packages/rest-hooks/src/manager/DevtoolsManager.ts

- We absolutely cannot push things into WeakMap that are not 'object'.
- In dev mode, have useful error message (this indicates something is wrong with response, as entities are only supposed to objects (including arrays))
- In prod, simply ignore all primitives (this won't break anything - as we don't need any primitives to ensure cache consistency)

fix: Gracefully handle primitive entity responses

---

packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/entities/__tests__/Entity.test.ts
packages/normalizr/src/entities/__tests__/__snapshots__/Entity.test.ts.snap

`static schema` keys should map to members of the entity - otherwise they do nothing.
During development - throw an error in case a schema is missing in response. This should help users with any typos or if they don't understand how `static schema` should work.

enhance: Throw useful error when schema key is missing from Entity

---

packages/normalizr/package.json

This breaks tooling that tries to transpile node_modules as it tries to looking for ` @anansi/browserslist-config` and cannot find it
Previously, the build configuration for normalizr was separate, but this has changed so it will use the config from the root level package which is not published.

fix: Exclude browserslist config from published package

---

packages/rest-hooks/src/index.ts
packages/rest-hooks/src/manager/DevtoolsManager.ts
packages/rest-hooks/src/manager/index.ts

When a site has multiple stores, they end up all having the document.title as the name - making it hard to find which one ties to rest hooks.
Explicitly name the redux-devtools integration.
Note: we don't type other options as the redux devtools could change these independently and it is up to the user to use what is provided by that tool.

enhance: Provide name to devtools to make it easier to find

---

packages/rest-hooks/src/manager/DevtoolsManager.ts

- Understanding the internal store what really matters is what state is sent to the context.
- Interpreting `state.optimistic` is not very readable or useful. So no loss here
DevToolsManager: Apply the same optimistic updates algorithm CacheProvider does before reporting state

enhance: Report optimistic state to devtools

---

.github/dependabot.yml

Keep website yarn.lock up to date. Ensure we have an appropriate prefix even with security updates for /website dir

internal: Dependabot for /website

---

packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/denormalize.ts

`typeof null === 'object'`
However weakmap doesn't take null.
@ljharb correctly pointed out the correct conditional in https://github.com/coinbase/rest-hooks/pull/584/files but this was overlooked.
- Use correct weakmap check
- Add extensive testing for regressions

fix: Handle nulls when schema expects something

---

packages/core/src/index.ts
packages/core/src/react-integration/hooks/index.ts
packages/core/src/react-integration/hooks/useError.ts
packages/legacy/package.json
packages/legacy/src/__tests__/useStatefulResource.tsx
packages/legacy/src/index.ts

Fixes #607 .
- Being explicit in our return type gives us a bit more power to control the value.
- Give same powers as useResource() types
- Enforce acceptable parameters
- Infer nullability from null parameters
- Empower type discrimination on return values

fix: useStatefulResource() return type

---

packages/rest-hooks/src/manager/DevtoolsManager.ts

https://github.com/coinbase/rest-hooks/pull/603 we put the reporting on the wrong argument of send.
Fix argument order - state is second arg
Since this is an external interface with no published types, one wonders how we might introduce more types or tests to catch this. For now I'm not super worried tho.
Validated by modifying lib code in node_modules in an install

fix: Actually send optimistic updates to devtool

---

packages/core/src/state/RIC.d.ts
packages/core/src/state/RIC.js
packages/core/src/state/RIC.ts

`global` is not max compatibility - so avoid if reasonable
Don't want to infect a user's global ambient, so we split js and .d.ts to ensure we type internally without polluting scope.

enhance: Don't use global for rIC def

---

packages/rest-hooks/src/manager/index.ts

Causes a warning in compilers
Prefix with `type`

fix: DevToolsConfig is type export

---

docs/api/useLoading.md
docs/guides/loading-state.md
packages/hooks/README.md
packages/hooks/src/__tests__/useLoading.ts
packages/hooks/src/index.ts
packages/hooks/src/useLoading.ts
website/i18n/en.json
website/sidebars.json

Prefer to have consumable code, vs copy/pasting in docs: https://resthooks.io/docs/guides/loading-state#loading-buttons
Add to hooks package.
```tsx
import { useLoading } from '@rest-hooks/hooks';
function Button({ onClick, children, ...props }) {
const [clickHandler, loading] = useLoading(onClick);
return (
<button onClick={clickHandler} {...props}>
{loading ? 'Loading...' : children}
</button>
);
}
```

feat: Add useLoading() hook

---

jest.config.js
package.json
packages/test/package.json
packages/test/rollup.config.js
packages/test/src/MockProvider.tsx
packages/test/src/MockResolver.tsx
packages/test/src/browser.ts
packages/test/src/index.ts
packages/test/src/makeRenderRestHook.tsx
packages/test/tsconfig.compile.json
tsconfig-base.json
yarn.lock

Type module expects explicit file extensions when importing.
- Remap all internal imports to relative + add .js extension
- Use package prefix for imports like in other packages (i.e., `@rest-hooks/test`)

fix: Explicit extensions for ESM

---

docs/guides/redux.md
docs/upgrade/upgrading-to-5.md
website/i18n/en.json
website/versioned_docs/version-5.0/guides/redux.md
website/versioned_docs/version-5.0/upgrade/upgrading-to-5.md

Imports were incorrect.
docs issue from #638
- Add to upgrade guide
- Update import directions

docs(fix): Update imports for @rest-hooks/core

---

docs/guides/redux.md
packages/rest-hooks/src/index.ts
packages/rest-hooks/src/react-integration/provider/index.ts
packages/rest-hooks/src/react-integration/provider/mapMiddleware.ts
packages/test/src/providers.tsx
website/versioned_docs/version-5.0/guides/redux.md

Fixes #638 .
Managers should work no matter where rest hooks shows up in a redux tree.
Transform middleware to make getState() return the piece that is rest hooks.
Better name?

feat: Add mapMiddleware

---

packages/test/package.json

Export added in next version of rest hooks. https://github.com/coinbase/rest-hooks/pull/643 added the export, but also to test it we used in the testing lib.
Redux stuff will soon get its own package to make this make a little more sense.

feat: Rely on mapMiddleware for redux testing

---

packages/rest-hooks/src/resource/Resource.ts

In #552 we made sure to only set the header with the correct payloads. However, legacy Resource still will always JSON encode body even if FormData is sent.
Backport check from @rest-hooks/rest

fix: non-JSON payloads on legacy Resource

---

__tests__/new.ts
docs/guides/network-transform.md
docs/upgrade/upgrading-to-5.md
packages/rest-hooks/src/resource/SimpleResource.ts
packages/rest/src/SimpleResource.ts
website/versioned_docs/version-5.0/guides/network-transform.md
website/versioned_docs/version-5.0/upgrade/upgrading-to-5.md

Keeping the class types the same allows simple extensions without knowledge of SimpleResource, which would be another import:
```typescript
static detail<T extends typeof Resource>(this: T) {
return super.detail().extend({
schema: { data: this },
});
}
```
However, since getFetchInit() was added to legacy Resource this was violated - potentially breaking types.
Add default implementation to legacy SimpleResource.
Also removed generics on url() since it no longer uses the class type for its params.
Ensure all test types `extend typeof Resource` to ensure this use-case continues to work.

fix: typeof Resource === typeof SimpleResource

---

packages/endpoint/src/endpoint.d.ts

These annotations will help users realize they shouldn't be using these proprieties when they autocomplete in their IDE.
`/** @deprecated */`

enhance: Mark Endpoint's back-compat members as 'deprecated'

---

packages/endpoint/src/endpoint.d.ts

Fixes #569 .
'mutate' is not allowed in hooks like useResource(), useCache(). 'read' is strictly more permissive. 
This means ambiguous sideEffect types can lead to type matching errors on things that only allow 'read'.
Correctly infer union case of sideEffect to also have union of mutate type.

fix: When sideEffect type is not known, bias toward 'read'

---

__tests__/new.ts
packages/core/src/endpoint/types.ts
packages/core/src/react-integration/__tests__/endpoint-types.web.tsx
packages/core/src/react-integration/hooks/useFetcher.ts
packages/endpoint/src/endpoint.d.ts
packages/rest/src/SimpleResource.ts
packages/rest/src/index.ts
packages/rest/src/types.ts

Fixes #569
Our previous precise logic worked with typescript 3.7+, but only in strict mode
A user kindly shared: https://github.com/saaymeen/rest-hooks-shape-type-issue
Most problems are derived from the fact that undefined simply does not exist.
Simplify types a bit so it works in both 3.7, as well as strict mode off.
This also means we lose strictness to force body for mutate types. The body param is always optional. However, the new fetch dispatcher design will be able to solve this enforcement and still remain compatible.
It would be good to add testing strict = false to test suite. However, this predictably causes some `ts-expect-error` tests to fail, as they should. We'll either need to figure out how to simply disable ts-expect-error or segment the tests by which are valid in …

fix: Compatibility with TypeScript strict: false

---

packages/rest/src/SimpleResource.ts
packages/rest/src/__tests__/resource.ts

Descriptive aid in development
By throwing in key we have the context that it's an improperly defined Resource, so instructions for correction can be more specific.
Since this is a static definition problem we only provide it during development to improve runtime.

enhance: Throw error when urlRoot is not defined

---

.github/workflows/benchmark.yml

Cache action both saves and restores, so PRs are writing nothing to cache.
Use `restore-keys` to read the same cache without saving it for PRs

internal(fix): Only write to benchmark cache on master

---

packages/endpoint/src/__tests__/endpoint.ts
packages/endpoint/src/endpoint.d.ts

Fixes #569
Still missed a case in loose world.
`IfTypeScriptLooseNull` detects loose types we can apply specific typing in this case. This makes the types much more readable as we simply write normal types and then cover that case with what we want.
In this case, if we can't detect we want it to be 'read' since that's the looser type. There may be a more elegant way of representing this by types that naturally represent that relationship, while still being terse.
We also exhaustively test the non-loose world to be certain we don't cause regressions there.

fix: Endpoint 'type' in loose typescript mode

---

.github/workflows/benchmark.yml

"The workflow is not valid. .github/workflows/benchmark.yml (Line: 31, Col: 11): A sequence was not expected"
Stole expected syntax from https://github.com/actions/cache/search?q=restore-keys

internal(fix): Fix github action syntax for benchmark

---

packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx
packages/core/src/state/selectors/useDenormalized.ts
packages/normalizr/src/schemas/__tests__/Values.test.js
packages/normalizr/src/schemas/__tests__/__snapshots__/Values.test.js.snap

Fixes #722 .
`schemaHasEntity()` assumed schema.schema would always be pojo. This is not true for Polymorphic types.
Use `typeof nestedSchema === 'function'` to check if the nested schema is another schema, rather than pojo - and in this case, simply recurse.
Added tests to both normalizr (validating not a problem there), as well as full integration with `useResource()`. Added for union as well to be comprehensive.
This is tightly coupled to internal implementations of schemas, rather than public APIs. We should establish a pattern to allow extensibility and reduce breakages.

fix: schema.Values singleSchema denormalization

---

.github/workflows/benchmark.yml

Master is broken
This github action is confused. I believe now `external-data-json-path` is a last resort if the branch option doesn't work. However, if it does, I *think* it still stores information to do bench comparisons. Either case this at least makes master not explode.

internal(fix): Fix bench action

---

packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx
packages/core/src/react-integration/test-fixtures.ts
packages/core/src/state/selectors/__tests__/buildInferredResults.ts
packages/core/src/state/selectors/buildInferredResults.ts

Fixes https://github.com/coinbase/rest-hooks/issues/722#issuecomment-816741203
Values is like array but for mapping types. Thus we need to distinguish when it's truly empty vs we tried to infer.
Make `undefined` like Array in `buildInferredResults()`.
Updated test case to do full networking response for values case

fix: Inferring schema.Values()

---

packages/core/package.json
packages/normalizr/package.json

Build the new files, define them but missed them in the upload process

fix: Publish legacy type files

---

__tests__/legacy.ts
packages/core/src/endpoint/shapes.ts
packages/rest-hooks/src/index.ts
packages/rest/src/legacy.ts

Previously MutateShape definitions were used. We need to make sure those don't cause type errors when still used in overrides.
Flex additional arguments on DeleteShape type

fix: Relax DeleteShape def to be back-compat

---

.github/workflows/benchmark.yml

Benchmark is for normalizr only now, so don't expect changes otherwise.

internal: Only run benchmark when normalizr files change

---

package.json
packages/core/src/index.ts
packages/core/src/internal.ts
packages/core/src/state/RIC.d.ts
packages/rest-hooks/src/index.ts
packages/rest-hooks/src/internal.ts
tsconfig-base.json

The current structure resulted in the following typescript ambient declaration
```buildInferredResults: typeof import("@rest-hooks/core/lib/state/selectors/buildInferredResults").default;```
- Focusing on __INTERNAL__ as module rather than object
- Keep RIC as a module in output
Validated output generation no longer reaches into internal file structures

fix: Generate types that do not refer internally to other packages

---

packages/core/src/react-integration/hooks/useRetrieve.ts
packages/core/src/state/reducer.ts
packages/core/src/types.ts

A year and a half ago this hack was introduced to allow for measuring rest-hooks with 0 length cache policy for A/B performance testing. This was introduced to prevent infinite loop problems because the code was not as robust back then. Since then, suspense logic was reworked to allow suspending anywhere with useInvalidator, and deletes. The hack has not been needed for some time. However, it remained in place in case there were any dependencies on it.
- The mechanisms were never documented or exposed
- The Coinbase experiment has long since been removed
- I can't imagine any use of building something relying on this - other than to get the same mechanisms that will continue to work without it.
Delete hack

enhance: Remove extraneous outdated hack

---

packages/endpoint/package.json
packages/endpoint/tsconfig.compile.json
packages/hooks/package.json
packages/hooks/tsconfig.compile.json
packages/img/package.json
packages/img/tsconfig.compile.json
packages/legacy/package.json
packages/legacy/tsconfig.compile.json
packages/rest-hooks/package.json
packages/rest-hooks/tsconfig.compile.json
packages/rest/package.json
packages/rest/tsconfig.compile.json
packages/test/package.json
packages/test/tsconfig.compile.json
packages/use-enhanced-reducer/package.json
packages/use-enhanced-reducer/tsconfig.compile.json

Use use TypeScript >=3.8 import features like `import type`
Use `typesVersions` with `downlevel-dts` for all remaining packages.

enhance: Support TypeScript 3.7

---

packages/endpoint/package.json
packages/endpoint/src-legacy-types/endpoint.d.ts
packages/endpoint/src-legacy-types/types.d.ts
packages/endpoint/src/__tests__/endpoint.ts
packages/endpoint/src/endpoint.js

Using .bind() but still have endpoint capabilities - like calling .key() without needing to send params.
Exploit the already existing `.extend()` to do most of the heavy lifting.

feat: Endpoint.bind()

---

__tests__/new.ts
packages/core/src/react-integration/__tests__/useExpiresAt.tsx
packages/core/src/types.ts
packages/endpoint/src-legacy-types/endpoint.d.ts
packages/endpoint/src-legacy-types/types.d.ts
packages/endpoint/src/__tests__/endpoint.ts
packages/endpoint/src/endpoint.d.ts
packages/endpoint/src/endpoint.js
packages/endpoint/src/interface.ts
packages/endpoint/src/types.ts
packages/normalizr/src/entities/SimpleRecord.ts
packages/normalizr/src/schema.d.ts
packages/normalizr/src/types.ts
packages/rest/src/types.ts

- Default key takes `JSON.strigify` on full `...params`
- Previously we were only taking the first arg to 'ignore' the body param. However, this is only valid for mutation endpoints, which aren't usable in declarative cases like useResource() that rely on `key()` in that way.
- This will change the serialization in results list as it will include body. (only applies to standalone entities - not Resources)
This only changes endpoint definitions - rest hooks itself still need to change to support this (based on variadic types).

feat: Endpoint parameters can be of any length

---

packages/core/src/react-integration/hooks/useError.ts
packages/core/src/react-integration/hooks/useExpiresAt.ts
packages/core/src/react-integration/hooks/useInvalidateDispatcher.ts
packages/core/src/react-integration/hooks/useInvalidator.ts
packages/core/src/react-integration/hooks/useMeta.ts
packages/core/src/react-integration/hooks/useSubscription.ts

Consistency means less to read and more robustness
Use the strongly validated pattern from [useCache](https://resthooks.io/docs/api/useCache)

enhance: Make hook generics use consistent params

---

packages/core/src/react-integration/__tests__/__snapshots__/integration-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx
packages/normalizr/src/schemas/Polymorphic.js
packages/normalizr/src/schemas/__tests__/__snapshots__/Array.test.js.snap
packages/normalizr/src/schemas/__tests__/__snapshots__/Union.test.js.snap

Deletes have special behavior and should never trigger when something else is awry.

fix: Delete should only be triggered on finding DELETE symbol

---

docs/api/useLoading.md
packages/hooks/README.md
packages/hooks/src/__tests__/useLoading.ts
packages/hooks/src/useLoading.ts
website/versioned_docs/version-5.0/api/useLoading.md

More convenience
Adding as third arg makes it back-compat, while still allowing optional partial usage. Loading will almost always be used, but error less often.

feat: Add error state to useLoading()

---

.github/dependabot.yml

Dependabot needs to format commits correctly or CI breaks

internal: Dependabot tracking info for normalizr redux example

---

packages/normalizr/src/denormalize.ts
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/types.ts

Reduces interface dependency on denormalize from Entity by making Entity aware of interface requirements for denormalize.
Previously fromJS was called from denormalize when constructing entities, so the local cache could be set. This created a dependency not only on the particular construction method, but also the concept around mutability. Having denormalize mutate a seemingly immutable SimpleRecord is like giving it private access.
Instead, we flip the script, providing `setLocal()` callback that requires Entity implementers to call appropriately. Since copying and setting the localcache before is only required to prevent infinite loops in nesting, it seems like this knowledge is already somewhat coupled to the implementation. For instance, there is no need for FlatEntity to use this …

enhance: Remove dependency on fromJS() from denormalize

---

packages/normalizr/src/__tests__/__snapshots__/index.test.js.snap
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/normalize.ts
packages/normalizr/src/schemas/Delete.ts

BREAKING CHANGE: normalize arg addEntity is now addEntity(schema,
processed, id)
- minimize interfaces
- slight performance win
The only reason all props are sent are to call pk(), which already happens - so just pass that on instead.
This will only affect those who override the entity normalize method

enhance: Simplify normalize addEntity function

---

jest.config.js
packages/experimental/src/entity/Entity.ts
packages/experimental/src/entity/EntityRecord.ts
packages/experimental/src/entity/IDEntity.ts
packages/experimental/src/entity/ImmutableUtils.ts
packages/experimental/src/entity/__tests__/NewEntity.test.ts
packages/experimental/src/entity/__tests__/__snapshots__/NewEntity.test.ts.snap
packages/experimental/src/index.ts

- Simplifies serialization of normalized values
- Improve performance
We introduce these new designs into the experimental packages to flesh out before planning migration.
- Normalizes to pojos
- new: `static process()` (instead of fromJS())
- Does not include Record concepts
- This can be a performance benefit for those who aren't interested in the helper methods that track which members are defined
- merge & fromJS are both a lot faster. These operations are performance for every entity in a response.
- Implements the same interface as prior Entity to provide backcompat as well as utility
- Implementation has some overhead but much less than SimpleRecord
- For most this will be 100% backwards compatible as the only distinction is the normalize to pojo, which is uncommon to rely on

feat: New Entity that normalizes to pojos

---

packages/core/src/state/NetworkManager.ts
packages/core/src/state/__tests__/networkManager.ts

Dangling promises are not a problem as they are cleaned by the GC when they lose references. All references to the promises should be within the tree of CacheProvider - therefore cleanup should remove all promise references.
Remove rejection CleanupError and simply delete everything.

enhance: Do not throw on unmount of CacheProvider

---

packages/rest-hooks/src/resource/Resource.ts
packages/rest-hooks/src/resource/SimpleResource.ts

To ease migration didn't want to spam editors with deprecation markers til a minor release.
We call this a 'feature' to trigger minor bump.
Use `@rest-hooks/rest` instead!

feat: Deprecate Resource in main 'rest-hooks' package

---

__tests__/new.ts
packages/core/src/state/__tests__/reducer.ts
packages/core/src/state/actions/createReceive.ts
packages/core/src/state/reducer.ts
packages/core/src/types.ts
packages/experimental/src/__tests__/useFetcher.ts
packages/experimental/src/createFetch.ts
packages/experimental/src/types.ts
packages/experimental/src/useFetcher.ts

Iterating toward https://github.com/coinbase/rest-hooks/issues/760
- Define programmable update in endpoint
- Improve function signature
We maintain working on raw reducer state, however we introduce improvements on the update method itself being much more straightforward and easy to define correctly.
- two degree function
- map key -> update function
```typescript
const createUser = new Endpoint(postToUserFunction, {
schema: User,
update: (newUser: Denormalize<S>)  => {
const updates = {
[userList.key()]: (users = []) => [newUser, ...users],
[userList.key({ sortBy: 'createdAt' })]: (users = [], { sortBy }) => {
const ret = [createdUser, ...users];
ret.sortBy(sortBy);
return ret;
},
];
if (newUser.isAdmin) {
updates[userList.key({ admin: true })] = (users = []) => [newUser, ...users];
} …
```

feat: Endpoint.update programmable sideeffects

---

packages/core/src/react-integration/__tests__/__snapshots__/hooks-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/hooks.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/useFetchDispatcher.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/useResource-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/useResource.web.tsx.snap
packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx
packages/core/src/react-integration/hooks/useFetchDispatcher.ts
packages/core/src/react-integration/hooks/useFetcher.ts
packages/core/src/state/__tests__/networkManager.ts
packages/core/src/state/__tests__/reducer.ts
packages/core/src/state/actions/createFetch.ts
packages/core/src/state/actions/createReceive.ts
packages/core/src/state/reducer.ts
packages/core/src/types.ts
packages/experimental/README.md
packages/experimental/src/createFetch.ts
website/siteConfig.js

No reason to wait for new fetch for new update method since it's optional
Add relevant arguments to action

enhance: Support endpoint.update in existing useFetcher

---

packages/core/src/react-integration/__tests__/__snapshots__/hooks-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/hooks.web.tsx.snap
packages/core/src/state/__tests__/networkManager.ts
packages/core/src/state/actions/createFetch.ts

As promised in https://github.com/coinbase/rest-hooks/pull/843 - as part of legacy plan we will only send update functions.
Convert updateParams to update function in core's createFetch().
Will not merge with endpoint.update - instead overrides for simplicity.

enhance: Transform updateParams to 'update' function

---

packages/core/src/actionTypes.ts
packages/core/src/state/__tests__/reducer.ts
packages/core/src/state/reducer.ts
packages/core/src/types.ts

Empowers high-performance pluggable GC.
Plan is to follow up with shipping configurable GC Manager based on ref counting and LRU.
- New action that simply dictates which entities and/or results to remove.
- Assumes issuer properly ref counted so immutability guarantees are not violated since there should be no references.
```ts
export interface GCAction {
type: typeof GC_TYPE;
entities: [key: string, pk: string][];
results: string[];
}
```
`actionTypes.GC_TYPE`

feat: Add garbage collection action

---

packages/experimental/src/entity/EntityRecord.ts
packages/experimental/src/rest/BaseResource.ts
packages/experimental/src/rest/Resource.ts
packages/experimental/src/rest/__tests__/Resource.test.ts
packages/experimental/src/rest/getArrayPath.ts
packages/experimental/src/rest/test-fixtures.ts

Fixes #694 .
Pagination is a common scenario, that would benefit from minimal specification.
By default we rely on finding a list within the schema. The only remaining thing is figuring out how to extract the 'cursor' args to update the main list. Therefore, a function to do just that should be provided by the user like so.
```ts
class NewsResource extends Resource {
static listPage<T extends typeof NewsResource>(this: T) {
return this.list().paginated(({ cursor, ...rest }) => [rest]);
}
}
```
```tsx
import { useResource } from 'rest-hooks';
import NewsResource from 'resources/NewsResource';
function NewsList() {
const { results, cursor } = useResource(NewsResource.list(), {});
const curRef = useRef(cursor);
curRef.current = cursor;
const fetch = useFetcher();
const getNextPage = …
```

feat: Resource.list().paginated()

---

package.json
packages/test/package.json

- requires node 12
- 'suppressErrorOutput will now work when explicitly called, even if the
RHTL_DISABLE_ERROR_FILTERING env variable has been set' (from
react-hooks-testing-library)
It wasn't picking up on the version change, so trying to trigger it here.

internal: Major version bump

---

packages/experimental/src/entity/Entity.ts
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/entities/SimpleRecord.ts

Reduces memory pressure by providing a cached defaults for various algorithms.
```ts
private declare static __defaults: any;
protected static get defaults() {
if (!Object.prototype.hasOwnProperty.call(this, '__defaults'))
this.__defaults = new (this as any)();
return this.__defaults;
}
```

enhance: Cache entity default instances

---

packages/core/package.json
packages/endpoint/package.json
packages/experimental/package.json
packages/hooks/package.json
packages/img/package.json
packages/legacy/package.json
packages/normalizr/package.json
packages/rest-hooks/package.json
packages/rest/package.json
packages/test/package.json
packages/use-enhanced-reducer/package.json

With TypeScript 4.3, autocomplete imports work even better, which makes this extra important.
For some reason even though the * is recommended by typescript docs, and makes the typescript itself work, it results in 
```ts
import { useResource } from '@rest-hooks/core/*'
```
Even though vscode tells me this is not a valid key in the package.json, this makes both auto import and import autocomplete work. Additionally, both lookup and the types still work correctly.

enhance: Improve autoimport handling in vscode

---

packages/experimental/src/entity/Entity.ts
packages/normalizr/src/__tests__/inferResults.ts
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/entities/SimpleRecord.ts
packages/normalizr/src/index.ts
packages/normalizr/src/inferResults.ts
packages/normalizr/src/schema.d.ts
packages/normalizr/src/schemas/Array.js
packages/normalizr/src/schemas/Delete.ts
packages/normalizr/src/schemas/Object.js
packages/normalizr/src/schemas/Union.js
packages/normalizr/src/schemas/Values.js

Extracting `buildInferredResults()` into normalizr
- Simplify logic
- Customizable inference behavior including disabling
- Start supporting variable arg length
Add `infer()` to schemas. Somewhat similar to normalize, tho only tries to build results piece - no entity collection.
Utilize this in @rest-hooks/core. We split this up so we can distinctly mark a dependency on this feature in the other package.

feat: Add inferResults()

---

babel.config.js
package.json
packages/core/package.json
packages/endpoint/package.json
packages/experimental/package.json
packages/hooks/package.json
packages/img/package.json
packages/legacy/package.json
packages/normalizr/package.json
packages/rest-hooks/package.json
packages/rest/package.json
packages/test/package.json
packages/use-enhanced-reducer/package.json
yarn.lock

Fixes #902 .
Previously module target was variable based on browser usage, which meant recently since browsers have implemented features like Nullish coalescing, it was no longer being transpiled. This is problematic for near-abandonware like CRA, or simply slowly updated projects that cannot parse ?? (because CRA transpiles node_modules) - even if their target compilation supports it.
We set specific targets for the 'legacy' npm entrypoints that won't change over time:
- main - includes IE and maintained node versions
- module - browsers from start of 2019
For the latest entry point (currently only used in @rest-hooks/test):
- exports - shifting target that sufficiently includes a few generations back

enhance: 'module' entrypoint targets 2019 browsers

---

packages/core/src/internal.ts
packages/core/src/react-integration/hooks/useCache.ts
packages/core/src/state/selectors/useDenormalized.ts
packages/legacy/package.json
packages/legacy/src/index.ts
packages/rest-hooks/src/internal.ts

Builds on https://github.com/coinbase/rest-hooks/pull/900
Extracting `buildInferredResults()` into normalizr
- Simplify logic
- Customizable inference behavior including disabling
- Start supporting variable arg length
Add `infer()` to schemas. Somewhat similar to normalize, tho only tries to build results piece - no entity collection.

enhance: Use inferResults() from normalizr

---

packages/endpoint/src/__tests__/endpoint.ts
packages/endpoint/src/endpoint.js
packages/experimental/package.json
packages/experimental/src/rest/BaseResource.ts
packages/experimental/src/rest/__tests__/Resource.test.ts

function names are already a staple of javascript and can be useful for logging purposes. Endpoints try to be like functions as much as possible.
- automatically infer names that are available
- allow setting name explicitly during init
- @rest-hooks/experimental resource endpoints get 'ResourceName.method' names
- e.g.) 'ArticleResource.detail'
```typescript
const fetchUser = (id) => fetch(`/users/${id}`).then(res=>res.json();
const UserDetail = new Endpoint(fetchUser);
UserDetail.name === 'fetchUser'
const UserExtraDetail = UserDetail.extend({ name: 'extraDetail' });
UserExtraDetail .name === 'extraDetail';
```
```ts
import { Resource } from '@rest-hooks/experimental';
class User extends Resource {
readonly id: string = '';
readonly username: string = '';
pk() { return this.id }
static …
```

feat: Endpoint.name

---

packages/experimental/src/entity/Entity.ts
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/normalize.ts

Fixes #876 .
Configurable/Programmable TTL for entities
Entities+Resources get `expiresAt()`
```ts
class Entity {
static expiresAt(
{ expiresAt }: { expiresAt: number; date: number },
input: any,
): number {
return expiresAt;
}
}
```
By default as above, just uses the fetch's expiry time.
However, this can also check for complete members, to not count toward an entity's expiry time.
```ts
class MyResource extends Resource {
readonly id: string = '';
readonly basic: string = '';
readonly extendedContent?: { stuff: string };
pk() { return this.id }
static urlRoot = '/myresource/';
static expiresAt(
{ expiresAt }: { expiresAt: number; date: number },
input: any,
): number {
// extendedContent only exists when returning full results, so it's safe to infer this entity
return …
```

feat: Add Entity.expiresAt() - entity TTL configuration

---

packages/experimental/src/rest/Resource.ts

Previously we used params to essentially infer the pk, since it's very common for delete to return nothing. However, we can easily support this case, as well as the case with something by adding conditional check

feat: Support deletes with responses

---

packages/experimental/src/rest/types.ts

Due to every part of a union needing to match in inheritance, this was limiting overriding to specifics. We want to prioritize customizing specific types rather than being more specific in the base class
Mutates are expected to have a body, so use {} to represent non-void, otherwise any for reads.

enhance: More flexible fetch types to help with inheritance

---

packages/core/src/react-integration/__tests__/useError-endpoint.tsx
packages/core/src/react-integration/__tests__/useError.tsx
packages/core/src/react-integration/hooks/useCache.ts
packages/core/src/react-integration/hooks/useError.ts
packages/core/src/react-integration/hooks/useResource.ts
packages/legacy/src/useStatefulResource.ts

BREAKING CHANGE: useError() will no longer create synthetic
errors for missing entities
- At this point all error handling that can be done is handled during normalization
- We want to be more lenient on entity requirements for some use cases
- Previously this was needed as we were less explicit about inferring results
useError() now just returns the error in meta

enhance: useError() only checks meta error

---

__tests__/common.ts
packages/core/src/react-integration/__tests__/subscriptions-endpoint.tsx
packages/rest-hooks/package.json
packages/rest-hooks/src/index.ts
packages/rest-hooks/tsconfig.json

- Removed exports from 'rest-hooks': NestedEntity, schemas, isEntity, Entity, Resource, SimpleResource, SchemaDetail, SchemaList, Method
- use @rest-hooks/legacy, or @rest-hooks/rest instead

enhance: Remove Resource export from 'rest-hooks' package

---

packages/legacy/rollup.config.js

For some reason all other packages had BROWSERSLIST_ENV set correctly for the rollup step, but not this one.
The result is not transpiling to work on legacy node versions correctly.
`process.env.BROWSERSLIST_ENV = 'legacy';` in rollup just like every other package

fix: Legacy cjs and unpkg should target 'legacy'

---

packages/rest-hooks/src/manager/PollingSubscription.ts

Node and Dom have different types here, so let a users' environment dictate the types
Use ReturnType

enhance: setInterval types based on node/web rather than hardcoded

---

packages/endpoint/src/endpoint.d.ts

- Easier to read in vscode tooltip
- Hoisting complexity
```ts
export type ExtendedEndpoint<
O extends EndpointExtendOptions<F>,
E extends EndpointInstance<
FetchFunction,
Schema | undefined,
true | undefined
>,
F extends FetchFunction,
> = Omit<O, keyof EndpointInstance<FetchFunction>> &
Omit<E, keyof EndpointInstance<FetchFunction>> &
EndpointInstance<
'fetch' extends keyof O ? Exclude<O['fetch'], undefined> : E['fetch'],
'schema' extends keyof O ? O['schema'] : E['_schema'],
'sideEffect' extends keyof O ? O['sideEffect'] : E['sideEffect']
>;
```

enhance: Give Endpoint.extend() type a name

---

packages/core/src/react-integration/hooks/useExpiresAt.ts

BREAKING CHANGE: Rest Hooks 4 invalidIfStale behavior completely removed
- This was a workaround for particular behavior in Rest Hooks 4, before the modern invalidation schema
- This is no longer triggerable
Delete code

enhance: Remove extraneous hack for expiresAt

---

jest.config.js
packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx
packages/endpoint/src/__tests__/endpoint.ts
packages/hooks/src/__tests__/useCancelling.ts

- Some typos around async behavior found when doing https://github.com/coinbase/rest-hooks/pull/553

internal: Fix some test async behavior

---

__tests__/new.ts
packages/core/src/index.ts
packages/core/src/react-integration/__tests__/__snapshots__/hooks-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/hooks.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/useFetchDispatcher.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/useResource-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/useResource.web.tsx.snap
packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx
packages/core/src/react-integration/__tests__/subscriptions-endpoint.tsx
packages/core/src/react-integration/hooks/index.ts
packages/core/src/react-integration/hooks/useError.ts
packages/core/src/react-integration/hooks/useResource.ts
packages/core/src/state/__tests__/__snapshots__/reducer.ts.snap
packages/core/src/state/actions/createReceiveError.ts
packages/core/src/state/reducer.ts
packages/core/src/types.ts
packages/endpoint/src/types.ts
packages/experimental/src/rest/BaseResource.ts
packages/legacy/src/resource/SimpleResource.ts
packages/rest-hooks/src/manager/PollingSubscription.ts
packages/rest-hooks/src/manager/__tests__/__snapshots__/pollingSubscription-endpoint.ts.snap
packages/rest-hooks/src/manager/__tests__/__snapshots__/pollingSubscription.ts.snap
packages/rest/src/SimpleResource.ts

- Removed: SyntheticError (untriggerable since https://github.com/coinbase/rest-hooks/pull/938)
- @rest-hooks/rest: 500s are 'soft', else 'hard'
- PollingSubscription: all errors are 'soft'
- @rest-hooks/endpoint: no default errorPolicy, therefore all errors are
'hard'
Fixes #288 .
- Configurable cache policy for errors
- More sane defaults for errors
```ts
interface EndpointExtraOptions {
//...rest
errorPolicy?: (error: any) => 'soft' | undefined;
}
```
- 'soft' avoids errors if existing results are still available (even if stale)
- `undefined` (hard error) means any error always falls
New default policy: 5xx are soft, else hard.
`@rest-hooks/rest` is where errors have 'status' members. This concept does not exist in base Endpoints.
```ts
static getEndpointExtra(): …
```

feat: Add errorPolicy to endpoint options

---

packages/test/node.mjs
packages/test/package.json
packages/test/rollup.config.js

New way to deal with tooling that for some reason doesn't know what a .cjs is, but does know how to find package.json and understands the types fields in there.
This was in previous change for other packages, but it including a breaking symbol so we moved the test updates to here.

enhance: Use .js for cjs like other packages

---

packages/rest/src/SimpleResource.ts

Removing `SimpleResource` allows for `BaseResource` (see experimental pkg) without endpoints, which is more flexible root.
Fetch code is very small now so not having a fetch implementation is a very small win.
Step 1: deprecate

enhance: SimpleResource is deprecated

---

packages/core/src/index.ts
packages/core/src/react-integration/hooks/hasUsableData.ts
packages/core/src/react-integration/hooks/useCache.ts
packages/core/src/react-integration/hooks/useError.ts
packages/core/src/react-integration/hooks/useExpiresAt.ts
packages/core/src/react-integration/hooks/useFetchDispatcher.ts
packages/core/src/react-integration/hooks/useFetcher.ts
packages/core/src/react-integration/hooks/useInvalidateDispatcher.ts
packages/core/src/react-integration/hooks/useInvalidator.ts
packages/core/src/react-integration/hooks/useMeta.ts
packages/core/src/react-integration/hooks/useResource.ts
packages/core/src/react-integration/hooks/useRetrieve.ts
packages/core/src/react-integration/hooks/useSubscription.ts
packages/core/src/react-integration/index.ts
packages/core/src/state/NetworkManager.ts
packages/core/src/state/actions/createFetch.ts
packages/core/src/state/reducer.ts
packages/core/src/state/selectors/useDenormalized.ts
packages/core/src/types.ts
packages/legacy/src/index.ts
packages/rest-hooks/src/index.ts
packages/rest-hooks/src/manager/DefaultConnectionListener.ts
packages/rest-hooks/src/manager/PollingSubscription.ts
packages/rest-hooks/src/manager/index.ts
packages/rest-hooks/src/react-integration/index.ts
packages/rest-hooks/src/react-integration/provider/index.ts

`Could not find module in path: '@rest-hooks/core/legacy/state/actions.js' relative to '/node_modules/@rest-hooks/core/legacy/state/NetworkManager.js'`
The renaming to .js doesn't work with directories
Just refer directly to the index file for now until tooling is bettter
Previously `export { useDenormalized } from '@rest-hooks/core/state/selectors';` -> `export { useDenormalized } from './state/selectors.js'`
Now `export { useDenormalized } from '@rest-hooks/core/state/selectors/index';` -> `export { useDenormalized } from './state/selectors/index.js'`

fix: module build import path

---

packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/normalize.ts

Use case is to allow for flexible fetch combinations that denormalize with entities retrieved elsewise.
New policy is all validation/checking is done on denorm side. Normalize should allow as much as possible. This was originally allowed by the normalizr library.

feat: Allow normalizing entities that are just ids

---

packages/core/src/state/NetworkManager.ts
packages/core/src/state/__tests__/networkManager.ts
packages/core/src/types.ts
packages/experimental/src/__tests__/useFetcher.ts
packages/experimental/src/createFetch.ts
packages/experimental/src/rest/__tests__/Resource.test.ts

Part of https://github.com/coinbase/rest-hooks/issues/760
This makes little difference in React 18 since renders are batched; however in React < 18, this means that code after promise resolution will be executed before react renders - allowing actions that need to take place as a result of successful fetch. For example navigating off a deleted page after delete.
Using promise chaining allows us to order microtasks so the resolution of useFetcher()'s promise happens before dispatch of receive.
This has many consequences for existing behaviors so we are opting in via the new fetch mechanism.
It's now recommended to wrap all fetches in act when testing like so:
```ts
await act(async () => {
await result.current.fetch(ComplexResource.detail(), {
id: '5',
});
});
```

enhance: Experimental fetcher resolves before react render

---

packages/experimental/src/__tests__/useController.tsx
packages/experimental/src/__tests__/useFetcher.ts
packages/experimental/src/index.ts
packages/experimental/src/useController.ts
packages/experimental/src/useFetcher.ts

Consolidate, simplify hooks
Consistent interface between managers and hooks
Global referential equality available everywhere (managers and updaters)
Simplify and consolidate TTL and error concepts
Less code in hooks = less work on rendering leaf nodes
Icing on cake: ez migration to EndpointInterface and flexible args support for hooks
Future breaking changes can allow ez migration with version strings sent to `useController('v2')`
We're introducing fetch, invalidate, resetEntireStore today into experimental.
Full future plan:
```ts
const controller = useController();
// actions
controller.fetch(UserResource.detail(), { id }) // sideEffects means no throttle, otherwise throttle
controller.receive(payload, UserResource.detail(), { id })
controller.invalidate(UserResource.detail(), { id }) …
```

feat: useController()

---

packages/core/src/state/NetworkManager.ts
packages/core/src/state/__tests__/networkManager.ts
packages/core/src/state/reducer.ts
packages/rest-hooks/src/react-integration/provider/index.ts

Fixes #1071 .
For nested members, TTL eliminates fetches. However, with siblings fetches must be throttled. If this happens, devtools fills up with duplicate fetches that have no actual impact on the state.
- NetworkManager passes through all non-throttled fetch actions
- Place devtools after networkmanager
- Update reducer tracking to ensure NM is still installed

enhance: Hide throttled fetches from devtools

---

examples/todo-app/src/resources/TodoResource.ts
packages/core/src/react-integration/__tests__/useResource-endpoint.web.tsx
packages/experimental/src/rest/BaseResource.ts
packages/experimental/src/rest/Resource.ts
packages/rest/src/SimpleResource.ts

Fixes #1101 .
useFetchInit() can call hooks, so we need to ensure it is called only from top level and not conditionally
Hoist all endpoint calls to top level.
Validated against example usage from https://github.com/coinbase/rest-hooks/issues/1101
We should think about suggesting use-prefix for endpoints that use this to ensure linter helps avoid these scenarios.

fix: useFetchInit() hook calls same amount every render

---

packages/core/src/react-integration/__tests__/integration.web.tsx
packages/core/src/state/NetworkManager.ts
packages/experimental/src/__tests__/useController.tsx

Apparently this render is triggered event tho state === state in reducer.
This was introduced in https://github.com/coinbase/rest-hooks/pull/1083 which sends through fetch actions so they can be picked up by dev middleware.
For now just schedule throttled fetches as a macrotask to keep it off same callstack.
Perhaps there's a way to keep this from reducer while still controller which go to middlewares?

fix: Cannot update a component while rendering a different component

---

packages/experimental/src/rest/Resource.ts
packages/experimental/src/rest/__tests__/Resource.test.ts

Empty object is unusable to lookup PK, so for this case we can try to fallback to params
`Object.keys(res).length`. If response is not an object it's likely going to fail this anyway

enhance: Resource.delete() handles empty object response

---

packages/core/src/state/NetworkManager.ts
packages/core/src/state/reducer.ts
packages/rest-hooks/src/manager/DevtoolsManager.ts
packages/rest-hooks/src/react-integration/provider/index.ts

Turns out react doesn't always short circuit reducers even with ===. It seemed like there were sometimes jank around loading.
Prior: https://github.com/coinbase/rest-hooks/pull/1083 https://github.com/coinbase/rest-hooks/pull/1130
Back to avoiding reducer - but we introduce `skipLogging` which is sent to devtools to know when to skip logging fetches. This adds an API surface area but is ultimately a cleaner code path.
Effectively https://github.com/coinbase/rest-hooks/pull/1083  is undone in favor of this solution

enhance: Back to avoiding reducer for fetch

---

packages/core/src/internal.ts
packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx
packages/core/src/react-integration/provider/BackupBoundary.tsx
packages/core/src/react-integration/provider/CacheProvider.tsx
packages/core/src/react-integration/provider/__tests__/__snapshots__/provider.tsx.snap
packages/core/src/react-integration/provider/__tests__/provider.tsx
packages/test/src/makeRenderRestHook.tsx

It's very confusing if a user misses Suspense or puts in the wrong place. Point them to the correct documentation when this occurs.
- Put Suspense just below rest of CacheProvider. Fallback will do the warning.
- [makeRenderRestHook](https://resthooks.io/docs/api/makeRenderRestHook) needs a suspense boundary so it doesn't trigger the warning in console for tests

enhance: Warn users if they are missing Suspense boundary

---

packages/experimental/src/rest/BaseResource.ts
packages/legacy/src/resource/Resource.ts
packages/rest/src/Resource.ts

Sometimes `response.statusText` is empty, making the error message empty
Fallback to response.status

enhance: Improve NetworkError debuggability

---

packages/core/README.md
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/entities/__tests__/Entity.test.ts
packages/normalizr/src/entities/__tests__/__snapshots__/Entity.test.ts.snap
packages/normalizr/src/schema.d.ts
packages/normalizr/src/schemas/Array.ts
packages/normalizr/src/schemas/Delete.ts

Entities can come from different endpoints than they are retrieved from.
This enables cases where you might want to send only partial fields for a short list, and then send the rest in longer. In this case you don't want to use partial entities.
```ts
class ArticlePreview extends Entity {
readonly id: string = '';
readonly title: string = '';
pk() { return this.id; }
static key() { return 'Article'; }
}
const articleList = new Endpoint(fetchList, { schema: [ArticlePreview] });
class ArticleFull extends ArticlePreview {
readonly content: string = '';
readonly createdAt: Date = new Date(0);
static schema = {
createdAt: Date,
}
static validate(processedEntity) {
if (!Object.hasOwn(processedEntity, 'content')) return 'Missing content';
}
}
const articleDetail = new Endpoint(fetchDetail, { …
```

enhance: validate during denormalization

---

docs/rest/usage.md
packages/core/src/state/__tests__/reducer.ts
packages/core/src/state/reducer.ts

If action types aren't typed correctly it's easy for someone dispatching these to be missing dates. Doing so will stall the entire store and no useResource() suspense will ever complete.
Warn in non-prod; and add fallback so things still work.

enhance: Improve robustness for legacy RESET actions

---

docs/graphql/auth.md
docs/graphql/usage.md
docs/guides/auth.md
docs/rest/usage.md
packages/experimental/src/rest/Resource.ts
packages/experimental/src/rest/__tests__/Resource.test.ts
packages/experimental/src/rest/test-fixtures.ts

Order is typically very important for list results
Instead of placing in a giant set - we explicitly iterate only added to end.

enhance: Maintain order during pagination

---

packages/experimental/src/rest/Resource.ts
packages/experimental/src/rest/__tests__/Resource.test.ts
packages/experimental/src/rest/types.ts

BREAKING CHANGE: Updated types of RestEndpoint, RestFetch, FetchGet, FetchMutate
Couldn't specify return types in inheritance
- RestEndpoint was too restrictive
- Improve RestFetch to be more usable with variable args

enhance: Improve list().paginated() types

---

packages/rest-hooks/src/react-integration/provider/ExternalCacheProvider.tsx

fix: Provide same referential guarantees when using redux

---

.circleci/config.yml

Tests are universally failing for a few days now.
Hidden in the test logs I found
```bash
#
#
#
#
#FailureMessage Object: 0x7ffcea876140
1: 0xb691f1  [/usr/local/bin/node]
2: 0x1bf3094 V8_Fatal(char const*, ...) [/usr/local/bin/node]
3: 0x10ac4a1 v8::internal::ConcurrentLookupIterator::TryGetPropertyCell(v8::internal::Isolate*, v8::internal::LocalIsolate*, v8::internal::Handle<v8::internal::JSGlobalObject>, v8::internal::Handle<v8::internal::Name>) [/usr/local/bin/node]
4: 0x1c5aa55  [/usr/local/bin/node]
5: 0x1c5b9eb v8::internal::compiler::JSGlobalObjectRef::GetPropertyCell(v8::internal::compiler::NameRef const&, v8::internal::compiler::SerializationPolicy) const [/usr/local/bin/node]
6: 0x1e61ba3 v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(v8::internal::comp …
```

internal: Fix node minor version so jest doesn't break

---

docs/api/useLoading.md
docs/introduction.md
packages/hooks/src/__tests__/useLoading.ts
packages/hooks/src/useLoading.ts

BREAKING CHANGE: onError() is no longer second argument;
To handle this case, simply .catch() yourself.
Simplify definitions avoiding need to useCallback
```ts
const { fetch } = useController();
const [toggleHandler, loading, error] = useLoading(
(e: ChangeEvent<HTMLInputElement>) =>
fetch(
TodoResource.partialUpdate(),
{ id },
{ completed: e.currentTarget.checked },
),
[fetch],
);
```

feat: useLoading() second argument is deps list

---

.circleci/config.yml

Coveralls has been down for days blocking progress. Sometimes their services has issues as well - these shouldn't block progress.
We will fail on test:coverage, but the actual sending to coveralls we don't fail

internal: Don't fail coverage if coveralls is down

---

docs/api/Manager.md
docs/api/SimpleRecord.md
docs/api/useFetcher.md
docs/api/useLoading.md
docs/guides/redux.md
packages/core/src/controller/Controller.ts
packages/core/src/controller/createFetch.ts
packages/core/src/controller/createReceive.ts
packages/core/src/controller/createSubscription.ts
packages/core/src/index.ts
packages/core/src/react-integration/provider/CacheProvider.tsx
packages/core/src/react-integration/provider/CacheStore.tsx
packages/core/src/state/NetworkManager.ts
packages/core/src/state/__tests__/networkManager.ts
packages/core/src/state/applyManager.ts
packages/core/src/types.ts
packages/rest-hooks/src/manager/__tests__/subscriptionManager.ts
packages/rest-hooks/src/react-integration/provider/mapMiddleware.ts
packages/test/src/managers.ts
packages/test/src/providers.tsx

- applyManager()
- controller in middlewares
Controller provides a cleaner and more consistent interface to the store. This also makes the interaction points more discoverable as any TypeScript supporting editor will autocomplete (even if the user is using javascript).
Added to middleware api
```ts
export interface MiddlewareAPI<
R extends React.Reducer<any, any> = React.Reducer<any, any>,
> {
getState: () => React.ReducerState<R>;
dispatch: Dispatch<R>;
controller: Controller;
}
```
This is adapted to still be redux-middleware compatible via the `applyManager()` method. This turns a manager into a redux-middleware
Due to the way typescript handles function parameter typing, this will not break compatibility with any existing middlewares since it is only an addition.
Also, by not using …

feat: Send controller to middlewares

---

examples/github-app/CHANGELOG.md
examples/github-app/package.json
examples/todo-app/CHANGELOG.md
examples/todo-app/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/experimental/CHANGELOG.md
packages/experimental/package.json
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/rest-hooks/CHANGELOG.md
packages/rest-hooks/package.json
packages/test/CHANGELOG.md
packages/test/package.json

- @rest-hooks/core@2.1.0
- @rest-hooks/experimental@2.0.0
- @rest-hooks/hooks@2.0.0
- rest-hooks@6.1.0
- @rest-hooks/test@7.1.0

internal: publish 6.1

---

packages/hooks/src/__tests__/useLoading.ts
packages/hooks/src/useLoading.ts

When using deps list, we want to inline the function so it won't maintain stability. However, without deps list it should be based on the function.

feat: Maintain referential stability when deps are used

---

packages/core/src/controller/Controller.ts
packages/core/src/controller/__tests__/__snapshots__/fetch.tsx.snap
packages/core/src/controller/__tests__/fetch.tsx
packages/core/src/endpoint/adapter.ts
packages/core/src/react-integration/hooks/useCache.ts
packages/core/src/react-integration/hooks/useError.ts
packages/core/src/react-integration/hooks/useResource.ts
packages/core/src/state/reducer.ts
packages/core/src/state/selectors/useDenormalized.ts

Continuing https://github.com/coinbase/rest-hooks/pull/1239
This extracts the core logic into a more accessible piece.
- Easier implementations for various frameworks
- Easier implementations for different hookups like context selectors
- Programmatic access to same values from hooks, which can be used for procedural pieces
```tsx
const { data, suspend, expiresAt } = controller.getResponse(UserResource.detail(), { id }, state)
const error = controller.getError(UserResource.detail(), { id }, state)
```
useDenormalized logic moved into controller.getResponse(). Except it's based on [endpoints](https://resthooks.io/docs/getting-started/endpoint) instead of shapes. Because of this useDenormalized first constructs an endpoint with the adapter `shapeToEndpoint()`

feat: Add controller.getResponse()

---

packages/legacy/src/resource/Entity.ts
packages/legacy/src/resource/Object.ts
packages/legacy/src/resource/SimpleRecord.ts
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/schema.d.ts

Stronger types
This doesn't break back compat as you can send non-readonly things as args

enhance: infer() args are readonly

---

packages/core/src/react-integration/provider/CacheProvider.tsx

Fixes #1306
This prevent react-native app from crashing when using default `<CacheProvider />` component.

fix: remove unwanted string in CacheProvider

---

package.json
packages/core/package.json
packages/core/rollup.config.js
packages/core/src/react-integration/provider/BackupBoundary.native.js
packages/core/src/react-integration/provider/BackupBoundary.tsx
tsconfig-base.json
yarn.lock

CacheProvider is needed in all installs, so ensure it works in all compatible cases.
- .native extension allows for RN specific version that uses <Text>
- Don't use <Suspense/> in React 16, 17 when doing SSR - as it will show fallback which will likely block entire app

enhance: Improve compatibility with SSR and React Native

---

packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/denormalize.ts

Fixes #1312 (assuming this is the cause)
If someone accidentally installs multiple versions of normalizr, identity of Symbols won't work, but it won't manifest in an obvious way.
Outright throw an error during denormalization. We only do this during dev mode as packages are not expected to change from dev to production and this would incur a cost for a very extreme edge case.

enhance: Detect multiple normalizr copies installed

---

docs/upgrade/upgrading-to-6.md

Played around til I could get decent instructions here. If they upgrade in one command it avoids duplication so frontload those instructions then change the npm mitigation to be a backup plan.

docs: Better guide to avoid npm upgrade issue

---

website/package.json
website/yarn.lock

Moved CacheProvider render to not depend on execution environment, so we need the fixed version of rest hooks that renders SSR.

docs(fix): Server compiling

---

packages/core/src/state/NetworkManager.ts

Access to endpoint in action is useful
In case of users extending NetworkManager without TypeScript we conditionally check controller existance for legacy protection

enhance: Dispatch new receive action if new fetch triggered it

---

packages/experimental/src/hooks/__tests__/useSuspense.web.tsx
packages/experimental/src/hooks/useSuspense.ts

Need protection in case a user passes null
```ts
E['schema'] extends Exclude<Schema, null>
? CondNull<
Args[0],
DenormalizeNullable<E['schema']>,
Denormalize<E['schema']>
>
: CondNull<Args[0], undefined, ReturnType<E>>
```

fix: Return type of useSuspense should factor in null params

---

packages/core/src/react-integration/__tests__/hooks-endpoint.web.tsx
packages/endpoint/src/endpoint.d.ts

Fixes #1474 .
New endpoints allow any number of arguments. Zero arguments are still valid with legacy hooks, so there's no reason to not make this work.
Update getFetchKey to be aware of the possibilities for no arguments

fix: useFetcher() work with zero argument Endpoint

---

.circleci/config.yml
.github/dependabot.yml
package.json
yarn.lock

- Test coverage seems to be running out of memory.
- Setup is both blocking and the longest step
Details:
- cache path does not support wildcard, so expand to explicit paths
- specify resource for specific workflows to increase memory and computational power
- build step explicitly only run build as prepare will cover types
- switch react 18 specification from 'next' to 'beta'

internal: Use bigger resources for expensive parts of CI flow

---

website/docusaurus.config.js

This allows release of updates to 6.1 docs without replacing the default to the yet-unreleased 6.2. Also allows people to navigate to 6.2 if they want.

docs: Set 6.2 as unreleased

---

website/docusaurus.config.js

They moved the config in https://github.com/facebook/docusaurus/pull/5832 kinda hidden in changelog

docs(fix): Google analytics integration with website

---

__tests__/new.ts
docs/api/Controller.md
docs/api/Snapshot.md
docs/guides/optimistic-updates.md
docs/introduction.md
packages/core/src/controller/Controller.ts
packages/core/src/controller/createFetch.ts
packages/core/src/controller/createOptimistic.ts
packages/core/src/controller/createReceive.ts
packages/core/src/controller/createReset.ts
packages/core/src/react-integration/__tests__/hooks-endpoint.web.tsx
packages/core/src/react-integration/__tests__/hooks.web.tsx
packages/core/src/react-integration/__tests__/integration-optimistic-endpoint.web.tsx
packages/core/src/react-integration/hooks/useResetter.ts
packages/core/src/state/NetworkManager.ts
packages/core/src/state/__tests__/reducer.ts
packages/core/src/state/actions/createFetch.ts
packages/core/src/state/createReducer.ts
packages/core/src/types.ts
packages/endpoint/src/SnapshotInterface.ts
website/package.json
website/src/components/Playground/Tree.tsx
website/src/components/Playground/resources/TodoResource.ts
website/src/mocks/handlers.js
website/src/mocks/init.js
website/static/mockServiceWorker.js
website/versioned_docs/version-5.0/introduction.md
website/versioned_docs/version-6.0/introduction.md
website/versioned_docs/version-6.1/introduction.md
website/yarn.lock

We need to ensure only one optimistic response is removed from queue per fetch. This requires exact timestamp matching.
Previously, we did not copy the timestamp but create it twice - this means time between each resulted in them not precisely equally.
- Add `Controller.resolve(endpoint, { args, response, fetchedAt, error })`
- This is similar to receive, except it triggers resolution of an inflight fetch.
- Make docs site use relative package paths to use the latest packages for rest hooks
- Track fetch createdAt with timestamp as it has milisecond resolution. This is used in the receive action as 'fetchedAt' to find the specific corresponding optimistic update to filter away.
- Remove vector clocks example for now as this is only requires for edits on other clients.

enhance: Fetch resolution only removes the optimistic update corresponding to that fetch

---

docs/getting-started/expiry-policy.md
website/versioned_docs/version-5.0/getting-started/expiry-policy.md
website/versioned_docs/version-6.0/getting-started/expiry-policy.md
website/versioned_docs/version-6.1/getting-started/expiry-policy.md

docs(fix): Correct endpoint.dataExpiryLength in getting started

---

packages/test/package.json

Missed this when moving the files around. Noticed this when experimenting with PNP for package mgmt
Remember we already put a package.json with `{"type":"commonjs"}` in the dist dir so this should be read as cjs.

fix: exports.require filepath

---

packages/rest/src/EntityRecord.ts
packages/rest/src/SimpleResource.ts
packages/rest/src/legacy.ts
packages/rest/src/types.ts

Newer tools are stricter about this sort of thing.

fix: Only import from explicit dependencies

---

packages/hooks/src/__tests__/useLoading.ts
packages/hooks/src/useLoading.ts

BREAKING CHANGE: useLoading() consumes all promise rejections
Unhandled errors reach the top.  Without handling the error ourselves we force users to try/catch just to prevent bubbling.
Consume errors. Users can still handle errors differently from within the function passed to useLoading.

enhance: useLoading() should consume rejections

---

packages/test/src/mockState.ts

```bash
export 'createReducer' (imported as 'RestHooks') was not found in '@rest-hooks/core' (possible exports: CacheProvider, Controller, ControllerContext, DELETED, DenormalizeCacheContext, DispatchContext, Endpoint, Entity, ExpiryStatus, Index, NetworkManager, ResetError, StateContext, __INTERNAL__, actionTypes, applyManager, createFetch, createReceive, createReceiveError, hasUsableData, initialState, isEntity, reducer, schema, useCache, useController, useDenormalized, useError, useFetchDispatcher, useFetcher, useInvalidateDispatcher, useInvalidator, useMeta, usePromisifiedDispatch, useResetter, useResource, useRetrieve, useSubscription)
@ ../../node_modules/@rest-hooks/test/lib/browser.js 2:0-46 4:0-42
@ ./src/pages/PostDetail/post.stories.tsx 30:0-48 67:27-39
@ ././ sync …
```

fix: Compatibility with webpack builds for test

---

packages/core/src/controller/Controller.ts
packages/core/src/react-integration/newhooks/__tests__/useSuspense.web.tsx

So rarely don't use endpoints with no schema so just noticed this. InvalidIfStale should be suspending on stale data for endpoints with no schema.

fix: InvalidIfStale should be respected in no-schema endpoints

---

packages/img/src/Img.tsx
packages/img/src/__tests__/Img.web.tsx

Fixes #1723 .
When using design systems sometimes you want to use a specific element to render your media.
Using the same signature as `React.ComponentProps` generic allows us to ensure prop enforcement for both components and 'string' components.

feat: Add component prop to Img

---

packages/rest-hooks/src/react-integration/provider/PromiseifyMiddleware.ts

Previously it imported `MiddlewareAPI` from @rest-hooks/core which now has controller type. The controller is actually not used at this point because it's redux-compatible middlewares, so this was causing typing errors with redux setup.
Since we don't actually use the middleware api, let it match anything with `unknown`.

fix: Loosen PromiseifyMiddleware types to only what is needed

---

packages/experimental/src/rest/BaseResource.ts
packages/experimental/src/rest/__tests__/Resource.test.ts
packages/rest/src/SimpleResource.ts
packages/rest/src/__tests__/resource-endpoint.ts

Fixes #1727 .
Resources should return the same object initialized with fromJS() when they are enumerated through spread. This matches normally expected behavior.
We can still provide a non-enumerable url getter in the prototype by making the setter define url in the instance with `Object.defineProperty`. Previous attempts to do this failed due to not using the special method. We also test hasOwnProperty() behavior

fix: Resource.url properties are enumerable when provided

---

packages/core/src/controller/createReceive.ts

Noticing fetching was increasing when moving to useSuspense(). Realized, the defaults in useSuspense() had error and success expiry times reversed from the defaults specified here: https://github.com/coinbase/rest-hooks/blob/master/packages/core/src/state/NetworkManager.ts#L48
Now:
1 minute for success
1 second for error

fix: Expiry defaults for useSuspense() should match useResource()

---

docs/guides/redux.md

Missed this when moving to createReducer. Since we targetted backcompat the old way will still work but we want new solutions to use the new method.

docs(fix): Update redux docs to use createReducer()

---

packages/core/src/index.ts
packages/core/src/react-integration/provider/index.ts
packages/rest-hooks/src/react-integration/provider/ExternalCacheProvider.tsx

Triggered by hydration mismatch which occurs when Suspense boundaries don't match during SSR hydration.
BackupBoundary was originally added to help with people missing Suspense in their setup. However, we missed adding it to ExternalCacheProvider. That alone is enough to add, however, for SSR to hydrate an ExternalCacheProvider into a CacheProvider, one must ensure the same amount and placement of Suspense, which makes this even more critical as concurrent partial hydration outright disables when those don't match.
Export from core. Use in ExternalCacheProvider

enhance: Use BackupBoundary to help debug setup issues

---

packages/core/src/react-integration/newhooks/__tests__/useSuspense.web.tsx
packages/core/src/react-integration/provider/__tests__/__snapshots__/provider.tsx.snap
packages/core/src/state/NetworkManager.ts
packages/core/src/state/__tests__/__snapshots__/reducer.ts.snap
packages/core/src/state/__tests__/networkManager.ts
packages/core/src/state/createReducer.ts

Store must be 100% serializable to make SSR work.
I ran into this issue when building out React 18 SSR. The fetches would all stall. After investigation I realized -Infinity serializes to null since it isn't part of JSON spec to have infinity.
Since the error is so catastrophic but not visible, we do two fold protection:
- Assume nothing about correctness of cache and do comprehensive checks in getLastReset()
- Use 0 as initial value. This should be just as sufficient as -Infinity since time is currently well in the future of 1970.

fix: lastReset should serialize

---

.github/workflows/codeql-analysis.yml

GitHub asks users to define workflow permissions, see https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ and https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token for securing GitHub workflows against supply-chain attacks.
[StepSecurity](https://github.com/step-security) is working on securing GitHub Actions and [OSSF Scorecards](https://github.com/ossf/scorecard) recommends using the StepSecurity [secure-workflows online tool](https://app.stepsecurity.io/) to improve the security of GitHub workflows.
This repository has a Scorecards score of 6.5/10 with 10 being the most secure. The `Token-Permissions` category has a score of 0/10. The link to the score is …

fix: Job permissions for codeql-analysis.yml

---

__tests__/new.ts
docs/api/Entity.md
docs/guides/optimistic-updates.md
jest.config.js
packages/core/src/controller/createOptimistic.ts
packages/core/src/react-integration/__tests__/integration-optimistic-endpoint.web.tsx
packages/core/src/state/createReducer.ts
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/normalize.ts
packages/normalizr/src/schemas/Delete.ts
website/src/components/Playground/resources/TodoResource.ts
website/static/mockServiceWorker.js

https://github.com/coinbase/rest-hooks/pull/1653 enables full race condition handling when server sends its date. However, without such special handling common cases were subject the client race conditions that were previously avoided.
Previously we had logic to try to solve the common case; this pulls this out into overridable function that makes it simple. This also has advantage of improved legacy compat as noone will have previously defined this so previous merge overrides still work.

feat: Entity.useIncoming() for race condition handling

---

packages/rest-hooks/src/react-integration/NetworkErrorBoundary.tsx

For legacy support TypeScript has a weird expectation that components all render elements, even tho children are nodes.
Explicit return type

fix: NetworkErrorBoundary should render Element

---

packages/core/src/controller/Controller.ts
packages/core/src/react-integration/hooks/useCache.ts
packages/core/src/react-integration/hooks/useError.ts
packages/core/src/react-integration/newhooks/__tests__/useCache.tsx
packages/core/src/react-integration/newhooks/__tests__/useSuspense.web.tsx
packages/core/src/react-integration/newhooks/constants.ts
packages/core/src/react-integration/newhooks/useCache.ts
packages/core/src/react-integration/newhooks/useError.ts
packages/core/src/react-integration/newhooks/useFetch.ts
packages/core/src/react-integration/newhooks/useSubscription.tsx
packages/core/src/react-integration/newhooks/useSuspense.ts
packages/core/src/state/selectors/useDenormalized.ts
packages/endpoint/src/SnapshotInterface.ts
packages/legacy/src/useStatefulResource.ts

Precisely handle null case.
Reduce type and runtime complexity by moving 'null' handling where it belongs. `null` arguments are only a concept needed for hooks since hooks cannot be called conditionally. Therefore, that logic should be tied to the hooks, and removed from further callstacks as early as possible
- Hoist null check to as early as possible
- Simplify snapshot types to alleviate typescript pressure. No reason some should need null params in a getOptimisticResponse
- We keep null handling in existing controller methods for back compatibility. However, in the future we should remove these as null is a leaky abstraction beyond hooks
- Ensure new hooks type handle null parameters as 'undefined' data
Note: making the title of this based on the external impact, since that trumps any …

enhance: Hooks should type return value based on 'null' arg

---

packages/endpoint/src/Expiry.ts
packages/endpoint/src/SnapshotInterface.ts
packages/endpoint/src/index.ts
packages/endpoint/src/types.ts

With multiple versions of @rest-hooks/endpoint installed, this could result in hooks not matching the types expected.
`ExpiryStatusInterface` has identical structural type, but lacks the nominal typing restriction that breaks multi-package compatibility.

enhance: Loosen SnapshotInterface to allow compatible but distinct versions

---

website/src/components/Playground/Tree.tsx
website/tsconfig.json

Similar to redux-devtools integration, improve the store treeview for demos on the docs site

docs: More readable timestamp in demos

---

docs/api/Entity.md
packages/core/src/react-integration/__tests__/integration-optimistic-endpoint.web.tsx
packages/core/src/react-integration/__tests__/useExpiresAt.tsx
packages/core/src/react-integration/provider/__tests__/__snapshots__/provider.tsx.snap
packages/core/src/state/NetworkManager.ts
packages/core/src/state/__tests__/__snapshots__/reducer.ts.snap
packages/core/src/state/__tests__/networkManager.ts
packages/core/src/state/__tests__/reducer.ts
packages/core/src/state/actions/createReceive.ts
packages/core/src/state/actions/createReceiveError.ts
packages/core/src/types.ts
packages/legacy/src/resource/Entity.ts
packages/legacy/src/resource/__tests__/__snapshots__/Delete.test.ts.snap
packages/legacy/src/resource/__tests__/__snapshots__/Entity.test.ts.snap
packages/legacy/src/resource/__tests__/__snapshots__/SimpleRecord.test.ts.snap
packages/legacy/src/resource/__tests__/__snapshots__/normalizr.test.js.snap
packages/normalizr/src/__tests__/__snapshots__/index.test.js.snap
packages/normalizr/src/entities/Entity.ts
packages/normalizr/src/entities/__tests__/__snapshots__/Entity.test.ts.snap
packages/normalizr/src/normalize.ts
packages/normalizr/src/schema.d.ts
packages/normalizr/src/schemas/Delete.ts
packages/normalizr/src/schemas/__tests__/__snapshots__/Array.test.js.snap
packages/normalizr/src/schemas/__tests__/__snapshots__/Delete.test.ts.snap
packages/normalizr/src/schemas/__tests__/__snapshots__/Object.test.js.snap
packages/normalizr/src/schemas/__tests__/__snapshots__/Serializable.test.ts.snap
packages/normalizr/src/schemas/__tests__/__snapshots__/Union.test.js.snap
packages/normalizr/src/schemas/__tests__/__snapshots__/Values.test.js.snap
packages/normalizr/src/types.ts
website/src/components/Playground/resources/TodoResource.ts

While adapting API is useful to guarantee correct handling of networking race conditions, the default case should handle the most common assumption. That assumption is that fetches will be resolved in the order they are sent. This makes sense because the only race condition where this is violated is if the server receive time is variable. Whereas there are many parts afterward there could affect response timing.
This assumption makes sense because with an RDS, transactions will lock a given row on first-come basis; and that transaction will only include updates from that request - thus any requests received during processing of that request will *not* be reflected in the response.
Numbered are events; the bullets represent what state is applied
1) fetch1
- optimistic1
2) fetch2
- …

fix: Default optimistic race condition assume in-order fetch timings

---

packages/core/src/controller/Controller.ts
packages/core/src/react-integration/hooks/useCache.ts
packages/core/src/react-integration/newhooks/__tests__/useCache.tsx
packages/core/src/react-integration/newhooks/__tests__/useSuspense.web.tsx
packages/core/src/react-integration/newhooks/constants.ts
packages/core/src/react-integration/newhooks/useCache.ts
packages/core/src/react-integration/newhooks/useError.ts
packages/core/src/react-integration/newhooks/useFetch.ts
packages/core/src/react-integration/newhooks/useSuspense.ts
packages/core/src/state/selectors/useDenormalized.ts
packages/legacy/src/__tests__/useStatefulResource.tsx
packages/legacy/src/useStatefulResource.ts

Maintaining schema structure simplifies cases where entities are nested in a structure even if null parameter is set. A common need for this is in pagination.
```tsx
const { results, nextPage } = useSuspense(
PaginatedArticleResource.list(),
should ? {} : null,
);
```
Undo part of https://github.com/coinbase/rest-hooks/pull/1783
However, still not accept null params in snapshot and keep some of the type improvements.
Add a test for pagination that validates types and runtime value.

fix: Hooks with null param maintain basic schema structure

---

packages/test/src/mockState.ts
packages/test/src/providers.tsx
packages/test/tsconfig.compile.json

Test package should be compatible with a wide range of rest hooks versions. To make this possible it should rely on the interfaces of whatever provided package exists.
Previously TypeScript compilation ended up duplicating State instead of referencing it which meant it was whatever State happened to be at the time of compilation. By explicitly setting the return value and using 'function' vs 'const' TypeScript will retain the reference to the imported type. This leads me to believe const functions should be avoided at all costs if not necessary (like when using them for the desired behavior of `this` scoping)
Also added `exactOptionalPropertyTypes` compiler flag; but this wasn't necessary for this fix. I kept it because it seems like a better way forward.
```ts
export default function …
```

fix: Use imported State interface rather than a copy

---

website/yarn.lock

Since we use relative paths (waiting on yarn 3, which is waiting on renovate), yarn.lock has to be updated every publish to get new versions.

docs: Update yarn.lock for docs site

---

website/docusaurus.config.js
website/package.json
website/versioned_docs/version-6.1/upgrade/upgrading-to-5.md
website/yarn.lock

- `fromExtensions: ['html'],` is actually redundant and spits out errors
- redirect /docs/next/api/useSuspense
- use more canonical path names for versions
- add production docs site serving
- fix a bad link in 6.1 docs

docs: Redirect next/api/useSuspense

---

packages/experimental/src/rest/BaseResource.ts

BREAKING CHANGE: Resource loses hasDefined, mergeRecord,
toObjectDefined, keysDefined, set
These weren't super useful in practice
No longer rely on rest package which shouldn't have been the case to begin with.

enhance: Resource extends from Entity rather than EntityRecord

---

packages/core/src/react-integration/provider/CacheProvider.tsx

Users can extends Controller to augment or add extra methods
```tsx
class MyController extends Controller {
}
<CacheProvider Controller=MyController/>
```

feat: Add CacheProvider Controller prop to allow controller customization

---

packages/core/src/index.ts
packages/core/src/react-integration/newhooks/__tests__/fixtures.ts
packages/core/src/react-integration/newhooks/__tests__/useDLE.tsx
packages/core/src/react-integration/newhooks/index.ts
packages/core/src/react-integration/newhooks/useCache.ts
packages/core/src/react-integration/newhooks/useDLE.ts

Fixes #1467
- Keep legacy just for back compat support.
- Avoid cross-package peerDeps issues with weird package managers
useDLE (data-loading-error) is like useStatefulResource except:
- Accepts [Endpoints](https://resthooks.io/docs/getting-started/endpoint) only
- Inside core package so additional package not needed.
- Doesn't awkwardly rely on denormalize export from normalizr
- Everything else is copy/paste of useStatefulResource()
Note: Keeping useStatefulResource() in legacy for use with FetchShape

feat: Add useDLE() to core

---

packages/core/src/controller/createReceive.ts
packages/core/src/react-integration/__tests__/integration-optimistic-endpoint.web.tsx
packages/core/src/react-integration/__tests__/integration-optimistic-legacy-endpoint.web.tsx
packages/normalizr/src/normalize.ts
packages/test/src/MockResolver.tsx
packages/test/src/mockState.ts

When using modern fetch methods like useSuspense and Controller.fetch, the legacy optimisticUpdate computing a fetchedAt of 0 which cannot compare to previously stored data. This was missed in our legacy optimisticUpdate tests due to our mocking code not reflecting the new behavior of those new fetches.
- Update mock state to detect new fetches and appropriately reflect their behavior.
- Only useIncoming() when fetchedAt is defined (to fallback to previous behavior if not existing)
- Ensure legacy test fails when fix is not in place

fix: optimisticUpdate when used with controller.fetch or useSuspense

---

packages/legacy/src/index.ts

Relative imports only work with files not folders

fix: Legacy exports

---

__tests__/common.ts
__tests__/legacy-optimistic.ts
__tests__/new.ts
packages/core/src/react-integration/__tests__/__snapshots__/hooks-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/__snapshots__/integration-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/endpoint-types.web.tsx
packages/core/src/react-integration/__tests__/hooks-endpoint.web.tsx
packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx
packages/core/src/react-integration/__tests__/integration-optimistic-endpoint.web.tsx
packages/core/src/state/__tests__/reducer.ts
packages/rest/package.json
packages/rest/src/HookableResource.ts
packages/rest/src/Resource.ts
packages/rest/src/__tests__/hookableresource-endpoint.ts

BREAKING CHANGE: fetch(Resource.create(), {}, body) -> fetch(Resource.create(), body)
More intuitive endpoint definitions
```tsx
const list = useSuspense(MyResource.list());
const filtered = useSuspense(MyResource.list(), { onlyGood: true });
```
```tsx
const { fetch } = useController()
const handler = () => fetch(MyResource.create(), payload);
```

feat: Simplify Resource.create() & Resource.list() arguments 

---

packages/core/src/react-integration/__tests__/hooks-endpoint.web.tsx
packages/endpoint/src/endpoint.d.ts

https://github.com/coinbase/rest-hooks/pull/1514 wasn't good enough. This ends up doing weird things when the first param is optional because undefined is a distinct track.
Using tuple comparisons eliminates undefined as actual option from being problematic.

enhance: Improve type inference for getFetchKey

---

packages/experimental/src/rest/Resource.ts
packages/experimental/src/rest/__tests__/Resource.test.ts
packages/experimental/src/rest/__tests__/types.test.ts
packages/experimental/src/rest/types.ts

Writing custom endpoints is cumbersome....what if types could also be generated from urlRoot alone?
As long as urlRoot includes `as const`, our recursion type algorithm will automatically extract the relevant types and apply appropriately to all endpoints.
Note this relies on [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) which were introduced in [typescript 4.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html)
```tsx
class UserResource extends Resource {
readonly id: number | undefined = undefined;
readonly username: string = '';
readonly email: string = '';
readonly isAdmin: boolean = false;
pk() {
return this.id?.toString();
}
static urlRoot = 'http\\://test.com/groups/:group/users/:id?' as const;
} …
```

enhance: Infer parameter types from urlRoot

---

examples/github-app/src/pages/IssueDetail/CommentsList.tsx
examples/github-app/src/pages/IssueDetail/index.tsx
examples/github-app/src/pages/IssueList.tsx
examples/github-app/src/resources/BaseResource.ts
examples/github-app/src/resources/CommentResource.ts
examples/github-app/src/resources/IssueResource.tsx
examples/github-app/src/resources/ReactionResource.tsx
examples/github-app/src/resources/UserResource.ts
examples/github-app/src/routing/routes.tsx

Already using it but forgot that was the case.
Beautiful clean definitions:
```ts
import BaseResource from './BaseResource';
import UserResource from './UserResource';
export default class CommentResource extends BaseResource {
readonly id: number | undefined = undefined;
readonly issueUrl: string = '';
readonly htmlUrl: string = '';
readonly body: string = '';
readonly user: UserResource = UserResource.fromJS({});
readonly createdAt: Date = new Date(0);
readonly updatedAt: Date = new Date(0);
pk() {
return this.id?.toString();
}
static urlRoot =
'https\\://api.github.com/repos/:owner/:repo/issues/:number/comments' as const;
static schema = {
user: UserResource,
createdAt: Date,
updatedAt: Date,
};
}
```

fix: Update github example to use latest experimental Resource

---

packages/experimental/src/rest/__tests__/types.test.ts
packages/experimental/src/rest/types.ts

In case `as const` is missed we want to simply fallback to 'any' rather than breaking the types.
string fallback for ternary.

enhance: Better handle non-const urlRoot types

---

packages/rest-hooks/src/manager/DevtoolsManager.ts

While incredibly helpful, the addition of datetime serialization to devtools integration has added a noticeable performance cost in development mode. This cost is still small when devtools are desired but otherwise hinders developer's productivity.
https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#autopause
`autoPause` is a quick simple way to avoid this cost. In the future, we will want to integrate a solution that still *logs* the actions, without the cost of serializing and updating devtools itself.

enhance: autopause devtools by default

---

__tests__/new.ts
packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx
packages/core/src/react-integration/test-fixtures.ts

- Have one resource `CoolerArticleResource` and a resource that extends it (child) `EditorArticleResource`. 
- `EditorArticleResource` has schema ` { editor: UserResource }`
- `CoolerArticleResource.detail() receives `editor` unexpectedly as part of the server response for a given `id`
- Getting `EditorArticleResource.detail()` from cache errors.
```
TypeError: Cannot read properties of undefined (reading '[object Object]')
319 |             expiresAt = Math.min(
320 |               expiresAt,
> 321 |               state.entityMeta[key][pk].expiresAt,
|               ^
322 |             );
323 |           }),
324 |         );
```
- Upon fetching `EditorArticleResource.detail()`, from cache, existing entity should be normalized and returned without error. (@ntucker I'm confident on the …

Integration test for parent fetch of an attribute not present in its schema, but in one of its childen's schemas

---

__tests__/new.ts
packages/core/src/controller/Controller.ts
packages/core/src/react-integration/__tests__/__snapshots__/integration-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/integration-endpoint.web.tsx
packages/core/src/react-integration/test-fixtures.ts
packages/legacy/src/resource/__tests__/__snapshots__/Entity.test.ts.snap
packages/normalizr/src/denormalize.ts
packages/normalizr/src/entities/__tests__/Entity.test.ts
packages/normalizr/src/schemas/Polymorphic.ts
packages/normalizr/src/schemas/__tests__/Union.test.js
packages/normalizr/src/schemas/__tests__/__snapshots__/Union.test.js.snap

New [validation cycle](https://resthooks.io/docs/getting-started/validation#partial-results) means users are encouraged to use multiple distinct schemas for the same entity depending on endpoint.
This breaks previous invariant that denormalize path always applied to same normalize path, which could result in confusing bugs if not defined correctly. For instance, if a nested schema is not defined for a normalization path, but it ends up actually getting that field, then the denormalization will end up getting a value from the response - rather than processed id.
"partial denormalization" is already intended for support (as there are tests for it). However, this broke with the assumption id was a string in `unvisitEntity`. This is used for the global referential equality guarantee.
First …

enhance: Improve robustness when using distinct schemas to normalize/denormalize

---

packages/experimental/src/rest/__tests__/types.test.ts
packages/experimental/src/rest/types.ts

If \\: shows up after a real group those groups will be missed.

fix: urlRoot type inference handles escapes anywhere in string

---

packages/ssr/src/createPersistedStore.tsx

`ModuleNotFoundError: Module not found: Error: Can't resolve './ServerDataComponent' in '/home/ntucker/src/anansi/node_modules/@rest-hooks/ssr/lib'`
Our tooling with rename to include .js in import when using absolute paths.

fix: createPersistedStore import

---

packages/core/src/controller/__tests__/__snapshots__/getResponse.ts.snap
packages/core/src/controller/__tests__/getResponse.ts
packages/legacy/src/resource/__tests__/__snapshots__/normalizr.test.js.snap
packages/legacy/src/resource/__tests__/normalizr.test.js
packages/normalizr/src/__tests__/__snapshots__/index.test.js.snap
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/denormalize.ts
packages/normalizr/src/entities/__tests__/Entity.test.ts
packages/normalizr/src/schema.d.ts
packages/normalizr/src/schemas/Array.ts
packages/normalizr/src/schemas/ImmutableUtils.ts
packages/normalizr/src/schemas/Object.ts
packages/normalizr/src/schemas/Polymorphic.ts
packages/normalizr/src/schemas/Union.ts
packages/normalizr/src/schemas/Values.ts
packages/normalizr/src/schemas/__tests__/Array.test.js
packages/normalizr/src/schemas/__tests__/Object.test.js
packages/normalizr/src/schemas/__tests__/__snapshots__/Array.test.js.snap
packages/normalizr/src/schemas/__tests__/__snapshots__/Object.test.js.snap

```tsx
class MyItem extends Entity {
readonly createdAt: Date | undefined;
static schema = {
createAt: Date,
}
}
```
@WayneYe
- `null` and `undefined` are always considered valid from a network response
- 'required' fields should not default to either or users should specify a validate() method
- Greatly simplified logic as handling null and undefined in root denormalize
- `undefined` inputs short-circuit 'found' tracking since they should infer something other than undefined if we should recurse. Therefore any `undefined` value is considered not 'found'
While this technically changes behavior; We meticulously validated each change to prevent regressions. We are strongly certain that if the new behavior is different it means it is more of what a user wants. I.e., they get a result when it …

fix: Accept undefined or null responses for schema entries

---

packages/legacy/src/index.ts

fix: Missing import extension in legacy package

---

examples/todo-app/src/pages/Home/NewTodo.tsx
examples/todo-app/src/resources/PlaceholderBaseResource.ts
examples/todo-app/src/resources/TodoResource.ts

Best practices from latest @rest-hooks/rest version. Single arg create.

docs(example): Use single arg create from rest@5

---

website/src/mocks/init.js

Without the service worker installed; the live demos on the homepage will look broken as the network will error.
This seems to be the only way to ensure service worker is loaded - reloading page if it is not.
Taken from: https://stackoverflow.com/a/61432538

docs: Ensure mocking service worker is installed

---

.circleci/config.yml

Unit tests are hitting memory limit resulting in 75% flake rate: https://app.circleci.com/pipelines/github/coinbase/rest-hooks/7726/workflows/70fb2deb-2e1e-448e-a85f-efc91cc636be/jobs/47702/resources is a successful run after failure https://app.circleci.com/pipelines/github/coinbase/rest-hooks/7726/workflows/4d658d3e-72ca-48fd-8e3b-feb16a34b9c8/jobs/47701

internal: Upgrade unit test machine size to large

---

packages/ssr/src/ServerDataComponent.tsx
packages/ssr/src/createPersistedStore.tsx

When embedding a script; validity of that script can be checked against a nonce. Let's provide an option to provide that.

feat: Add nonce property for security in SSR

---

packages/core/src/react-integration/provider/BackupBoundary.tsx
packages/core/src/react-integration/provider/__tests__/backupboundary.node.tsx

Fixes #2037
To deal with Legacy react not rendering below suspense boundaries during SSR - we won't render them. However, this creates a hydration mismatch warning, so we need to identify this case client-side and change behavior appropriately.
Injecting scripts introduces all sorts of troubles with CSP; so we're just adding an element with a specific ID to detect the path.
I couldn't easily find a solution to actually test hydration - so I just tested the SSR node-side.

fix: Hydration mismatch in React 17

---

packages/core/src/react-integration/provider/BackupBoundary.tsx
packages/core/src/react-integration/provider/CacheProvider.tsx
packages/core/src/react-integration/provider/__tests__/backupboundary.node.tsx
packages/core/src/react-integration/provider/__tests__/provider.node.tsx

There is no case where context is updated in react 16/17 during an SSR cycle. So it doesn't make sense to use CacheProvider here - even when no suspense is used.
Also, adding actual elements in a provider is quite unexpected, which for instance led to the docs site having layout issues due to the nature of flexbox layout.
Log that they should use ExternalCacheProvider for the server-side rendering and remove special SSR handling. BackupBoundary is still used in ExternalCacheProvider but the hydration mismatch doesn't make any sense since server and client side have same DOM so I suspect it's a bug somewhere.
This is not a pure revert of #2039 as we maintain the test and used an alternative solution of warning about best usage patterns

enhance: Warn about CacheProvider usage for SSR

---

examples/github-app/package.json
examples/todo-app/package.json

stackblitz installs from sub directory thus ignoring yarn.lock. newer linaria is broken as well as incompatible with previous versions.
add resolutions that only run when installed from that directory

internal: Pin linaria sub-packages to make demos work in stackblitz

---

packages/core/package.json
packages/endpoint/package.json
packages/graphql/package.json
packages/legacy/package.json
packages/normalizr/package.json
packages/rest-hooks/package.json
packages/rest/package.json
packages/ssr/package.json
packages/test/package.json

Fixes #2060 .
Some recent version of something (maybe resolve package?) started not using node conditional and instead using the browser condition when jest tests are running.
Add require conditional as fallback after node to hit before reaching 'default'.

fix: package exports support for latest resolve pkg

---

.github/dependabot.yml

Still use security updates from dependabot - but we need commit messages to conform.
Using `open-pull-requests-limit: 0` will make dependabot only make security PRs

internal: Ensure security (only) updates have correct commit msg

---

.github/dependabot.yml

https://github.com/coinbase/rest-hooks/runs/7163388406
Annoyingly they don't tell you this in your PR only once master is corrupted

internal(fix): Add needed schedule field in dependabot.yml

---

website/src/components/Demo/CodeProvider.tsx
website/src/components/Playground/Result.tsx

https://github.com/facebook/docusaurus/pull/7660 Moved some exports we were using for our Playground component.
In the future we'll have to consider reworking this since these APIs are considered 'unstable'.
Larger docusaurus context: https://github.com/facebook/docusaurus/issues/6113

docs(fix): Update imports to reflect breaking changes in beta.22

---

packages/core/package.json
packages/endpoint/package.json
packages/graphql/package.json
packages/legacy/package.json
packages/normalizr/package.json
packages/rest-hooks/package.json
packages/rest/package.json
packages/ssr/package.json
packages/test/package.json

The [dual package hazard](https://nodejs.org/api/packages.html#dual-package-hazard) can cause issue if multiple imports occur that provide singletons like Symbols or React Context variables.
We currently solve this by pointing to commonjs from an ESM module. This works fine in node contexts because it is not considered that tree shaking is needed in this case.
However, [jest does not currently support ESM - only commonjs](https://github.com/coinbase/rest-hooks/issues/2060). Additionally in a recent update their jsdom environment will report only 'browser' condition to 'exports' fields. This means we must provide it with a commonjs module.
Previously we had simply adding a require condition to capture this case - but that introduced the dual package hazard for any non-node condition.
This …

fix: Ensure dual package hazard solved for non-node

---

examples/github-app/package.json
examples/todo-app/package.json
package.json
renovate.json
yarn.lock

Now a peerDep of anansi lint config since eslint doesn't allow plugins to be normal deps

internal: @typescript-eslint/eslint-plugin is needed for peerDep

---

packages/test/package.json
yarn.lock

fix(pkg): Missing @babel/runtime in deps list

---

examples/github-app/src/pages/IssueDetail/CommentForm.tsx
examples/github-app/src/pages/IssueDetail/CommentInline.tsx
examples/github-app/src/pages/IssueDetail/CreateComment.tsx
examples/github-app/src/pages/IssueDetail/CreateReaction.tsx
examples/github-app/src/resources/Reaction.tsx
examples/github-app/src/resources/Repository.tsx
packages/graphql/src/GQLEndpoint.ts
packages/graphql/src/__tests__/gql.ts

GQL can also have HTTP errors like REST
Steal logic from REST lib

enhance: Better handling of errors

---

examples/github-app/src/resources/Base.ts
examples/github-app/src/resources/Comment.ts
examples/github-app/src/resources/Event.tsx
examples/github-app/src/resources/Reaction.tsx
examples/github-app/src/resources/Repository.tsx
examples/github-app/src/resources/User.ts
packages/experimental/src/rest/RestEndpoint.d.ts
packages/experimental/src/rest/RestEndpoint.js
packages/experimental/src/rest/RestHelpers.ts
packages/experimental/src/rest/__tests__/Resource.test.ts
packages/experimental/src/rest/__tests__/RestEndpoint.ts
packages/experimental/src/rest/__tests__/createResource.test.ts
packages/experimental/src/rest/createResource.ts
packages/experimental/src/rest/types.ts

BREAKING CHANGE: urlRoot -> path
More canonical name for url construction pattern like this. urlRoot only makes sense when it's a base url that is extended, rather than specifying patterns

enhance: urlRoot -> path

---

examples/benchmark/package.json
examples/github-app/package.json
examples/normalizr-github/package.json
examples/normalizr-redux/package.json
examples/normalizr-relationships/package.json
examples/todo-app/package.json
packages/core/package.json
packages/endpoint/package.json
packages/experimental/package.json
packages/graphql/package.json
packages/hooks/package.json
packages/img/package.json
packages/legacy/package.json
packages/normalizr/package.json
packages/rest-hooks/package.json
packages/rest/package.json
packages/ssr/package.json
packages/test/package.json
packages/use-enhanced-reducer/package.json
yarn.lock

Fixes #2178 .
react-native uses the 'main' field of package.json (at least in older versions). However, the commonjs builds sometimes did weird things with require in this environment.
Using es6 works best, and can be done with legacy metro setups by specifying a "react-native" field in the package.json.
Most likely future bundlers for RN will use 'exports' field and thus not have this problem.

fix: React native to use es6 modules

---

__tests__/new.ts
docs/rest/usage.md
packages/core/src/controller/__tests__/fetch.tsx
packages/core/src/react-integration/__tests__/integration-optimistic-endpoint.web.tsx
packages/rest/src/RestEndpoint.d.ts
packages/rest/src/__tests__/RestEndpoint.ts

We can extrapolate the denormalized type from schema, but there is currently no way to set the return type of fetch, which will often be slightly different.
```ts
const getArticle = new RestEndpoint({
path: 'http\\://test.com/article-cooler/:id',
process(value): ArticleInterface {
return value;
},
});
```
Now when we simply call the function we will get autocomplete.
```ts
const article = await getArticle({ id: '5' });
```
This can also be useful in mutations when doing something with the result
```ts
const newArticle = controller.fetch(createArticle, { title: 'yay' });
router.push(`/article/${newArticle.id}`);
```

enhance: Use process() option to infer return type of RestEndpoint

---

docs/rest/api/RestEndpoint.md
docs/rest/api/createResource.md
packages/rest/src/RestEndpoint.d.ts
packages/rest/src/__tests__/RestEndpoint.ts
packages/rest/src/hookifyResource.ts
packages/rest/src/index.ts
website/src/components/Demo/index.js

Fixes #2215
Turns out this is easier than trying to ban 'body' without 'path'.
I realized I can easily infer urlParams since it's either there or not
Let's also make the docs more clear about how to set types using the parameters

enhance: Allow body-only RestEndpoint.extend()

---

packages/endpoint/src/schemas/Entity.ts
packages/normalizr/src/__tests__/inferResults.ts

Supporting non-object arguments for an endpoint like so:
```ts
const data = useSuspense(getThing, id);
```
Longer:
```ts
const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))
class Item extends Entity {
readonly id: string = ''
readonly name: string = ''
public pk() {
console.log('creating item with id', this.id)
return this.id
}
}
const listEndpoint = new Endpoint(
async () => {
console.log('fetching items')
await delay(1000)
return [
{ id: 'A', name: 'Name A' },
{ id: 'B', name: 'Name B' },
{ id: 'C', name: 'Name C' },
]
},
{
name: `${Item.name}.getList`,
schema: [Item],
},
)
const detailEndpoint = listEndpoint.extend({
async fetch(id: string) {
console.log('fetching item', id)
await delay(500)
return { id, name: `Name ${id}` }
},
name: `${Item.name}.getById`, …
```

feat: Support infer for Endpoints with string or number args

---

docs/graphql/api/Array.md
docs/graphql/api/Entity.md
docs/graphql/api/Object.md
docs/graphql/api/Union.md
docs/graphql/api/Values.md
docs/rest/api/Array.md
docs/rest/api/Endpoint.md
docs/rest/api/Entity.md
docs/rest/api/Object.md
docs/rest/api/RestEndpoint.md
docs/rest/api/Union.md
docs/rest/api/Values.md
docs/rest/guides/rpc.md
website/yarn.lock

Github and [docuarus added support for mermaid](https://github.com/facebook/docusaurus/pull/7490). These diagrams allow svg demonstrations. They aren't super pretty but make it easy to get the point across. Lifecycle explanations was originally brought up by @sweetro as one of the most useful docs to add that was missing.
Also included updates to schema pages
- https://resthooks.io/rest/api/Array
- https://resthooks.io/rest/api/Object
- https://resthooks.io/rest/api/Union
- https://resthooks.io/rest/api/Values
- https://resthooks.io/rest/api/Entity

docs: Add control flow diagrams

---

packages/core/src/controller/Controller.ts
packages/core/src/react-integration/__tests__/__snapshots__/hooks-endpoint.web.tsx.snap
packages/core/src/react-integration/__tests__/hooks-endpoint.web.tsx
packages/core/src/react-integration/provider/CacheStore.tsx
packages/rest-hooks/src/react-integration/provider/ExternalCacheProvider.tsx

Fixes #1468 .
Imperative handlers sometimes need context to choose their next behavior. It's critical we don't lock this into the React lifecycle as that is an antipattern (the useEffect-trap) - not just annoying from a coding perspective.
We already have imperative access with middlewares, so use the same function to provide to controller.
It's important we do not hide [getState()](https://resthooks.io/docs/api/Controller#getState) inside any accessors, as it is critical to understand where state comes from so it always represents the expected value.
```ts
const controller = useController();
const updateHandler = useCallback(async (updatePayload) => {
const response = controller.fetch(MyResource.update, { id }, updatePayload);
const denormalized = …
```

feat: Add Controller.getState()

---

docs/rest/api/RestEndpoint.md
packages/rest/src/RestEndpoint.d.ts
packages/rest/src/__tests__/RestEndpoint.ts
website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
website/yarn.lock

Same functionality as `body` for the searchParams.
Add type only argument to RestEndpoint construction and .extends() arguments.

enhance: Add searchParams arg for RestEndpoint typing

---

packages/react/src/hooks/__tests__/useLive.tsx
packages/react/src/hooks/useLive.ts

Specialization: It's fairly common to want polling when also getting the data.
Add new hook so the behaviors can still be separated if needed.

feat: Add useLive()

---

README.md
docs/core/README.md
docs/core/api/LogoutManager.md
docs/core/api/Manager.md
docs/core/api/NetworkManager.md
docs/core/guides/ssr.md
docs/core/upgrade/upgrading-to-5.md
docs/core/upgrade/upgrading-to-6.md
docs/core/upgrade/upgrading-to-7.md
packages/react/README.md
packages/rest-hooks/README.md
website/src/components/Playground/MonacoPreloads.tsx
website/src/pages/demos.tsx
website/versioned_docs/version-7.0/upgrade/upgrading-to-5.md
website/yarn.lock

Googlebot has limited download resources. Since we SSR everything blocking it from loading the JS saves a lot of resources, avoiding quota limits that cause inconsistent 'mobile usability' issues. When quota limits are hit google simply stops mid-way through, but still evaluates the page, which means random resources aren't loaded. This potentially also allows googlebot to crawl pages with more frequency.
- Fix NextJS demo tabs
- Add feature bullets to README
- Execute monaco preloads as client-side javascript only for non-bots
- Fix website/yarn.lock
- Fix upgrade links

docs: Lots of fixes

---

packages/graphql/src/GQLEndpoint.ts
packages/rest/src/RestEndpoint.js
packages/rest/src/__tests__/RestEndpoint.ts

These are potentially recoverable so we want to retry when that logic is added, but also keep existing data if it is still valid.
Change artificial status from 400 to 500

fix: Network down/ CORS errors should be 'soft' by default

---

packages/react/src/components/CacheStore.tsx
packages/react/src/components/__tests__/provider.tsx

User-land managers might call dispatchers after unmount. Forcing users to think about this is unnecessary complexity and learning curve.
Simply ignore them. In dev mode we will log at debug level as this is not considered a bug. But it may be useful if one is expecting dispatches to know where they went.

enhance: Block dispatches after unmount

---

.github/ISSUE_TEMPLATE/bug_report.md
docs/core/api/AsyncBoundary.md
docs/core/api/Manager.md
docs/core/api/SubscriptionManager.md
docs/core/api/useDLE.md
docs/core/api/useError.md
docs/core/api/useFetch.md
docs/core/getting-started/installation.md
docs/graphql/auth.md
docs/rest/guides/auth.md
docs/rest/guides/computed-properties.md
packages/react/src/__tests__/integration-endpoint.web.tsx
website/docusaurus.config.js
website/src/components/Demo/index.js
website/src/pages/index.js
website/static/robots.txt

#2295 was supposed to have robots.txt but that was somehow lost on the final commit.
Various other docs tweaks
Googlebot has limited download resources. Since we SSR everything blocking it from loading the JS saves a lot of resources, avoiding quota limits that cause inconsistent 'mobile usability' issues. When quota limits are hit google simply stops mid-way through, but still evaluates the page, which means random resources aren't loaded. This potentially also allows googlebot to crawl pages with more frequency.

docs: Random improvements and robots.txt again

---

__tests__/new.ts
docs/core/README.md
docs/core/api/Controller.md
docs/core/api/DevToolsManager.md
docs/core/api/LogoutManager.md
docs/core/api/PollingSubscription.md
docs/core/api/SubscriptionManager.md
docs/rest/api/RestEndpoint.md
packages/rest/src/RestEndpoint.d.ts
packages/rest/src/__tests__/RestEndpoint.ts
website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
website/yarn.lock

This was a very weird limitation that could lead to confusing behavior.
Because path is a key of RestInstance, we were excluding its specifics from being intersected with the type, which meant
it was always string. This meant we did not have access to the specific path to reconstruct when combined with other parameters.
Track in types path, body, and searchParams, to make it easy to compute new function types based on previous values.

enhance: Allow extend({searchParams}) without path arg

---

docs/core/README.md
docs/core/api/Controller.md
docs/core/api/Manager.md
docs/core/api/useCache.md
docs/core/api/useController.md
docs/core/api/useDLE.md
docs/core/api/useFetch.md
docs/core/api/useSuspense.md
docs/core/guides/debugging.md
examples/benchmark/reducer.js
packages/core/src/controller/Controller.ts
packages/react/src/components/__tests__/provider.tsx
packages/react/src/hooks/__tests__/useController/receive.tsx
packages/test/src/mockState.ts
website/yarn.lock

Way better names. Following naming convention of 'getResponse' and 'getError'
receive -> setResponse
receiveError -> setError
Mark TODO to deprecate previous names in next sem major. Otherwise, both will continue to exist.

feat: Add ctrl.setResponse, ctrl.setError

---

packages/rest/src/__tests__/RestEndpoint.ts
packages/rest/src/paginationUpdate.ts
packages/rest/src/test-fixtures.ts

Fixes #2353 .
Paginated requires getting the updated cursor, not the first page cursor
Based on the [previous docs ](https://resthooks.io/docs/6.3/guides/infinite-scrolling-pagination) we need to be simply using the new results to completely replace other values like the cursor

fix: paginated() should replace all results to ensure updated cursor

---

docs/core/api/useCancelling.md
packages/hooks/package.json
packages/hooks/src/useCancelling.ts
packages/hooks/src/useDebounce.ts
yarn.lock

@rest-hooks/endpoint is no longer installed as standard top level library since splitting normalizr implementations and consumption.
We have a dep of @rest-hooks/normalizr instead, which is used for consumers like @rest-hooks/react hooks. Since we only use its types it won't increase bundle size.

enhance: Remove @rest-hooks/endpoint peerDep for /hooks

---

examples/todo-app/src/index.tsx
packages/core/CHANGELOG.md
packages/core/package.json
packages/endpoint/CHANGELOG.md
packages/endpoint/package.json
packages/graphql/CHANGELOG.md
packages/graphql/package.json
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/legacy/CHANGELOG.md
packages/legacy/package.json
packages/normalizr/CHANGELOG.md
packages/normalizr/package.json
packages/react/CHANGELOG.md
packages/react/README.md
packages/react/package.json
packages/react/src/components/CacheStore.tsx
packages/react/src/components/__tests__/provider.tsx
packages/rest-hooks/CHANGELOG.md
packages/rest-hooks/README.md
packages/rest-hooks/package.json
packages/rest/CHANGELOG.md
packages/rest/package.json
packages/use-enhanced-reducer/CHANGELOG.md
packages/use-enhanced-reducer/package.json
packages/use-enhanced-reducer/src/useEnhancedReducer.ts
yarn.lock

https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state
React 18 StrictMode calls useEffect callback twice; making it look like the component unmounted before it did.
All sideeffects done in unmount must be reapplied on useEffect mount. Currently our dispatch is asymetric.

fix: Compatibility with React 18 StrictMode

---

docs/rest/api/Query.md
packages/endpoint/src/queryEndpoint.ts
packages/endpoint/src/schemas/__tests__/Query.test.ts
packages/endpoint/src/schemas/__tests__/__snapshots__/Query.test.ts.snap
website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts
website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
website/yarn.lock

Aggregates should have the same advantage of both
- centralized definition
- centralized memoization
Alter schema type based on process return value

feat: Allow arbitrary return types for Query

---

__tests__/new.ts
docs/core/api/Controller.md
docs/core/api/LogoutManager.md
packages/core/src/actionTypes.ts
packages/core/src/controller/Controller.ts
packages/core/src/controller/createInvalidateAll.ts
packages/core/src/newActions.ts
packages/core/src/previousActions.ts
packages/core/src/state/createReducer.ts
packages/react/src/hooks/__tests__/useController/invalidateAll.tsx
website/docusaurus.config.js
website/sidebars.json
website/yarn.lock

Fixes #1548 (the @stufisher part).
- Easily reset part of cache (when logout but only some endpoints use that auth)
- Easily invalidate all results matching an endpoint (every possible arg)
```ts
controller.invalidateAll(CoolerArticleResource.get)
```
```ts
controller.invalidateAll({
testKey(key: string) {
return /\/users\/([\w\W]+)\/photo/.test(key);
}
});
```
We still plan on adding an atomic mutation solution for #1548 - enabling a more performant and automatic answer to this use case of not knowing all parameters that are relevant

feat: Add controller.invalidateAll()

---

__tests__/new.ts
packages/core/src/controller/types.ts
packages/experimental/src/types.ts
packages/react/src/hooks/__tests__/useDLE.tsx
packages/react/src/hooks/__tests__/useLive.tsx
packages/react/src/hooks/types.ts
packages/react/src/hooks/useCache.ts
packages/react/src/hooks/useDLE.ts
packages/react/src/hooks/useLive.ts
packages/react/src/hooks/useSuspense.native.ts
packages/react/src/hooks/useSuspense.ts
packages/rest/src/RestEndpoint.d.ts
packages/rest/src/__tests__/RestEndpoint.ts
packages/rest/src/__tests__/types.test.ts
packages/rest/src/createResource.ts
packages/rest/src/index.ts
tsconfig-base.json
website/docusaurus.config.js
website/src/components/Demo/index.js

`strictNullChecks: false` should result in looser types, not broken types.
null unions as args to useSuspense don't properly unionize nullability.
GetEndpoint, MutateEndpoint did not previously set the path, searchParams, body values used by .extends() to keep extension types precise.
- hooks:
- schema should be ignored with both `null` and `undefined`
- schema extends `null` | `undefined` works even with strictNullChecks (schema extends Schema does not)
- REST
- Use strictNullChecks detection when generating function parameters to make more flexible type
For some reason for a union type to properly run through each case in a conditional, it must be a separated type instead of inline. So we add `CondNull`
```ts
export type CondNull<P, A, B> = P extends null ? A : B;
```
Add …

enhance: Improve strictNullChecks: false compatibility

---

packages/rest/src/RestEndpoint.d.ts
packages/rest/src/__tests__/createResource.test.ts

Fixes #2330 .
The previous heuristic fails in certain edge cases. Now that we track the components reliably, simply use existing path to recompute function arguments.

fix: Typing when using .extend({body}) with no path

---

packages/react/src/__tests__/integration-optimistic-endpoint.web.tsx

- act does not need to wrap promise resolves as setResponse is already always wrapped
- use test hook return value controller

internal: Improve usage of act in optimistic test

---

.github/workflows/benchmark.yml
docs/graphql/api/Entity.md
docs/rest/api/Entity.md
docs/rest/diagrams/_entity_lifecycle.mdx
examples/benchmark/README.md
packages/endpoint/src/interface.ts
packages/endpoint/src/schemas/Entity.ts
packages/endpoint/src/schemas/__tests__/legacy-compat/Entity.test.ts
packages/endpoint/src/schemas/__tests__/legacy-compat/__snapshots__/Entity.test.ts.snap
packages/endpoint/src/schemas/__tests__/legacy-compat/denormalize.ts
packages/normalizr/src/__tests__/normalizerMerge.test.tsx
packages/normalizr/src/interface.ts
website/src/components/Playground/editor-types/@rest-hooks/core.d.ts
website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts
website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts
website/src/components/Playground/editor-types/@rest-hooks/normalizr.d.ts
website/src/components/Playground/editor-types/@rest-hooks/react.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
website/src/components/Playground/editor-types/rest-hooks.d.ts
website/yarn.lock

Faster is more better
After adding a launch profile and asking ChatGPT - I was able to produce a cpu profile.
Wrapping unvisit is not only awkward, it makes v8 not optimize the function, which is called often. While profiling this was in the top 7 in self-time.
> Benchmarks consistently show about a <strike>30%</strike> 10% performance increase for denormalize step
The original intent was to reduce the surface area of the interface between entity and denormalize/normalize. However, this is deceptive as it's still exposing an interface in that weird unvisit object. Since unvisit is exposed to other schemas, not just entity this could be considered an even larger surface areas as well.
To make it more clear we introduce a new lifecycle which allows us to go back to the [original …

feat: Entity.createIfValid() lifecycle

---

docs/rest/README.md
docs/rest/api/Endpoint.md
docs/rest/api/Entity.md
examples/github-app/src/resources/Base.ts
examples/github-app/webpack.config.js
examples/nextjs/pages/api/ExchangeRates.ts
examples/todo-app/src/resources/TodoResource.ts
examples/todo-app/src/resources/UserResource.ts
packages/endpoint/src/endpoint.js
packages/endpoint/src/schemas/Entity.ts
website/src/pages/errors/dklj.tsx
website/src/pages/errors/osid.tsx

Commonly minification programs like terser will change class names to something shorter. However, this can cause issues when using `this.name` to generate easy keys (like in Entity and Endpoint).
- The risk of collisions increases since these become very short words
- There will be serialization mismatches in SSR if the server side code does not also mangle in the exact same way (they usually don't at all)
We can run detection upon Entity static class creation. We know the name *should* be Entity, so this comparison will detect the issue. If so we will override the default implementation with a console.error.
```ts
static {
if (this.name !== 'Entity') {
Object.defineProperty(this, 'key', {
get() {
console.error('Rest Hooks Error: https://resthooks.io/errors/dklj');
return this.name;
}, …
```

enhance: Alert users of class mangling issues

---

__tests__/new.ts
docs/core/concepts/validation.md
docs/core/getting-started/endpoint.md
docs/core/guides/ssr.md
docs/graphql/api/Entity.md
docs/rest/README.md
docs/rest/api/Entity.md
docs/rest/guides/summary-list.md
examples/benchmark/schemas.js
examples/github-app/src/resources/Repository.tsx
examples/nextjs/pages/api/ExchangeRates.ts
examples/todo-app/src/resources/TodoResource.ts
examples/todo-app/src/resources/UserResource.ts
packages/endpoint/src/schemas/Entity.ts
website/graphql_versioned_docs/version-0.2/api/Entity.md
website/src/components/Playground/editor-types/@rest-hooks/core.d.ts
website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts
website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
website/yarn.lock

Promotes less verbose best practices
```ts
static get key() {
return 'CoolerArticle';
}
```
<
```ts
static key = 'CoolerArticle';
```
Previously this was not possible for code executing in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode). To enable this, we will also define a setter
We could define the getter and setter in normal class definition - however, we still need to do class mangling detection in the class static block. Therefore, we just decide to put everything there.

feat: Allow direct assignment to Entity.key

---

packages/img/package.json
yarn.lock

Now people don't have to manually install [@rest-hooks/endpoint](https://www.npmjs.com/package/@rest-hooks/endpoint)
[@rest-hooks/endpoint](https://www.npmjs.com/package/@rest-hooks/endpoint) moved from peerDeps to deps

enhance: Make endpoint a normal dep

---

docs/rest/api/Endpoint.md
packages/endpoint/src/__tests__/__snapshots__/endpoint.ts.snap
packages/endpoint/src/__tests__/endpoint.ts
packages/endpoint/src/endpoint.js
website/src/pages/errors/osid.tsx

Earlier visibility into potential key issues.
- log when Endpoint autonaming fails. Only do this if key is not overridden. (So we know it relies on name)
- Add `name` option to docs
- Update mangling detection for Endpoint to use function mangling, as name is based on a function name, not the class name.

enhance: Improve autonaming failure detection for Endpoint

---

packages/endpoint/src/CSP.js
packages/endpoint/src/__tests__/__snapshots__/endpoint.ts.snap
packages/endpoint/src/__tests__/endpoint.ts
packages/endpoint/src/endpoint.js
packages/rest/src/RestEndpoint.js
packages/rest/src/__tests__/RestEndpoint.ts

`name` can be great for logging or debugging purposes, so having better defaults is beneficial.
Note: Resources still have `Resource.method` naming convention
Set default option if name is not provided to options.urlPrefix + options.path
To make things callable, we force every instance to be constructed as a function
Because of this the name property will be autoset
To create a usable naming inheritance pattern, we use __name as a proxy.
Every instance then overrides the name property.
For protocol specific extensions that wish to customize default naming
behavior, be sure to add your own `Object.defineProperty(self, 'name'`
in your constructor to override this one.

enhance: Default RestEndpoint name based on url path

---

packages/endpoint/src/schemas/Entity.ts

Less object crowding; more performance
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#smart_self-overwriting_lazy_getters
```ts
const obj = {
get notifier() {
delete this.notifier;
this.notifier = document.getElementById("bookmarked-notification-anchor");
return this.notifier;
},
};
```
We apply this to Entity.defaults
We had to slightly alter the pattern to use `Object.defineProperty` for assignment, since the object we are operating on might be a descendant of the original getter.

enhance: Use self-overwriting memoization pattern

---

packages/endpoint/src/schemas/Entity.ts

Get rid of extraneous `__` member variables
Similar to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#smart_self-overwriting_lazy_getters, but adapted for only running sideeffects once (console.error)

enhance: Use self-overwriting pattern to limit error spam

---

packages/endpoint/src/schemas/Entity.ts
packages/endpoint/src/schemas/__tests__/Entity.test.ts
website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts
website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
website/src/components/Playground/editor-types/rest-hooks.d.ts

The pattern from https://github.com/data-client/rest-hooks/pull/2437 only works if there are no descendants. However, we want to allow users to add more defaults with children entities. For instance, having a base class for their whole API, base class for Unions, or simply having partial fields sometimes.
Revert #2437, but also add tests to ensure we cover this case, as the bug will only be triggered with multiple calls in the inheritance chain.

fix: Entity.defaults should work with inheritance

---

packages/core/src/controller/Controller.ts
packages/core/src/controller/__tests__/getResponse.ts
packages/legacy/src/resource/__tests__/__snapshots__/Delete.test.ts.snap
packages/legacy/src/resource/__tests__/__snapshots__/Entity.test.ts.snap
packages/legacy/src/resource/__tests__/__snapshots__/normalizr.test.js.snap
packages/legacy/src/resource/__tests__/normalizr.test.js
packages/normalizr/src/WeakEntityMap.ts
packages/normalizr/src/__tests__/WeakEntityMap.test.ts
packages/normalizr/src/denormalize.ts
packages/normalizr/src/index.ts
packages/normalizr/src/types.ts

The improved caching in #2444, caused localEntities to not be filled out when the result cache was used. This was previously used to determine what entities should be used to determine expiresAt in the case that an endpoint doesn't have its own meta (its results were inferred).
We should ensure this is computed properly even in cached case - added a test to reflect this condition.
Since we're already computing a path list for dependencies, we can simply store that in our cache and use that to do entityMeta lookups, rather than returning the full local cache list.

fix: Correct `expiresAt` computation when cached + inferred results

---

examples/benchmark/normalizr.js
packages/core/src/controller/Controller.ts
packages/core/src/controller/__tests__/getResponse.ts
packages/endpoint/src/schemas/__tests__/All.test.ts
packages/endpoint/src/schemas/__tests__/Entity.test.ts
packages/endpoint/src/schemas/__tests__/denormalize.ts
packages/legacy/src/resource/__tests__/Entity.test.ts
packages/legacy/src/resource/__tests__/normalizr.test.js
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/denormalize.ts
packages/normalizr/src/types.ts
website/src/components/Playground/editor-types/@rest-hooks/core.d.ts
website/src/components/Playground/editor-types/@rest-hooks/normalizr.d.ts

Since we already key on the endpoint in result cache, it is unnecessary to key on schema as well as it is assumed schema will not change.
This was previously reasoned about incorrectly as the tests were in normalizr rather than core. `core` is where the endpoint key splitting is, so I wasn't thinking about that already existing.
Remove complexities around WeakMap for schemas; use WeakEntityMap as resultCache argument to denormalize

enhance: Do not key on schema in result cache

---

docs/core/api/MockResolver.md
docs/core/api/makeRenderRestHook.md
docs/rest/guides/optimistic-updates.md
packages/test/src/MockResolver.tsx
packages/test/src/collapseFixture.ts
packages/test/src/createControllerInterceptor.tsx
packages/test/src/fixtureTypes.ts
packages/test/src/makeRenderRestHook/index.tsx
packages/test/src/mockState.ts
website/src/components/HooksPlayground.tsx
website/src/components/Playground/Preview.tsx
website/src/components/Playground/PreviewWithHeader.tsx
website/src/components/Playground/PreviewWithScope.tsx
website/src/components/Playground/index.tsx
website/yarn.lock

To provide more realistic mocking scenarios, it's critical that operations are able to reflect server state updates. This is necessary when the proper simulated response cannot be computed simply from the request sent, but also requires an understanding of previous requests.
For instance, on the docs site, the [server timing variation example](https://resthooks.io/rest/guides/optimistic-updates#server-timings) will not work without persisting counter state.
The state should be tracked per mocking instance, thus we need to send an object that can be mutated. `this` seems like an intuitive case as the interceptor is operating on the mocking instance.

feat: Interceptor response 'this' can be used to track 'server state'

---

packages/normalizr/src/__tests__/normalizerMerge.test.tsx
packages/normalizr/src/normalize.ts

Simplify a lot of complex conditional logic
When operating on a full store like @rest-hooks/core does; entityMeta will always exist if an entity does. However, we still want to never crash even if weird things happen. By extracting this case to one condition we can 'hoist' the complexity to only one split point.
If entityMeta doesn't exist, then we don't need reasoning around how to merge with entity - simply replace. For those possibly using normalizr without such an enforcement; they will get the behavior that would exerted without a persistent store anyway - as there is no expectations of existing entity tracking.
Remove `mergeWithStore` undefined possibility in Endpoint implementation. This complexity will not be needed when using updated versions of rest-hooks

enhance: Only use mergeWithStore logic when entityMeta exists

---

packages/normalizr/src/normalize.ts

https://www.measurethat.net/Benchmarks/Show/23731/0/arrayisarray-vs-truthy
index can only be undefined or an array - therefore this check is equivalent, but much faster and less code

enhance: Optimize index check in normalize

---

packages/core/src/controller/Controller.ts
packages/experimental/src/hooks/useSubscription.tsx
packages/normalizr/src/endpoint/EndpointInterface.ts
packages/react/src/hooks/types.ts
packages/react/src/hooks/useCache.ts
packages/react/src/hooks/useDLE.ts
packages/react/src/hooks/useFetch.native.ts
packages/react/src/hooks/useFetch.ts
packages/react/src/hooks/useLive.ts
packages/react/src/hooks/useSubscription.native.tsx
packages/react/src/hooks/useSubscription.tsx
packages/react/src/hooks/useSuspense.native.ts
packages/react/src/hooks/useSuspense.ts
packages/rest-hooks/src/hooks/useCache.ts
packages/rest-hooks/src/hooks/useError.ts
packages/rest-hooks/src/hooks/useSubscription.ts

Besides being kind of weird to have `undefined` as a specific type - `undefined` can behave quite weirdly in typescript. For instance, in non-strict mode it won't even be a type.
We first allow `undefined` in all consumers. Eventually we'll migrate to using booleans for definitions.

enhance: Allow 'false' as Endpoint.sideEffect

---

packages/endpoint/src/schemas/EntitySchema.ts
packages/endpoint/src/schemas/__tests__/EntitySchema.test.ts
packages/endpoint/src/schemas/__tests__/__snapshots__/EntitySchema.test.ts.snap
packages/rest/src/__tests__/__snapshots__/RestEndpoint.ts.snap

Eliminate need for extends if people don't want to use it.
Supported options:
```ts
| 'process'
| 'merge'
| 'expiresAt'
| 'createIfValid'
| 'mergeWithStore'
| 'validate'
| 'shouldReorder'
| 'useIncoming'
```
```ts
class EntriesEntity extends schema.Entity(Entries, {
schema: {
data: { attachment: AttachmentsEntity },
},
process(input, parent, key) {
return {
...values(input)[0],
type: Object.keys(input)[0],
};
},
}) {}
```

feat: Add Entity lifecycle overrides to mixin options

---

packages/core/src/manager/DevtoolsManager.ts
packages/core/src/manager/devtoolsTypes.ts

People might want to use it in production. This allows them to manually add it.
It is still defaulted in managers list based on dev/prod env.
Remove `process.env.NODE_ENV` condition in manager itself; dynamic import to add to defaults

enhance: Allow DevToolsManager in prod

---

docs/core/api/Fixtures.md
docs/core/api/types.md
docs/core/api/useController.md
docs/rest/guides/optimistic-updates.md
docs/rest/guides/relational-data.md
packages/core/src/middlewareTypes.ts
packages/core/src/newActions.ts
packages/react/src/components/CacheProvider.tsx
packages/test/src/collapseFixture.ts
packages/test/src/createControllerInterceptor.tsx
packages/test/src/fixtureTypes.ts
packages/test/src/mockState.ts
website/src/components/Playground/FixturePreview.tsx
website/src/components/Playground/editor-types/@rest-hooks/core.d.ts
website/src/mocks/handlers.js
website/yarn.lock

Follow up to #2380
When you want to still run other parts of an endpoint's fetch preparation like [getRequestInit()](https://resthooks.io/rest/api/RestEndpoint#getRequestInit)
Add new Interceptor type, and make Interceptor a union of this and old type.
```ts
interface FetchInterceptor<
T = any,
E extends EndpointInterface & {
update?: Updater;
testKey(key: string): boolean;
fetchResponse(input: RequestInfo, init: RequestInit): Promise<Response>;
extend(options: any): any;
} = EndpointInterface & {
testKey(key: string): boolean;
fetchResponse(input: RequestInfo, init: RequestInit): Promise<Response>;
extend(options: any): any;
},
> {
readonly endpoint: E;
fetchResponse(this: T, input: RequestInfo, init: RequestInit): ResolveType<E>;
/** Number of miliseconds (or function that returns) to …
```

feat: Add FetchInterceptor - a lower-level interceptor

---

packages/hooks/src/__tests__/useLoading.tsx
packages/hooks/src/useLoading.ts
packages/redux/src/ExternalCacheProvider.tsx

Fixes #2484 .
https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state
React 18 StrictMode calls useEffect callback twice; making it look like the component unmounted before it did.
We did this properly for CacheProvider in #2361
This add compat to
- hooks package (useLoading)
- ExternalCacheProvider (in redux pkg)
Reset refs to initial conditions in the first useeffect block
Thanks to @d7sd6u for not only a great bug report but the solution

fix: StrictMode compatibility

---

.circleci/config.yml
examples/github-app/src/resources/Base.ts
packages/rest/src/RestEndpoint.d.ts

Some people don't set strict settings
Test examples folder based on this setting with CLI. This ensures we only validate acceptance, rather than rejection

enhance: Improve types with null checks off

---

.circleci/config.yml

Why test twice. Previously we tested react 17, and then also tested react 17 while reporting coverage.
Now, let's just detect the 17 version and report coverage when we hit that case.

internal(CI): Integrate coverage into unit test matrix

---

.circleci/config.yml

Faster CI. If a test doesn't use react, it doesn't need to be run more than once for each version of react.
Only run all tests for the codecoverage as this must do them all to get accurate coverage.
Note we still include `packages/rest` because it does have some (limited) react references in its tests.

internal(test): React test matrix - only target react tests

---

.changeset/spicy-yaks-drive.md
.circleci/config.yml
.yarnrc.yml
examples/github-app/package.json
examples/todo-app/package.json
package.json
packages/test/package.json
yarn.lock

When we moved build patterns missed updating the .cjs specific versions

fix: .cjs should be in commonjs format

---

package.json
packages/core/package.json
packages/endpoint/package.json
packages/experimental/package.json
packages/graphql/package.json
packages/hooks/package.json
packages/img/package.json
packages/legacy/package.json
packages/normalizr/package.json
packages/react/package.json
packages/redux/package.json
packages/rest-hooks/package.json
packages/rest/package.json
packages/ssr/package.json
packages/test/package.json
packages/use-enhanced-reducer/package.json
yarn.lock

Found out about https://yarnpkg.com/getting-started/qa#how-to-share-scripts-between-workspaces
This allows us to centralize all dev deps used in scripts to the root, as well as shared options.
```json
{
"dependencies": {
"typescript": "^3.8.0"
},
"scripts": {
"g:tsc": "cd $INIT_CWD && tsc"
}
}
```
```json
{
"scripts": {
"build": "yarn g:tsc"
}
}
```

internal: Centralize common scripts

---

packages/core/package.json
packages/endpoint/package.json
packages/experimental/package.json
packages/graphql/package.json
packages/hooks/package.json
packages/img/package.json
packages/legacy/package.json
packages/react/package.json
packages/redux/package.json
packages/rest-hooks/package.json
packages/rest/package.json
packages/ssr/package.json
packages/test/package.json
packages/use-enhanced-reducer/package.json

prepublishOnly is run *before* prepack, so we need to change the order.
put everything in prepack. this will make bundle builds run on git installs as well which is probably desirable

internal: Fix publish scripts

---

.changeset/calm-taxis-beam.md
.changeset/rude-pets-kick.md
packages/core/src/manager/NetworkManager.ts
packages/core/src/manager/PollingSubscription.ts
packages/core/src/manager/__tests__/__snapshots__/pollingSubscription-endpoint.ts.snap
packages/core/src/manager/__tests__/pollingSubscription-endpoint.ts
packages/experimental/src/hooks/__tests__/subscriptions.tsx
packages/hooks/src/__tests__/useCancelling.ts
packages/react/src/__tests__/subscriptions-endpoint.tsx
packages/react/src/hooks/__tests__/subscriptions.native.tsx
packages/react/src/hooks/__tests__/subscriptions.tsx
packages/react/src/hooks/__tests__/useLive.tsx
packages/test/src/makeRenderRestHook/index.tsx

Mostly because clear interval is flaky when mocking timers. However, we can at least detect weird edge cases more easily.
In case the intervalId is undefined, we warn instead of doing an update fetch

fix: Improve subscription edge case handling

---

.changeset/breezy-coins-think.md
.changeset/proud-dingos-fold.md
packages/core/src/manager/NetworkManager.ts
packages/test/src/makeRenderRestHook/index.tsx

We used nm.allSettled() being falsy (undefined) to indicate we can complete suspense. Therefore, we must return undefined rather than a promise when there are no fetches in flight.
This reverts part of #2540

fix: SSR will complete suspense

---

.changeset/fast-melons-raise.md
.changeset/nine-shoes-sell.md
packages/core/src/controller/BaseController.ts
packages/endpoint/src/schemas/Values.ts
packages/normalizr/src/__tests__/__snapshots__/index.test.js.snap
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/denormalize/unvisit.ts
packages/react/src/__tests__/integration-optimistic-endpoint.web.tsx

Since we're now dealing with denormalizing non-cached items; we can be presented with objects that may rely on their context (parent, key) to properly compute pk. If they were normalized first they would still find a pk (by it simply being passed as input).
Fully denormalize even when pk cannot be computed

enhance: Denormalize even when pk cannot be computed

---

.changeset/fifty-months-turn.md
.changeset/moody-forks-itch.md
.changeset/rotten-dots-learn.md
.changeset/seven-countries-march.md
.changeset/slow-pumas-rush.md
examples/benchmark/entity.js
examples/benchmark/normalizr.js
examples/benchmark/src/index.ts
packages/core/src/controller/BaseController.ts
packages/core/src/controller/__tests__/__snapshots__/getResponse.ts.snap
packages/core/src/controller/__tests__/getResponse.ts
packages/core/src/next/Controller.ts
packages/endpoint/src/schemas/EntitySchema.ts
packages/endpoint/src/schemas/__tests__/denormalize.ts
packages/endpoint/typescript-tests/array_schema.ts
packages/endpoint/typescript-tests/denormalize.ts
packages/legacy/src/SimpleRecord.ts
packages/legacy/src/useStatefulResource.ts
packages/normalizr/src/__tests__/__snapshots__/index.test.js.snap
packages/normalizr/src/__tests__/denormalizeCached.js
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/__tests__/inferResults.ts
packages/normalizr/src/__tests__/normalizerMerge.test.tsx
packages/normalizr/src/denormalize/denormalize.ts
packages/normalizr/src/denormalize/denormalizeSimple.ts
packages/normalizr/src/index.ts
packages/normalizr/src/inferResults.ts

Simplify denormalize to have one return value
- Found is only used in conjunction with inferred results
- Found only has relevance for entity inference
- If not found when inferring, then we don't actually use the data from that inference
Therefore:
We use the entities to lookup in infer. If we cannot find the entity, we don't even return the ID.
This means we need to change Entity.infer. To keep back compat as endpoint consumer (normalizr), we will detect entity case in the infer function and run fallback code.
Once we have `undefined` when entities don't exist, we can simply check for any `undefined` to determine the validity of inferred results. Previously any non-entity case would simply infer `undefined` anyway, and when denormalize found `undefined` it would return found of `false`. …

enhance: Remove the need for 'found' in denormalize

---

.changeset/thin-peaches-wait.md
packages/normalizr/src/WeakEntityMap.ts

The first dependency is always the input, which has a path of {key:'', pk: ''}. While this is an important part of dependencies, it should not be part of the path list as it is not a valid entity.

fix: Remove empty entity path from denormalize

---

.changeset/nine-cups-admire.md
examples/benchmark/core.js
packages/core/src/controller/BaseController.ts
packages/core/src/controller/__tests__/getResponse.ts

Simplified code. Better performance.
When we pass in null as the first arg, we are indicating we want to 'do nothing'.
For getResponse() this means
- Our results won't be found organically so they will be inferred
- Thererfore, the results cannot be cached
- Therefore, no entities will be found and thus no entity cache
- So essentially our data is just filling the shape with inferred results, which means we can just return those immediately.
- Since we never want to fetch we will return expiryStatus as Valid, and expiresAt Infinity - there is no case where we can do anything here
This results in a 5x speedup of the already very fast path:
Before:
getResponse (null) x 1,709,543 ops/sec ±0.17% (98 runs sampled)
After
getResponse (null) x 6,400,458 ops/sec ±0.20% (98 runs sampled)

enhance: Simplified null args path for ctrl.getResponse()

---

.changeset/fuzzy-clouds-occur.md
.changeset/sour-radios-drop.md
packages/core/src/state/reducer/setReducer.ts
packages/endpoint/src/interface.ts
packages/endpoint/src/schemas/Entity.ts
packages/endpoint/src/schemas/EntitySchema.ts
packages/normalizr/src/interface.ts
packages/normalizr/src/normalize.ts

Allowing for more flexible schemas, including customizing expiry controls
- Hoist no `fetchAt` handling to earlier to simplify control flow, and reduce bundle size.
- Entity.mergeMeta() normalize lifecycle pushing metadata handling to the schema

feat: Add Entity.mergeMeta()

---

packages/endpoint/src/schemas/Delete.ts
packages/endpoint/src/schemas/Invalidate.ts

Ensure same race condition handling, etc is used by deleted
Since updates are kind of meaningless after a delete, we're safe to not worry about reordering and just replace with our symbol.

enhance: Invalidate/Delete uses modern normalize lifecycles

---

.changeset/famous-toes-jam.md
.changeset/tame-mails-rest.md
packages/endpoint/src/interface.ts
packages/endpoint/src/schemas/Entity.ts
packages/endpoint/src/schemas/EntitySchema.ts
packages/endpoint/src/schemas/Invalidate.ts
packages/normalizr/src/interface.ts
packages/normalizr/src/normalize.ts
website/src/components/Playground/editor-types/@rest-hooks/core.d.ts
website/src/components/Playground/editor-types/@rest-hooks/core/next.d.ts
website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts
website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts
website/src/components/Playground/editor-types/@rest-hooks/normalizr.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest/next.d.ts
website/src/components/Playground/editor-types/rest-hooks.d.ts

Keep naming consistent with mergeWithStore

enhance: mergeMeta -> mergeMetaWithStore

---

.changeset/brown-countries-turn.md
docs/core/api/useDLE.md
packages/endpoint/src-4.0-types/schemas/Entity.d.ts
packages/endpoint/src-4.0-types/schemas/EntitySchema.d.ts
packages/endpoint/src/types.ts
packages/react/src/__tests__/integration-collections.tsx
packages/rest/src-4.0-types/next/OptionsToFunction.d.ts
packages/rest/src/RestEndpoint.d.ts
packages/rest/src/__tests__/types.test.ts
packages/rest/src/next/RestEndpoint.d.ts
packages/rest/src/next/__tests__/RestEndpoint.ts
packages/rest/src/next/__tests__/types.test.ts
packages/rest/src/next/createResource.ts
packages/rest/src/next/index.ts
packages/rest/src/next/resourceTypes.ts
packages/rest/src/utiltypes.ts
packages/rest/tsconfig.typetest.json

Ensure extensive compatibility with type combinations
- Update TS 4.0 Entity types with changes
- Add TS 4.0 OptionsToFunction for /next (just like normal)
- Move Resource specific interfaces to another file
- Exclude number in Value utility for TypeScript 4.4 and below (see https://www.typescriptlang.org/play?ts=4.4.4#code/C4TwDgpgBAglC8UDeUBGB7VAuKBnYATgJYB2A5gNxQDaA1jvseQLo4CsAPo6WVAL4UAsACgRIiAA8w6AsCihIUAEoQAjgFciBCABMA0hBC4APABUAfAigA1AIYAbdRBMB5EvZAqNW3WfPmhUWFJaVl5cGg3Dy9NbR0-KyQRKBo9KFIoWkN0ADMoUyhbXDxCHihJYAgSHWK0gH4oEggANwgCKBw9ZgBaOpwkPnKJSurigAUiAGNaMwAaKD1zZJSoBqbWgmWUzsCBMWEFaDtHZwTEUzpsvNNmQJFDqABhKyjPNVjfGCWDiKgAIT+ViyIFyT3uv0ez0QxycJke5iAA)
- For RestEndpoint/createResource constructors - only wrap the generic options in Readonly. (both /next and normal)
- This is only …

enhance: Fix rest/next types

---

.changeset/afraid-emus-cover.md
.changeset/orange-numbers-eat.md
.changeset/shiny-moose-tell.md
examples/github-app/src/resources/Base.ts
packages/endpoint/src/index.ts
packages/endpoint/src/interface.ts
packages/endpoint/src/schema.d.ts
packages/endpoint/src/schemas/Collection.ts
packages/endpoint/src/schemas/Invalidate.ts
packages/rest/src/extractCollection.ts
packages/rest/src/index.ts
packages/rest/src/next/RestEndpoint.d.ts
packages/rest/src/next/createResource.ts
packages/rest/src/next/index.ts
packages/rest/src/next/resourceTypes.ts
website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts
website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest/next.d.ts

- export  SchemaSimpleNew,  PolymorphicInterface,
- Collection matches Polymoprhic interface, rather than Array | Values [Prefer base types over union](https://github.com/microsoft/TypeScript/wiki/Performance#preferring-base-types-over-unions)
- Collection push/unshift/assign ternary matches against base interface, rather than fully realized types
- use Invalidate instead of Delete (same thing, different name) for /new createResource
- export every type from /new/RestEndpoint.js

enhance: Add missing type exports

---

.changeset/gentle-tables-shop.md
.changeset/sixty-pans-melt.md
packages/endpoint/src/schema.d.ts
packages/endpoint/src/schemas/Collection.ts
packages/normalizr/src/denormalize/globalCache.ts
packages/normalizr/src/interface.ts

Consistent public interface
Since Collections should overlap with different instances, we should not have distinct caches per instance. However, we still must support Entity uniqueness, so we expose those with `Collection.cacheWith`

enhance: Collections should use .cacheWith to tell cache what to vary on

---

examples/todo-app/src/pages/Home/NewTodo.tsx
packages/rest/src/RestEndpoint.d.ts
packages/rest/src/next/RestEndpoint.d.ts

When users specify searchParams with all optional fields, we want it to be optional
```ts
TodoResourceBase.create.extend({
searchParams: {} as { userId?: string | number } | undefined,
getOptimisticResponse(snap, body) {
return body;
},
})
```
For non-loose we can detect `undefined`. However, previously we only tried to match against `string` type. By using `{} extends UrlParams` we can handle both string case, as well as optional fields.

enhance: Improve loose null typing

---

.changeset/late-bobcats-design.md
.changeset/silent-chicken-protect.md
.circleci/config.yml
examples/github-app/src/resources/Reaction.tsx
examples/todo-app/src/resources/PlaceholderBaseResource.ts
examples/todo-app/src/resources/TodoResource.ts
examples/todo-app/tsconfig.typetest41.json
examples/todo-app/typetest41.ts
packages/rest/src/RestEndpoint.d.ts
packages/rest/src/__tests__/types.test.ts
packages/rest/src/next/RestEndpoint.d.ts
packages/rest/src/next/__tests__/types.test.ts
packages/rest/src/pathTypes.ts
website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts
website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest/next.d.ts

Computing function arguments is one of the hottest type paths in this library. It is not only used in all call inference, but used to type options when defining RestEndpoints.
`{} extends P` works even with loose null types - allowing us to remove the loose-type generic split.
We added an extensive type suite to test all combinations of searchParams and path. We run this against the entire type matrix except 4.0 which doesn't have sufficient support for path templates.

enhance: Disallow non-object when all path members are optional

---

.changeset/five-spoons-admire.md
docs/rest/api/Collection.md
packages/endpoint/src/schema.d.ts
packages/endpoint/src/schemas/Collection.ts
packages/endpoint/src/schemas/__tests__/Collection.test.ts
packages/endpoint/src/schemas/__tests__/__snapshots__/Collection.test.ts.snap
packages/rest/src/next/createResource.ts
website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts
website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest/next.d.ts

Sane defaults. Easy overrides.
After lots of usage I found the most common as well as obvious case we simply want to spread. This alleviates the need to specify a key for these cases.
```ts
new schema.Collection([Todo])
```

enhance: Collection has default argsKey

---

.changeset/polite-ties-joke.md
.changeset/strange-waves-develop.md
docs/rest/api/Collection.md
packages/endpoint/src/schema.d.ts
packages/endpoint/src/schemas/Collection.ts
packages/endpoint/src/schemas/__tests__/Collection.test.ts
packages/rest/src/paginatedCollections.ts
website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts
website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest/next.d.ts
website/src/components/Playground/styles.module.css

"The fastest fetch is the one that never happens." - Nathaniel
For argsKey based Collections they will 100% have everything needed to infer results.
In other words, if we have a Collection in store from another fetch (say we nested Todos by user inside User fetch). Now when we want to get just todos by user, we don't need to do any fetch because the data is already there.

enhance: Infer non-nested Collections

---

.changeset/big-ways-care.md
packages/endpoint/src/schema.d.ts
packages/endpoint/src/schemas/Collection.ts
scripts/copywebsitetypes.sh
website/src/components/Playground/editor-types/@rest-hooks/endpoint.d.ts
website/src/components/Playground/editor-types/@rest-hooks/graphql.d.ts
website/src/components/Playground/editor-types/@rest-hooks/react.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest.d.ts
website/src/components/Playground/editor-types/@rest-hooks/rest/next.d.ts
website/src/components/Playground/editor-types/react.d.ts
website/src/components/Playground/editor-types/rest-hooks.d.ts

`.key` is called a lot, so this is a slight optimization
Set key in constructor since `schema` is readonly

enhance: Set Collection key in constructor

---

.changeset/big-radios-speak.md
.changeset/six-emus-smoke.md
__tests__/new.ts
docs/core/getting-started/comparison.md
examples/todo-app/src/resources/PlaceholderBaseResource.ts
packages/core/src/manager/NetworkManager.ts
packages/core/src/state/reducer/fetchReducer.ts
packages/react/src/hooks/__tests__/useController/__snapshots__/fetch.tsx.snap
packages/react/src/next/__tests__/__snapshots__/fetch.tsx.snap
packages/react/src/next/__tests__/fetch.tsx
packages/rest/src/createResource.ts
packages/rest/src/next/createResource.ts
packages/rest/src/next/resourceTypes.ts

Reduce common code.
Since RestEndpoints have a fairly common argument structure, we can exploit this to provide sensible optimistic defaults. We add to the resource since we most likely want to share the optimistic nature across different mutation types.
- Retrieval endpoints this is pointless
- We want to be able to encode our 'create' optimistic in getList so we can use extenders like unshift,assign, etc.

feat: Add 'optimistic' option to createResource

---

.changeset/chilled-news-wink.md
packages/rest/src/RestEndpoint.js
packages/rest/src/__tests__/__snapshots__/createResource.test.ts.snap
packages/rest/src/__tests__/createResource.test.ts
packages/rest/src/next/RestEndpoint.js

Since Resource.delete handles empty responses in process(), we cannot be so eager to rule out empty responses in parseResponse for RestEndpoint.
(200 delete with empty response is still valid because process falls back to using parameters to find the element to delete*
Don't be as strict with response when process is overridden in RestEndpoint.

fix: Remove false positive Resource.delete with 200 response type but empty text

---

.changeset/afraid-keys-change.md
.changeset/silent-lies-yell.md
packages/rest/src-4.0-types/pathTypes.d.ts
packages/rest/src/RestEndpoint.d.ts
packages/rest/src/RestHelpers.ts
packages/rest/src/__tests__/Resource.test.ts
packages/rest/src/__tests__/__snapshots__/createResource.test.ts.snap
packages/rest/src/__tests__/createResource.test.ts
packages/rest/src/__tests__/types.test.ts
packages/rest/src/createResource.ts
packages/rest/src/pathTypes.ts
packages/rest/src/resourceTypes.ts

> Can there be better feedback when the path passed to createResource is malformed? Currently, if the path is /todos instead of /todos/:id, rest-hooks will completely ignore the path and send the request to urlPrefix with no path appended
by Firelight on discord
createResource() will throw without a path as this is not well defined.
Also: Fixed a type for push/unshift/assign that put double nested Promises as return type rather than only one promise

enhance: createResource() throws without at least one path :parameter

---

.changeset/sharp-islands-pull.md
docs/rest/api/createResource.md
examples/github-app/src/resources/Base.ts
examples/todo-app/src/resources/PlaceholderBaseResource.ts
packages/react/src/__tests__/__snapshots__/integration-collections.tsx.snap
packages/react/src/__tests__/integration-collections.tsx
packages/rest/src/createResource.ts
packages/rest/src/resourceTypes.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/@data-client/rest/next.d.ts

Simplify common definitions. (Abstraction specialization)
Before
```ts
const BaseArticleResource = createResource({
urlPrefix: 'http://test.com',
path: '/article/:id',
searchParams: {} as { userId?: number } | undefined,
schema: Article,
});
const ArticleResource = {
...BaseArticleResource,
getNextPage: BaseArticleResource.paginated('page'),
};
```
After
```ts
const ArticleResource = createResource({
urlPrefix: 'http://test.com',
path: '/article/:id',
searchParams: {} as { userId?: number } | undefined,
schema: Article,
paginationField: 'page',
});
```
```tsx
import { useSuspense, useController } from '@data-client/react';
import { NewsResource } from 'api/News';
function NewsList() {
const articles = useSuspense(ArticleResource.getList);
const ctrl = useController();
return (
<Pagination …
```

feat: Add paginationField to createResource

---

.changeset/new-countries-approve.md
docs/rest/api/schema.Entity.md
packages/endpoint/src/schemas/EntitySchema.ts
packages/endpoint/src/schemas/Invalidate.ts
packages/endpoint/src/schemas/__tests__/Delete.test.ts
packages/endpoint/src/schemas/__tests__/Entity.test.ts
packages/endpoint/src/schemas/__tests__/__snapshots__/Delete.test.ts.snap
packages/endpoint/src/schemas/__tests__/__snapshots__/Entity.test.ts.snap
packages/endpoint/src/schemas/__tests__/__snapshots__/EntitySchema.test.ts.snap

Handle case where users use template strings for [pk](https://dataclient.io/rest/api/Entity#pk)
```ts
class MyEntity extends Entity {
id = 0;
secondthing = '';
pk() {
return `${this.id}`;
}
}
```
Update pk check to `id === undefined || id === '' || id === 'undefined'`

enhance: Detect unusable pk when pk is serialized

---

examples/github-app/package-lock.json
examples/github-app/package.json
examples/todo-app/package-lock.json
examples/todo-app/package.json

Fixes weird build resolution issues.
Stackblitz doesn't support yarn3, so npm install is faster. We can get the right tree if we build the lock after running the yarn resolution algo.

docs: Add lockfile for stackblitz demos

---

.changeset/tender-turtles-grin.md
packages/endpoint/src/endpoint.js
packages/endpoint/src/schemas/EntitySchema.ts
packages/ssr/src/getInitialData.ts

Realistically name mangling only matters when doing hydration where keys are expected to be consistent. So it's just spam for other people.
Furthermore, previous methods would potentially spam the console more than once per type.
We indicate this is an issue to look for in the SSR library.
This will remain back compatible tho not warn if one package is outdated. This is fine because they would have been warned already had they not solved this.

enhance: Only warn about name mangling when using SSR and once

---

.changeset/wise-buses-eat.md
.circleci/config.yml
packages/react/src/hooks/__tests__/useSuspense.native.tsx
packages/test/package.json
packages/test/src/makeRenderRestHook/renderHook.cts
yarn.lock

BREAKING CHANGE: @testing-library/react-hooks must be installed when using react 16 or 17 and testing library
Recent versions of NPM really don't like when peerDeps don't match
We make @testing-library/react-hooks an optional peerdep so it's only used when react 17,16 is used.

enhance: React 16,17 testing require @testing-library/react-hooks installed

---

.changeset/shiny-spies-give.md
.changeset/violet-donkeys-tell.md
packages/test/rollup.config.js

'./render18HookWrapped.js' and '@testing-library/react-hooks' need to be dynamically required
'@testing-library/react-hooks' is an optional dependency, and render18HookWrapped needs to be in a distinct file for RN
Add `ignore` configure to [commonjs rollup plugin](https://github.com/rollup/rollup-plugin-commonjs)

fix: Commonjs rollup build for test

---

.changeset/cool-dryers-change.md
.changeset/many-pears-explain.md
README.md
docs/core/api/Controller.md
docs/core/concepts/expiry-policy.md
packages/core/src/actionTypes.ts
packages/core/src/controller/Controller.ts
packages/core/src/controller/createExpireAll.ts
packages/core/src/newActions.ts
packages/core/src/state/reducer/createReducer.ts
packages/core/src/state/reducer/expireReducer.ts
packages/react/README.md
packages/react/src/hooks/__tests__/useController/expireAll.tsx
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/core/next.d.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/@data-client/rest/next.d.ts

Fixes #1548
Similar to use case of [invalidateAll()](https://dataclient.io/docs/api/Controller#invalidateAll), but does not result in loading condition.
Add controller.expireAll() that sets all responses to *STALE*
```ts
controller.expireAll(ArticleResource.getList);
```
This is like controller.invalidateAll(); but will continue showing
stale data while it is refetched.
This is sometimes useful to trigger refresh of only data presently shown
when there are many parameterizations in cache.

Add controller.expireAll() that sets all responses to *STALE*

---

.changeset/old-hairs-give.md
docs/core/getting-started/mutations.md
examples/todo-app/src/resources/PlaceholderBaseResource.ts
packages/endpoint/src/schemas/Collection.ts
packages/endpoint/src/schemas/EntitySchema.ts
packages/endpoint/src/schemas/__tests__/Object.test.js
packages/endpoint/src/schemas/__tests__/__snapshots__/Entity.test.ts.snap
packages/endpoint/src/schemas/__tests__/__snapshots__/EntitySchema.test.ts.snap
packages/endpoint/src/schemas/__tests__/legacy-compat/__snapshots__/Entity.test.ts.snap
packages/endpoint/src/schemas/special.ts
packages/react/src/__tests__/integration-collections.tsx
packages/react/src/__tests__/integration-optimistic-endpoint.web.tsx
website/src/components/Demo/code/todo-app/rest/NewTodo.tsx
website/src/components/Demo/code/todo-app/rest/index.ts
website/src/fixtures/todos.ts
website/yarn.lock

Forcing users to add `id` argument to body for optimistic creates is not only awkward - it means their API has to not explode if they send it over network.
```ts
controller.fetch(TodoResource.getList.push, {
id: randomId(),
userId,
title: e.currentTarget.value,
});
```
Use random ids when id does not exist
If pk() cannot be computed, instead compute a random id. Detect when the current normalize schema is using collection adders and if so don't throw in this case. A bit hacky - but we store the flag of collection add in visitedEntities using a symbol so it is not iterated over.
```ts
controller.fetch(TodoResource.getList.push, {
userId,
title: e.currentTarget.value,
});
```

enhance: Optimistic creates no longer need a 'fake pk'

---

.changeset/late-hotels-deliver.md
.changeset/odd-tables-tease.md
.changeset/strange-parents-crash.md
README.md
docs/core/getting-started/resource.md
docs/rest/api/RestEndpoint.md
docs/rest/api/createResource.md
docs/rest/guides/pagination.md
examples/github-app/src/pages/IssueList.tsx
examples/github-app/src/pages/NextPage.tsx
examples/github-app/src/resources/Base.ts
packages/endpoint/src/schemas/Collection.ts
packages/react/README.md
packages/react/src/__tests__/__snapshots__/integration-collections.tsx.snap
packages/react/src/__tests__/integration-collections.tsx
packages/rest/src/RestEndpoint.d.ts
packages/rest/src/RestEndpoint.js
packages/rest/src/__tests__/RestEndpoint.ts
packages/rest/src/__tests__/createResource.test.ts
packages/rest/src/createResource.ts
packages/rest/src/paginatedCollections.ts
packages/rest/src/resourceTypes.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/@data-client/rest/next.d.ts
website/yarn.lock

DRY
`paginationField` is added to both [createResource](https://dataclient.io/rest/api/createResource) and [RestEndpoint](https://dataclient.io/rest/api/RestEndpoint)
When provided, adds a specialized extender (like push/unshift/assign) to the list. This also only works with [collections](https://dataclient.io/rest/api/Collection).
```ts
const TodoResource = createResource({
path: '/todos/:id',
schema: Todo,
paginationField: 'page',
}).getList.getPage({ page: '2' });
```

feat: Add 'paginationField' parameter to RestEndpoint and createResource

---

.changeset/tidy-kiwis-trade.md
docs/core/api/Controller.md
examples/github-app/src/pages/IssueList.tsx
examples/github-app/src/routing/routes.tsx
packages/core/src/controller/Controller.ts
packages/core/src/controller/__tests__/Controller.ts
packages/img/package.json
packages/redux/package.json
packages/ssr/package.json
packages/test/package.json
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/core/next.d.ts
yarn.lock

Fixes https://github.com/data-client/rest-hooks/discussions/2402
Avoid overfetching when performing fetch-as-you-render patterns
Add controller.fetchIfStale()
Fetches only if endpoint is considered '[stale](../concepts/expiry-policy.md#stale)'; otherwise returns undefined.
This can be useful when prefetching data, as it avoids overfetching fresh data.
An [example](https://stackblitz.com/github/data-client/rest-hooks/tree/master/examples/github-app?file=src%2Frouting%2Froutes.tsx) with a fetch-as-you-render router:
```ts
{
name: 'IssueList',
component: lazyPage('IssuesPage'),
title: 'issue list',
resolveData: async (
controller: Controller,
{ owner, repo }: { owner: string; repo: string },
searchParams: URLSearchParams,
) => {
const q = searchParams?.get('q') || 'is:issue is:open';
await …
```

feat: Add controller.fetchIfStale()

---

.changeset/tidy-coats-drum.md
docs/core/api/Controller.md
docs/rest/README.md
packages/core/src/controller/Controller.ts
packages/core/src/controller/__tests__/Controller.ts
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/core/next.d.ts

Return value is often used to determine other things. It's more important to use the fetched data than to know if we actually fetched
Resolve to existing data if it is not fetched.

enhance: controller.fetchIfStale() resolves to data from store if it does not fetch

---

.changeset/gentle-rivers-decide.md
.changeset/unlucky-boxes-jog.md
docs/rest/README.md
docs/rest/guides/pagination.md
examples/github-app/src/pages/IssueList.tsx
examples/github-app/src/pages/NextPage.tsx
examples/github-app/webpack.config.js
packages/endpoint/src/schemas/Collection.ts
packages/react/src/__tests__/__snapshots__/integration-collections.tsx.snap
packages/react/src/__tests__/integration-collections.tsx
packages/react/src/__tests__/integration-endpoint.web.tsx
packages/react/src/test-fixtures.ts
packages/rest/src/RestEndpoint.js
packages/rest/src/paginatedCollections.ts
website/src/fixtures/posts.ts
website/yarn.lock

The best way to know what page to get next is by using a value sent from the network request. This is required for cursor based pagination, but even for page-based systems there are problems with attempting to track locally as it easily becomes inconsistent with what has been fetched by the server.
Rather than adding a new result and also merging in the existing response:
Next pages should actually replace the whole response - simply merging the list piece. This way it updates with new values like its cursor or page, etc.
To achieve this we modify [RestEndpoint.paginated()](https://dataclient.io/rest/api/RestEndpoint#paginated-function) (only with Collections as other means are 'legacy' and thus we don't want to change behavior):
We now override the Endpoint's key to ensure we remove the …

enhance: Collection based pagination updates entire 'root' response

---

.changeset/young-bulldogs-scream.md
packages/endpoint/src/schemas/Collection.ts
packages/endpoint/src/schemas/consistentSerialize.native.ts
packages/endpoint/src/schemas/consistentSerialize.ts

Work with React Native
.native version of any algorithms that need sorting that will fallback in case this fails. So weird that RN doesn't have Array.sort() in all cases. This is the same as paramsToString from @data-client/rest.

fix: some versions of RN not working with Collections

---

.github/workflows/site-preview.yml
.github/workflows/site-release.yml
docs/rest/guides/pagination.md

We want accurate last updated for docs site
Since vercel's integration doesn't allow much configuration - we move to using our own github actions relying on their CLI instead. This gives us control over fetch depth.

docs: Fix 'last updated' on site

---

.changeset/wet-waves-share.md
docs/core/shared/_useLoading.mdx
docs/rest/api/Collection.md
packages/endpoint/src/schemas/Collection.ts
packages/endpoint/src/schemas/EntitySchema.ts
packages/endpoint/src/schemas/__tests__/Collection.test.ts
website/src/components/Playground/editor-types/@data-client/endpoint.d.ts
website/src/components/Playground/editor-types/@data-client/graphql.d.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/@data-client/rest/next.d.ts
website/src/fixtures/posts-collection.ts
website/src/fixtures/posts.ts

Specialization to simplify customization
`nonFilterArgumentKeys` defines a test to determine which argument keys
are _not_ used for filtering the results. For instance, if your API uses
'orderBy' to choose a sort - this argument would not influence which
entities are included in the response.
```ts
const getPosts = new RestEndpoint({
path: '/:group/posts',
searchParams: {} as { orderBy?: string; author?: string },
schema: new schema.Collection([Post], {
nonFilterArgumentKeys(key) {
return key === 'orderBy';
},
}),
});
```
For convenience you can also use a RegExp or list of strings:
```ts
const getPosts = new RestEndpoint({
path: '/:group/posts',
searchParams: {} as { orderBy?: string; author?: string },
schema: new schema.Collection([Post], {
nonFilterArgumentKeys: /orderBy/,
}),
});
``` …

feat: Add nonFilterArgumentKeys argument to Collection

---

.changeset/selfish-bananas-serve.md
docs/rest/api/Collection.md
docs/rest/api/createResource.md
packages/react/src/__tests__/__snapshots__/integration-collections.tsx.snap
packages/react/src/__tests__/integration-collections.tsx
packages/rest/src/createResource.ts
packages/rest/src/resourceTypes.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/@data-client/rest/next.d.ts

Make it easier to customize [Collection](https://dataclient.io/rest/api/Collection) usage with [Resources](https://dataclient.io/rest/api/createResource)
Class used to construct [getList](https://dataclient.io/rest/api/createResource#getlist) schema.
```ts
import { schema, createResource } from '@data-client/rest';
class MyCollection<
S extends any[] | PolymorphicInterface = any,
Parent extends any[] = [urlParams: any, body?: any],
> extends schema.Collection<S, Parent> {
// getList.push should add to Collections regardless of its 'sorted' argument
nonFilterArgumentKeys(key: string) {
return key === 'sorted';
}
}
const TodoResource = createResource({
path: '/todos/:id',
searchParams: {} as { userId?: string; sorted?: boolean } | undefined,
schema: Todo,
// highlight-next-line
Collection: …
```

feat: Add Collection option to createResource

---

.changeset/odd-pants-roll.md
packages/rest/src/__tests__/createResource.test.ts
packages/rest/src/resourceExtensionTypes.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/@data-client/rest/next.d.ts

Fix Resource.extend() for builtin endpoints with zero typing options
```ts
const RatingResource = createResource({
path: '/ratings/:id',
schema: Rating,
}).extend({
getList: {
dataExpiryLength: 10 * 60 * 1000, // 10 minutes
},
});
```
This would previously break the types of RatingResource.getList.
This would only occur because dataExpiryLength is not a type-influencing option.
In the case of an option specified, but not including type-influencing options (PartialRestGenerics) the generic would end up being `PartialRestGenerics` rather than any - therefore we simply add a condition to handle that.

fix: Resource.extend() for builtin endpoints with zero typing options

---

.github/workflows/site-preview.yml
.github/workflows/site-release.yml

In case we hit limits https://vercel.com/docs/limits/overview#username-update we don't want a red mark on our history
`continue-on-error` should ensure the action doesn't fail

internal: Do not fail on vercel deploys

---

.changeset/bright-planes-dance.md
docs/rest/api/Collection.md
packages/core/src/controller/Controller.ts
packages/core/src/controller/createSet.ts
packages/core/src/controller/ensurePojo.ts
packages/react/src/__tests__/__snapshots__/integration-collections.tsx.snap
packages/react/src/__tests__/integration-collections.tsx
packages/rest/src/createResource.ts
website/src/fixtures/posts-collection.ts

It's often easy to prepare data using FormData.
[Collections](https://dataclient.io/rest/api/Collection) can filter based on FormData arguments
```ts
ctrl.fetch(
getPosts.push,
{ group: 'react' },
new FormData(e.currentTarget),
);
```
Say our FormData contained an `author` field. Now that newly created
item will be properly added to the [collection list](https://dataclient.io/rest/api/Collection) for that author.
```ts
useSuspense(getPosts, {
group: 'react',
author: 'bob',
});
```
In this case if `FormData.get('author') === 'bob'`, it will show
up in that [useSuspense()](https://dataclient.io/docs/api/useSuspense) call.
See more in the [Collection nonFilterArgumentKeys example](https://dataclient.io/rest/api/Collection#nonfilterargumentkeys)
We convert args away from FormData inside the …

enhance: Collections can filter based on FormData arguments

---

.changeset/purple-hornets-turn.md
docs/rest/api/Entity.md
packages/endpoint/src/schemas/Entity.ts
packages/endpoint/src/schemas/EntitySchema.ts
packages/endpoint/src/schemas/Invalidate.ts
website/src/components/Playground/editor-types/@data-client/endpoint.d.ts
website/src/components/Playground/editor-types/@data-client/graphql.d.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/react.d.ts

normalize has this so we might as well pass it on. This enables applying the [case of the missing id](https://dataclient.io/rest/guides/network-transform#case-of-the-missing-id) to entities and not just endpoints.
Entity.process() now gets an addition argument of 'args' (sent from endpoint)
```ts
class Stream extends Entity {
username = '';
title = '';
game = '';
currentViewers = 0;
live = false;
pk() {
return this.username;
}
static key = 'Stream';
process(value, parent, key, args) {
const processed = super.process(value, parent, key, args);
processed.username = args[0]?.username;
return processed;
}
}
```

Entity.process() now gets an addition argument of 'args' (sent from endpoint)

---

.changeset/new-pugs-smell.md
docs/core/api/AsyncBoundary.md
docs/core/api/NetworkErrorBoundary.md
packages/react/src/components/AsyncBoundary.tsx
packages/react/src/components/NetworkErrorBoundary.tsx
packages/react/src/components/__tests__/AsyncBoundary.web.tsx
packages/react/src/components/__tests__/NetworkErrorBoundary.web.tsx
website/src/components/Playground/editor-types/@data-client/react.d.ts

Easy style customization
Add className to [error boundary ](https://dataclient.io/docs/api/NetworkErrorBoundary)and errorClassName to [AsyncBoundary](https://dataclient.io/docs/api/AsyncBoundary)
```tsx
<AsyncBoundary errorClassName="error">
<Stuff/>
</AsyncBounary>
```
```tsx
<NetworkErrorBoundary className="error">
<Stuff/>
</NetworkErrorBoundary>
```

feat: Add className option for ErrorBoundaries

---

.changeset/dirty-adults-sparkle.md
packages/core/src/manager/applyManager.ts
packages/core/src/middlewareTypes.ts
website/src/components/Playground/editor-types/@data-client/core.d.ts

Dropping deprecations
[Middleware](https://dataclient.io/docs/api/Manager#getmiddleware) no longer gets `controller` prop.
The entire API is controller itself:
`({controller}) => next => async action => {}` ->
`(controller) => next => async action => {}`
```ts
class LoggingManager implements Manager {
getMiddleware = (): Middleware => controller => next => async action => {
console.log('before', action, controller.getState());
await next(action);
console.log('after', action, controller.getState());
};
cleanup() {}
}
```
Note this has been possible for some time this simply drops
legacy compatibility.

enhance: Middleware no longer gets  prop.

---

.changeset/rotten-ears-remember.md
packages/rest/src/RestEndpoint.js
packages/rest/src/__tests__/RestEndpoint.ts
packages/rest/src/__tests__/__snapshots__/RestEndpoint.ts.snap

These change the networking, so any logging system relying on names should receive a different value
getPage,push,unshift,assign should not match name of parent
```ts
const getTodos = new RestEndpoint({
urlPrefix: 'https://jsonplaceholder.typicode.com',
path: '/todos',
schema: new schema.Collection([Todo]),
name: 'gettodos',
});
getTodos.getPage.name === 'gettodos.getPage';
getTodos.push.name === 'gettodos.create';
getTodos.unshift.name === 'gettodos.create';
```

enhance: getPage,push,unshift,assign should not match name of parent

---

.changeset/slow-tips-cross.md
docs/core/api/CacheProvider.md
docs/core/api/Controller.md
docs/core/api/LogoutManager.md
docs/core/api/Manager.md
examples/github-app/src/RootProvider.tsx
packages/react/src/components/CacheProvider.tsx
packages/react/src/components/__tests__/provider.native.tsx
packages/react/src/components/__tests__/provider.tsx
packages/react/src/components/index.ts

Leading towards having multiple CacheProvider instances - this is the first step. This also makes conceptualizing around managers a bit more straightforward.
CacheProvider elements no longer share default managers
New export: `getDefaultManagers()`
BREAKING CHANGE: Newly mounted CacheProviders will have new manager
objects when default is used

enhance: CacheProvider elements no longer share default managers

---

.changeset/tasty-gifts-shop.md
packages/endpoint/src/schemas/__tests__/Object.test.js
packages/endpoint/src/schemas/__tests__/Serializable.test.ts
packages/endpoint/src/schemas/__tests__/__snapshots__/Object.test.js.snap
packages/endpoint/src/schemas/__tests__/__snapshots__/Serializable.test.ts.snap
packages/normalizr/src/normalize.ts

We need absolute consistency when performing SSR and mounting the store, or we have potential for hydration mismatches.
BREAKING: Serializer schemas are only processed during denormalization.
- This was the already the intended behavior of the [original pr for serializers](https://github.com/data-client/data-client/pull/355)
- Since then we introduced consistent caching, so there is no longer a performance benefit for running this during normalization

enhance: Serializer schemas are only processed during denormalization

---

.changeset/sour-dryers-reflect.md
packages/core/package.json
packages/graphql/package.json
packages/hooks/package.json
packages/img/package.json
packages/react/package.json
packages/redux/package.json
packages/rest/package.json
yarn.lock

https://github.com/changesets/changesets/issues/432 changesets doesn't work with workspace protocols currently. This means it publishes packages with incorrect version listed (keeping workspace:)
Move back to nonworkspace until this is fixed.

fix: Published dependency range

---

.changeset/afraid-phones-sip.md
packages/core/rollup.config.js
packages/endpoint/rollup.config.js
packages/graphql/rollup.config.js
packages/hooks/rollup.config.js
packages/img/rollup.config.js
packages/normalizr/rollup.config.js
packages/react/rollup.config.js
packages/redux/rollup.config.js
packages/rest/rollup.config.js
packages/ssr/rollup.config.js
packages/use-enhanced-reducer/rollup.config.js

Stackoverflow example embeds can utilize umd well
- Client packages namespace into RDC
- @data-client/react - RDC
- @data-client/core - RDC.Core
- @data-client/redux - RDC.Redux
- Definition packages namespace top level
- @data-client/rest - Rest
- @data-client/graphql - GraphQL
- @data-client/img - Img
- @data-client/endpoint - Endpoint
- Utility
- @data-client/normalizr - normalizr
- @data-client/use-enhanced-reducer - EnhancedReducer
- @data-client/test - [does not have an unpkg]
- unpkg (UMD) builds should bundle all non-peers (update externals specifically to only be listed peers)
- update names to above
- Add [output.globals](https://rollupjs.org/configuration-options/#output-globals) to correctly map the peerdeps to their unpkg name

fix: unpkg bundle holds everything needed and refers to peers correctly

---

.changeset/stupid-flies-yell.md
package.json
packages/react/rollup.config.js
yarn.lock

Fixes #2822
NextJS app router does not support any concept of state or server side rendering. It forces a directive to even run. We include these in our ESM, but rollup removes the directives, so our commonjs output is missing these.
Rollup issue: https://github.com/rollup/rollup/issues/4699 we found:
Copied https://github.com/inokawa/virtua/pull/103/files that simply pastes it to the top.

enhance: Improve compatibility by forcing app directive in commonjs build

---

.changeset/chilly-mugs-work.md
.changeset/lemon-zoos-relax.md
docs/rest/api/RestEndpoint.md
docs/rest/diagrams/_restendpoint_lifecycle.mdx
packages/rest/src/RestEndpoint.js
packages/rest/src/RestEndpointTypes.ts
packages/rest/src/__tests__/RestEndpoint.ts
packages/rest/src/index.ts
packages/rest/src/paramsToString.native.ts
packages/rest/src/paramsToString.ts

Fixes #2917 .
Enable usage of complex objects in [searchParams](https://dataclient.io/rest/api/RestEndpoint#searchParams)
Add [RestEndpoint.searchToString()](https://dataclient.io/rest/api/RestEndpoint#searchToString) to enable more easy customization of the serialization:
```typescript
import { RestEndpoint, RestGenerics } from '@data-client/rest';
import qs from 'qs';
class MyEndpoint<O extends RestGenerics = any> extends RestEndpoint<O> {
searchToString(searchParams) {
return qs.stringify(searchParams);
}
}
```
Also export `getUrlBase`, and `getUrlTokens`, to make it possible to customize the [url](https://dataclient.io/rest/api/RestEndpoint#url) method as well.

feat: Add RestEndpoint.searchToString()

---

.circleci/config.yml
.github/workflows/benchmark.yml

Recent version of corepack breaks due to https://github.com/nodejs/corepack/issues/379
Now that we're on the latest node in CI, corepack is preinstalled so just use that version.

internal: Do not globally install corepack

---

.changeset/tough-panthers-compare.md
packages/normalizr/src/WeakEntityMap.ts
packages/normalizr/src/__tests__/denormalizeCached.js
packages/normalizr/src/denormalize/UNDEF.ts
packages/normalizr/src/denormalize/unvisit.ts

Support resolving nested entities from a distinct fetch (client-side joins): https://dataclient.io/rest/api/Query#client-side-joins
In the case where:
- nested pk is valid
- but the entity is not present in cache
We currently won't bust the cache when those nested entities show up later (due to racing fetches). This means the above example will not show the nested members if they resolve *after* the top-level entity fetch.
When we have both a valid pk, and the entity from store is `undefined` we will add it to the dependency paths with a special `UNDEF` constant. This constant is needed so it can be used as a key in WeakMap (as only objects are tracked). In this sense, we simulate the value of `undefined` by having a special value for it that does not change.

fix: Missing nested entities should appear once they are present

---

.changeset/mean-mayflies-sleep.md
.changeset/serious-dogs-battle.md
.changeset/tough-panthers-compare.md
.changeset/two-foxes-explode.md
docs/rest/api/Query.md
docs/rest/api/schema.Entity.md
packages/endpoint/src-4.0-types/schemas/Entity.d.ts
packages/endpoint/src-4.0-types/schemas/EntitySchema.d.ts
packages/endpoint/src/interface.ts
packages/endpoint/src/schema.d.ts
packages/endpoint/src/schemas/Entity.ts
packages/endpoint/src/schemas/EntitySchema.ts
packages/endpoint/src/schemas/Invalidate.ts
packages/endpoint/typescript-tests/relationships.ts
packages/normalizr/src/__tests__/__snapshots__/index.test.js.snap
packages/normalizr/src/__tests__/denormalizeCached.js
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/__tests__/inferResults.ts
packages/normalizr/src/denormalize/unvisit.ts
packages/normalizr/src/interface.ts
packages/normalizr/src/normalize.ts
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/endpoint.d.ts
website/src/components/Playground/editor-types/@data-client/graphql.d.ts
website/src/components/Playground/editor-types/@data-client/normalizr.d.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts

Followup to #2956
The previous solution did not handle cases where the nested members appeared as numbers rather than strings.
`unvisit` check for `entityOrId` as 'id' compares type to 'object' rather than string, so it will match on the 'number' case.
Before:
```ts
class MyEntity extends Entity {
id = 0;
pk() {
return `${this.id}`;
}
}
```
After:
```ts
class MyEntity extends Entity {
id = 0;
pk() {
return this.id;
}
}
```
Before:
```json
{
"Article": {
"123": {
"author": 8472,
"id": 123,
"title": "A Great Article",
},
},
"User": {
"8472": {
"id": 8472,
"name": "Paul",
},
},
}
```
After:
```json
{
"Article": {
"123": {
"author": "8472",
"id": 123,
"title": "A Great Article",
},
},
"User": {
"8472": {
"id": 8472,
"name": "Paul",
},
},
}
```

fix: Properly vary cache when nested pk is a number

---

.changeset/neat-moose-applaud.md
packages/rest/src/RestEndpointTypes.ts
packages/rest/src/__tests__/createResource.test.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts

Ensure both consistency, and better accuracy when using Parameters<> on a [RestEndpoint](https://dataclient.io/rest/api/RestEndpoint).
Previously under loose types:
```ts
const getThing = new RestEndpoint({ path: '/test' });
const getThingExtended = getThing.extend({ path: '/test2' });
// [] | [undefined]
type A = Parameters<typeof getThing>;
// [undefined]
type V = Parameters<typeof getThingExtended>;
```
Previously when simply using the constructor, types were actively and robustly produced using `RestFetch<>`. We now employ this also for the extend case

enhance: Improve .extend() typing for loose types case

---

.changeset/five-flies-help.md
packages/react/src/hooks/useCache.ts
website/src/components/Playground/editor-types/@data-client/react.d.ts
website/src/components/Playground/editor-types/globals.d.ts

Accessing mutation endpoints can be useful
[useCache()](https://dataclient.io/docs/api/useCache) does not call fetch, so there's no reason to restrict it to only [side-effect ](https://dataclient.io/rest/api/Endpoint#sideeffect)free endpoints.

enhance: useCache() accepts Endpoints with sideEffects

---

.changeset/sharp-ears-think.md
__tests__/new.ts
docs/graphql/api/GQLEntity.md
docs/graphql/diagrams/_entity_lifecycle.mdx
docs/rest/api/Entity.md
docs/rest/diagrams/_entity_lifecycle.mdx
packages/endpoint/src-4.0-types/schemas/EntitySchema.d.ts
packages/endpoint/src/schemas/EntitySchema.ts
packages/endpoint/src/schemas/__tests__/Entity.test.ts
packages/endpoint/src/schemas/__tests__/EntitySchema.test.ts
website/blog/2024-03-15-v0.11-queries-querable-usequery.md
website/src/components/Playground/editor-types/@data-client/endpoint.d.ts
website/src/components/Playground/editor-types/@data-client/graphql.d.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/globals.d.ts
website/src/components/Playground/resources/TodoResource.ts

Make [Entity.shouldUpdate](/rest/api/Entity#shouldupdate) name consistent with [Entity.shouldReorder](/rest/api/Entity#shouldreorder)
```ts title="Before"
class MyEntity extends Entity {
// highlight-next-line
static useIncoming(
existingMeta: { date: number },
incomingMeta: { date: number },
existing: any,
incoming: any,
) {
return !deepEquals(existing, incoming);
}
}
```
```ts title="After"
class MyEntity extends Entity {
// highlight-next-line
static shouldUpdate(
existingMeta: { date: number },
incomingMeta: { date: number },
existing: any,
incoming: any,
) {
return !deepEquals(existing, incoming);
}
}
```

enhance: Entity.useIncoming -> Entity.shouldUpdate

---

.changeset/three-owls-notice.md
docs/core/api/useDLE.md
packages/react/src/hooks/__tests__/__snapshots__/useDLE.native.tsx.snap
packages/react/src/hooks/__tests__/useDLE.native.tsx
packages/react/src/hooks/__tests__/useSuspense.native.tsx
packages/react/src/hooks/useDLE.native.ts
packages/react/src/hooks/useFocusEffect.native.ts
packages/react/src/hooks/useSuspense.ts
website/blog/2024-03-15-v0.11-queries-querable-usequery.md

[useDLE()](https://dataclient.io/docs/api/useDLE) should behave as expected in react native - which is to say similar to [useSuspense](https://dataclient.io/docs/api/useSuspense).
This is sort of a bug fix, but technically a breaking change as it could result in unexpected extra fetches.
Add custom [useDLE ](https://dataclient.io/docs/api/useDLE)native implementation that has same react navigation focus handling code as [useSuspense()](https://dataclient.io/docs/api/useSuspense).

enhance: useDLE() reactive native focus handling

---

.changeset/quick-spiders-wave.md
packages/normalizr/README.md
packages/rest/src/RestEndpointTypes.ts
packages/rest/src/__tests__/RestEndpoint.ts
packages/rest/src/__tests__/types.test.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/globals.d.ts

Some weird APIs aren't REST, but they still mostly use HTTP protocols, so allow explicit set of sideEffect
We already do this correctly in constructor of RestEndpoint. Update type code in extend to reflect same logic in constructor. Add tests.

enhance: Allow sideEffect overrides when using .extend()

---

.changeset/new-readers-exercise.md
packages/endpoint/src-4.2-types/endpointTypes.d.ts
packages/endpoint/src-legacy-types/endpointTypes.d.ts
packages/endpoint/src/__tests__/endpoint.ts
packages/endpoint/src/endpointTypes.ts
packages/endpoint/src/interface.ts
packages/graphql/src/GQLEndpoint.ts
packages/react/src/hooks/useCache.ts
packages/rest/src/RestEndpointTypes.ts
website/src/components/Playground/editor-types/@data-client/endpoint.d.ts
website/src/components/Playground/editor-types/@data-client/graphql.d.ts
website/src/components/Playground/editor-types/@data-client/react.d.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/globals.d.ts

More intuitive; supports sideEffect overrides when using `loosenulltypes`
Support was already added to consumers (@data-client/react), so these will be supported by existing versions (0.11)

enhance: Endpoint.sideEffect can be

---

.circleci/config.yml

ts 4.0 tests flake every 1 in 10. https://app.circleci.com/pipelines/github/reactive/data-client/13890/workflows/b1197b76-94cd-430d-acad-b9507c50b9a3/jobs/119748
<details collapsed>
<summary><b>Flake error</b></summary>
```bash
node_modules/@types/react/ts5.0/index.d.ts:3287:50 - error TS1110: Type expected.
3287     type OptionalPrefixToken<T extends string> = `${T} ` | "";
~~~
node_modules/@types/react/ts5.0/index.d.ts:3288:51 - error TS1110: Type expected.
3288     type OptionalPostfixToken<T extends string> = ` ${T}` | "";
~~~~
node_modules/@types/react/ts5.0/index.d.ts:3289:48 - error TS1110: Type expected.
3289     type AutoFillField = AutoFillNormalField | `${OptionalPrefixToken<AutoFillContactKind>}${AutoFillContactField}`;
~~~
node_modules/@types/react/ts5.0/index.d.ts:3289:91 - …
```

internal(fix): Fix flaky tests by testing old ts versions with older @types/react

---

.changeset/short-experts-wave.md
.circleci/config.yml
docs/rest/api/Collection.md
docs/rest/api/Query.md
packages/core/src/controller/__tests__/get.ts
packages/endpoint/src/schema.d.ts
packages/endpoint/src/schemas/Query.ts
packages/endpoint/src/schemas/__tests__/Query.test.ts
packages/rest/src/__tests__/createResource.test.ts
website/src/components/Playground/editor-types/@data-client/endpoint.d.ts
website/src/components/Playground/editor-types/@data-client/graphql.d.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/globals.d.ts

Allow queries to be used in endpoints.
Queries pass-through suspense rather than ever being undefined
- [useSuspense()](https://dataclient.io/docs/api/useSuspense) return values will not be nullable
- [useQuery()](https://dataclient.io/docs/api/useQuery) will still be nullable due to it handling `INVALID` as `undefined` return
- [Query.process](https://dataclient.io/rest/api/Query#process) does not need to handle nullable cases

enhance: Queries passthrough suspense rather than being undefined

---

.changeset/fluffy-beans-act.md
examples/coin-app/src/pages/AssetDetail/LineChart.tsx
packages/rest/src/__tests__/__snapshots__/createResource.test.ts.snap
packages/rest/src/__tests__/createResource.test.ts
packages/rest/src/createResource.ts

Report of bug on discord server. Code was the following, which had `endpoint` parameters uncapitalized.
```ts
export const UserResource = createResource({
urlPrefix: CONFIG.API_ROOT,
path: '/users/:id',
schema: User,
endpoint: AuthedEndpoint,
});
```
Add warning
Should we just take lower cased versions as well? Do people actually need the lower cased for their class?

enhance: Warn for capitalization mistakes when calling createResource()

---

.changeset/itchy-kiwis-design.md
.circleci/config.yml
packages/core/src/state/RIC.ts
packages/react/src/__tests__/integration.node.tsx

Node doesn't have RIC - which is when SSR happens. We actually want to keep SSR synchronous.
When RequestIdleCallback is not found - call immediately.
Browsers that don't support this would be so old we don't care at this point, and it's just a perf optimization anyway.

enhance: Environments without RequestIdleCallback will call immediately

---

.changeset/silly-ducks-count.md
.changeset/tall-monkeys-exist.md
packages/hooks/src/__tests__/useCancelling.ts
packages/hooks/src/__tests__/useDebounce.ts
packages/hooks/src/__tests__/useLoading.tsx
packages/react/src/__tests__/hooks-endpoint.web.tsx
packages/react/src/__tests__/integration-index-endpoint.web.tsx
packages/react/src/__tests__/integration-nesting.web.tsx
packages/react/src/__tests__/integration.node.tsx
packages/react/src/__tests__/subscriptions-endpoint.tsx
packages/react/src/hooks/__tests__/subscriptions.tsx
packages/react/src/hooks/__tests__/useController/expireAll.tsx
packages/react/src/hooks/__tests__/useController/invalidate.tsx
packages/react/src/hooks/__tests__/useController/invalidateAll.tsx
packages/react/src/hooks/__tests__/useController/receive.tsx
packages/react/src/hooks/__tests__/useController/reset.tsx
packages/react/src/hooks/__tests__/useController/subscribe.tsx
packages/react/src/hooks/__tests__/useDLE.native.tsx
packages/react/src/hooks/__tests__/useFetch.native.tsx
packages/react/src/hooks/__tests__/useFetch.web.tsx
packages/react/src/hooks/useCacheSelector.ts
packages/rest/src/__tests__/createResource.test.ts
packages/test/package.json
packages/test/src/index.ts
packages/test/src/makeRenderDataClient/render18HookWrapped.tsx
packages/use-enhanced-reducer/src/__tests__/middleware.tsx
yarn.lock

Proper testing of react 18 behavior while keeping 17, react native and SSR tests all accurate and possible.
Move remaining tests that directly reference '@testing-library/react-hooks' to refer to our testing library.
- Add `renderHook` export to @data-client/test
- Rely on [ErrorBoundary](https://dataclient.io/docs/api/ErrorBoundary) from '@data-client/react' rather than error-boundary package.

internal: Remove '@testing-library/react-hooks' direct usage

---

.changeset/fuzzy-cherries-provide.md
docs/rest/api/Array.md
docs/rest/api/Values.md
packages/endpoint/src/schemas/Polymorphic.ts
packages/endpoint/src/schemas/__tests__/Union.test.js
packages/react/src/__tests__/integration-endpoint.web.tsx
packages/react/src/hooks/__tests__/useController/__snapshots__/fetch.tsx.snap
packages/react/src/hooks/__tests__/useController/fetch.tsx

ctrl.fetch() resolution should always be denormalized if possible. Previously, we would skip class instantiation (and other denorm things) with Polymorphic types, as they use a special normalized format to select the schema for denormalization.
Polymorphic (Union) types should still denormalize when handling passthrough (non-normalized) data
When denormalizing non-normalized (like return of ctrl.fetch), it is still expected to handle
all steps like constructing class instances if possible. However, to do this for Polymorphic
types we need to fallback to using part of the normalize process to find out *which* schema
to use for the remainder of denormalization.
This also removes extra console.warn that would appear when using [useSuspense()](https://dataclient.io/docs/api/useSuspense) or …

enhance: Union types construct class instances in ctrl.fetch() resolution value

---

website/blog/2024-04-08-v0.11-queries-querable-usequery.md
website/src/components/DiffEditor.tsx
website/src/components/DiffEditorChooser.tsx
website/src/components/DiffEditorMonaco.tsx
website/src/components/Grid.module.css
website/src/components/Grid.tsx
website/src/components/Playground/PlaygroundMonacoEditor.tsx
website/src/components/Playground/PlaygroundTextEdit.tsx
website/src/components/Playground/extensionToMonacoLanguage.tsx
website/src/components/Playground/monaco-init.ts
website/src/components/Playground/useAutoHeight.tsx
website/src/components/Playground/useCode.tsx

Easier to understand changes
Monaco has built in editor, so configure in similar way. Diffs should have 'before' and 'after'. Highlights will be removed.
```mdx
<DiffEditor>
``ts title="Before"
class MyEntity extends Entity {
id = 0;
pk() {
// highlight-next-line
return `${this.id}`;
}
}
``
``ts title="After"
class MyEntity extends Entity {
id = 0;
pk() {
// highlight-next-line
return this.id;
}
}
``
</DiffEditor>
```

docs: Add DiffEditor

---

.changeset/many-rings-matter.md
.changeset/metal-birds-punch.md
examples/nextjs/tsconfig.json
packages/react/src/components/CacheProvider.tsx
packages/react/src/components/ErrorBoundary.tsx
packages/react/src/context.ts
packages/react/src/hooks/useCacheState.ts
packages/react/src/hooks/useController.ts
packages/react/src/hooks/useDLE.native.ts
packages/react/src/hooks/useDLE.ts
packages/react/src/hooks/useError.ts
packages/react/src/hooks/useLive.ts
packages/react/src/hooks/useSubscription.tsx
packages/react/src/hooks/useUniversal.ts
packages/redux/src/ExternalCacheProvider.tsx
packages/ssr/rollup.config.js
packages/ssr/src/nextjs/DataProvider/DataProvider.tsx
packages/ssr/src/nextjs/DataProvider/ServerDataComponent.tsx
packages/ssr/src/nextjs/DataProvider/ServerProvider.tsx
packages/ssr/src/nextjs/DataProvider/context.ts
packages/ssr/src/nextjs/DataProvider/createPersistedStore.tsx
packages/ssr/src/nextjs/index.ts
packages/use-enhanced-reducer/rollup.config.js
packages/use-enhanced-reducer/src/useEnhancedReducer.ts
packages/use-enhanced-reducer/src/usePromisifiedDispatch.ts

Support NextJS App Router. This is a much better developer experience, and also allows for SSR based on dynamic routing, which means NextJS is finally usable for SSR use cases and not just SSG.
Add DataProvider export to /nextjs namespace.
This provides 'App Router' compatibility. Simply add it to the root layout, ensuring
`children` is rendered as a descendent.
<details open>
<summary><b>app/layout.tsx</b></summary>
```tsx
import { DataProvider } from '@data-client/react/nextjs';
import { AsyncBoundary } from '@data-client/react';
export default function RootLayout({ children }) {
return (
<html>
<body>
<DataProvider>
<header>Title</header>
<AsyncBoundary>{children}</AsyncBoundary>
<footer></footer>
</DataProvider>
</body>
</html>
);
}
```
</details>
Any endpoints can be used in server …

feat: Add NextJS app router support

---

.changeset/brave-bottles-talk.md
docs/core/guides/ssr.md
docs/core/shared/_installation.mdx
packages/react/.gitignore
packages/react/package.json
packages/react/rollup.config.js
packages/react/src/server/ServerData.tsx
packages/react/src/server/getInitialData.ts
packages/react/src/server/nextjs/DataProvider/DataProvider.tsx
packages/react/src/server/nextjs/DataProvider/ServerDataComponent.tsx
packages/react/src/server/nextjs/DataProvider/createPersistedStore.ts
packages/react/src/server/nextjs/DataProvider/createPersistedStoreClient.tsx
packages/react/src/server/nextjs/DataProvider/createPersistedStoreServer.tsx
packages/react/src/server/nextjs/index.ts
packages/react/src/server/redux/ExternalCacheProvider.tsx
packages/react/src/server/redux/PromiseifyMiddleware.ts
packages/react/src/server/redux/index.ts
packages/react/src/server/redux/mapMiddleware.ts
packages/react/src/server/redux/redux.d.ts
packages/react/src/server/redux/redux.js
scripts/copywebsitetypes.sh
website/src/components/Playground/editor-types/@data-client/react.d.ts
website/src/components/Playground/editor-types/@data-client/react/nextjs.d.ts

Simpler installs - no longer need multiple extra packages
```tsx
import { DataProvider } from '@data-client/react/nextjs';
export default function RootLayout({ children }) {
return (
<html>
<body>
<DataProvider>
{children}
</DataProvider>
</body>
</html>
);
}
```
- We now bundle in the redux specific things to remove external dependencies.

feat: Add @data-client/react/nextjs entrypoint

---

examples/coin-app/src/index.tsx
examples/coin-app/src/resources/StreamManager.ts
examples/nextjs/app/Provider.tsx
examples/nextjs/resources/StreamManager.ts

Disconnects can happen when device is forced offline, or sometimes even when app is in background for a long time.

demo: Improve stream manager against disconnects

---

.changeset/lemon-walls-shop.md
packages/react/rollup.config.js
packages/react/src/server/SSRDataProvider.tsx
packages/react/src/server/createPersistedStore.tsx
packages/react/src/server/nextjs/DataProvider/createPersistedStoreServer.tsx
website/src/components/Playground/editor-types/@data-client/react/ssr.d.ts

Remove extraneous codepaths that only run on client since this component only runs on server side

enhance: Use custom SSRProvider for SSR rather than ExternalDataProvider

---

.changeset/modern-pears-burn.md
.changeset/poor-cherries-promise.md
README.md
docs/core/README.md
docs/core/api/useCache.md
docs/core/api/useCancelling.md
docs/core/api/useDebounce.md
docs/core/api/useLoading.md
docs/core/concepts/expiry-policy.md
docs/core/getting-started/installation.md
docs/core/guides/abort.md
docs/core/shared/_useCancelling.mdx
docs/core/shared/_useLoading.mdx
docs/rest/api/Collection.md
docs/rest/api/Query.md
docs/rest/guides/abort.md
docs/rest/guides/optimistic-updates.md
docs/rest/shared/_optimisticTransform.mdx
packages/hooks/README.md
packages/react/README.md
packages/react/src/hooks/__tests__/useCancelling.ts
packages/react/src/hooks/__tests__/useDebounce.ts
packages/react/src/hooks/__tests__/useLoading.tsx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useCancelling.ts
packages/react/src/hooks/useDebounce.ts
packages/react/src/hooks/useLoading.ts
website/sidebars.json
website/src/components/Playground/editor-types/@data-client/react.d.ts

Less installs and brain power to think of what package the hooks are in.
**Mark @data-client/hooks as deprecated.** All hooks moved to [@data-client/react](https://www.npmjs.com/package/@data-client/react)

feat: Move /hooks package into /react pkg

---

.changeset/weak-timers-joke.md
babel.config.js
package.json
packages/react/.gitignore
packages/react/package.json

Fixes #3079 .
React Native [platform specific extensions](https://docs.expo.dev/router/advanced/platform-specific-modules/#platform-specific-extensions) was previously not working, resulting in the browser version of modules being used.
Explicit extension names (".js") in imports are required for modern node ESM support. However, this breaks the metro bundler as it gets confused and doesn't look for .native.js. To workaround we introduce custom react native builds.
The builds are referenced in ['community condition' for package exports "react-native"](https://reactnative.dev/blog/2023/06/21/package-exports-support). We also have the "react-native" field for legacy versions. (equivalent to "main").
It is critical to add "browser" condition anywhere "react-native" condition is used, so …

fix: React Native specific module bundler issues

---

.changeset/twelve-rockets-divide.md
.changeset/twelve-socks-hope.md
.changeset/young-needles-hide.md
packages/core/src/internal.ts
packages/core/src/manager/NetworkManager.ts
packages/core/src/state/RIC.ts
packages/react/src/components/DataProvider.tsx
packages/react/src/index.ts
packages/react/src/managers/NetworkManager.native.ts
packages/react/src/managers/NetworkManager.ts
packages/react/src/managers/__tests__/RIC.native.ts
packages/react/src/managers/__tests__/RIC.web.ts
packages/react/src/managers/index.ts
packages/react/src/server/createPersistedStore.tsx
packages/react/src/server/nextjs/DataProvider/createPersistedStoreServer.tsx
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/react.d.ts

Performance feature parity with web
Add NetworkManager.idleCallback overridable method
This allows platform specific implementations by overriding the method.
For instance, on web:
```ts
import { NetworkManager } from '@data-client/core';
export default class WebNetworkManager extends NetworkManager {
static {
if (typeof requestIdleCallback === 'function') {
WebNetworkManager.prototype.idleCallback = requestIdleCallback;
}
}
}
```
In React Native we use [InteractionManager](https://reactnative.dev/docs/interactionmanager) to implement similar functionality to requestIdleCallback:
```ts
import { NetworkManager } from '@data-client/core';
import { InteractionManager } from 'react-native';
export default class NativeNetworkManager extends NetworkManager {
/** Calls the callback when client …
```

enhance(native): Reduce chance of frame drops with InteractionManager

---

.changeset/smart-oranges-vanish.md
docs/core/api/Controller.md
packages/core/src/actions.ts
packages/core/src/controller/Controller.ts
packages/core/src/controller/createSet.ts
packages/core/src/state/__tests__/reducer.ts
packages/core/src/state/reducer/createReducer.ts
packages/core/src/state/reducer/setReducer.ts
website/src/components/Playground/editor-types/@data-client/core.d.ts

In case the value depends on previous value this eliminates race conditions.
Allow ctrl.set() value to be a function
This [prevents race conditions](https://react.dev/reference/react/useState#updating-state-based-on-the-previous-state).
```ts
const id = '2';
ctrl.set(Article, { id }, article => ({ id, votes: article.votes + 1 }));
```

feat: Allow ctrl.set() value to be a function

---

.changeset/wet-mirrors-visit.md
packages/endpoint/src/schemas/EntitySchema.ts
packages/normalizr/src/__tests__/__snapshots__/index.test.js.snap
packages/normalizr/src/__tests__/index.test.js
packages/normalizr/src/normalize.ts

Group like code for easier to read and possibly refactoring.
Validate after marking cirucular reference loops
This should not change any behavior as validate should be deterministic so if it fails
it will fail again and failure measure throwing which exits the whole stack.
This improves code grouping. (And possibly cache locality improvement - though didn't check.)

enhance: Entity runs validate after marking circular reference point

---

website/docusaurus.config.ts
website/src/components/DiffEditorMonaco.tsx
website/src/components/Playground/PlaygroundMonacoEditor.tsx
website/src/components/Playground/PlaygroundTextEdit.tsx
website/src/components/Playground/monacoOptions.tsx

`WARNING : Html size is too long` in bing & google.
This also means pages with editors are huge and take a long time to show initial html for users with slower connections.
Don't SSR hidden tabs. The shown tabs are the important context for that docs page - usually hidden tabs just provide further context for the example, and don't provide any unique insights for that page.
TODO:
- Perhaps later have links to show just the playground where all tabs and rendered - this way the example code is crawlable for AI codegen engines.
- Try to SSR without all the syntax highlighting as the large amount of extra tags is also problematic for crawlers. This will likely require docusaurus changes.

docs: Don't SSR hidden editor tabs

---

.changeset/rich-stingrays-look.md
packages/normalizr/README.md
packages/react/src/managers/NetworkManager.native.ts
packages/react/src/managers/NetworkManager.ts
packages/react/src/managers/index.ts
website/src/components/Playground/editor-types/@data-client/react.d.ts

[NetworkManager](https://dataclient.io/docs/api/NetworkManager) will fetch
immediately, rather than waiting for idle. With React 18+ it is expected for
React to better handle work with concurrent mode and batching. Due to this, it
is not longer deemed the best performance to wait for idle and instead we should
fetch immediately.
Call fetches immediately - do not wait for idle
`IdlingNetworkManager` is still available to keep the previous behavior.

enhance: Call fetches immediately - do not wait for idle

---

.changeset/empty-pillows-wait.md
.changeset/fluffy-months-sleep.md
.changeset/little-plants-hammer.md
.changeset/strong-garlics-wonder.md
packages/endpoint/src/interface.ts
packages/endpoint/src/schema.d.ts
packages/endpoint/src/schemas/Collection.ts
packages/endpoint/src/schemas/Polymorphic.ts
packages/endpoint/src/schemas/__tests__/Collection.test.ts
packages/endpoint/src/schemas/__tests__/__snapshots__/Collection.test.ts.snap
packages/normalizr/src/memo/MemoCache.ts
packages/normalizr/src/normalizr/normalize.ts
packages/normalizr/src/types.ts
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/endpoint.d.ts
website/src/components/Playground/editor-types/@data-client/graphql.d.ts
website/src/components/Playground/editor-types/@data-client/normalizr.d.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/globals.d.ts

- Production builds often mangle class names: Collection.key used to rely on schema.constructor.name, which could result in client/server serialization mismatches at the worst, and at the best made production build stores unreadable
- Collections would not work with polymorphic members - including [Unions](https://dataclient.io/rest/api/Union) or when Array/Values had a [polymorphic constructor](https://dataclient.io/rest/api/Array#polymorphic-types
Rework Collect.key:
Now relies on its schema to have schemaKey() (which is defined in Polymorphic, so it is inherited by Array, Values, and Union).
```ts
new Collection([Todo]).key
```
'COLLECT:ArraySchema(Todo)' -> '[Todo]'
```ts
new Collection(
new Array(
{
users: User,
groups: Group,
},
'type',
),
).key
```
*FAILED* -> '[User;Group]'

fix: Collections work with polymorphic schemas and class name mangling

---

.changeset/pink-dodos-protect.md
.changeset/witty-papayas-battle.md
docs/core/api/DataProvider.md
docs/core/api/DevToolsManager.md
docs/core/api/Manager.md
docs/core/api/NetworkManager.md
docs/core/api/getDefaultManagers.md
docs/core/concepts/managers.md
docs/core/getting-started/debugging.md
examples/coin-app/src/getManagers.ts
examples/coin-app/src/index.tsx
packages/core/src/manager/SubscriptionManager.ts
packages/react/src/components/DataProvider.tsx
packages/react/src/components/__tests__/__snapshots__/getDefaultManagers.tsx.snap
packages/react/src/components/__tests__/getDefaultManagers.tsx
packages/react/src/components/__tests__/provider.native.tsx
packages/react/src/components/__tests__/provider.tsx
packages/react/src/components/getDefaultManagers.tsx
packages/react/src/components/index.ts
packages/react/src/managers/IdlingNetworkManager.native.ts
packages/react/src/managers/IdlingNetworkManager.ts
packages/react/src/managers/__tests__/RIC.native.ts
packages/react/src/managers/__tests__/RIC.web.ts
packages/react/src/managers/index.ts
website/sidebars.json
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/react.d.ts

Currently, customizing managers found in the default managers required awkward filtering them out, and then replacing them in the correct position.
```tsx
const getManagers =
process.env.NODE_ENV === 'development' ?
() => [
...getDefaultManagers().filter(
mgr => mgr.constructor.name !== 'DevToolsManager',
),
]
: getDefaultManagers;
```
```tsx
function getManagers() {
const managers = getDefaultManagers().filter(
manager => manager.constructor.name !== 'DevToolsManager',
);
if (process.env.NODE_ENV !== 'production') {
const networkManager: NetworkManager | undefined = managers.find(
manager => manager instanceof NetworkManager,
) as any;
managers.unshift(
new DevToolsManager(
{
// double latency to help with high frequency updates
latency: 1000,
// skip websocket updates as these are too …
```

feat: Add configuration to getDefaultManagers()

---

.changeset/five-apes-pretend.md
.changeset/new-garlics-sort.md
README.md
docs/core/README.md
docs/core/api/Controller.md
docs/core/api/Manager.md
docs/core/api/types.md
docs/core/concepts/managers.md
docs/core/guides/redux.md
examples/coin-app/src/resources/StreamManager.ts
packages/core/src/manager/DevtoolsManager.ts
packages/core/src/manager/LogoutManager.ts
packages/core/src/manager/NetworkManager.ts
packages/core/src/manager/SubscriptionManager.ts
packages/core/src/manager/__tests__/applyManager.ts
packages/core/src/manager/__tests__/logoutManager.ts
packages/core/src/manager/__tests__/manager.ts
packages/core/src/manager/__tests__/networkManager.ts
packages/core/src/manager/__tests__/subscriptionManager.ts
packages/core/src/manager/applyManager.ts
packages/core/src/middlewareTypes.ts
packages/core/src/types.ts
packages/react/README.md
packages/react/src/components/DataProvider.tsx
packages/react/src/components/DataStore.tsx
packages/react/src/components/__tests__/provider.tsx
website/src/components/Playground/editor-types/@data-client/core.d.ts

Simplification
We previously used `getMiddleware()` so we wouldn't have to worry about object binding (we could assign middleware variable instead of calling manager.middleware()). However, applyManagers gives us full control of how it is is called, so this is no longer necessary.
```ts
class LoggingManager implements Manager {
getMiddleware = (): Middleware => controller => next => async action => {
console.log('before', action, controller.getState());
await next(action);
console.log('after', action, controller.getState());
};
cleanup() {}
}
```
```ts
class LoggingManager implements Manager {
middleware: Middleware => controller => next => async action => {
console.log('before', action, controller.getState());
await next(action);
console.log('after', action, controller.getState());
}; …
```

enhance: Manager.getMiddleware() -> Manager.middleware

---

.changeset/green-dogs-lay.md
docs/core/api/useQuery.md
docs/rest/api/Query.md
examples/coin-app/src/pages/Home/AssetPrice.tsx
examples/coin-app/src/resources/Stats.ts
examples/coin-app/src/resources/Ticker.ts
examples/coin-app/src/resources/fallbackQueries.ts
packages/endpoint/src-4.0-types/schemaArgs.d.ts
packages/endpoint/src/index.ts
packages/endpoint/src/interface.ts
packages/endpoint/src/normal.ts
packages/endpoint/src/schema.d.ts
packages/endpoint/src/schemaArgs.ts
packages/endpoint/src/schemas/Query.ts
packages/endpoint/typescript-tests/query.ts
packages/normalizr/src-4.0-types/schemaArgs.d.ts
packages/normalizr/src/interface.ts
packages/normalizr/src/schemaArgs.ts
packages/normalizr/src/types.ts
packages/react/src/index.ts
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/endpoint.d.ts
website/src/components/Playground/editor-types/@data-client/graphql.d.ts
website/src/components/Playground/editor-types/@data-client/normalizr.d.ts
website/src/components/Playground/editor-types/@data-client/react.d.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/globals.d.ts

Client-side joins should all be doable in [Queries](https://dataclient.io/rest/api/Query).
This enables joins across arbitrary elements (not just nested entities).
For instance, with our [crypto live price demo](https://dataclient.io/demos), we need to fallback to `Stats` when loading a page until the websocket `Ticker` has updated. This ensures [SSR](https://dataclient.io/docs/guides/ssr) and initial page loads work. 
```ts
class Ticker extends Entity {
product_id = '';
price = 0;
pk(): string {
return this.product_id;
}
}
class Stats extends Entity {
product_id = '';
last = 0;
pk(): string {
return this.product_id;
}
}
const queryPrice = new schema.Query(
{ ticker: Ticker, stats: Stats },
({ ticker, stats }) => ticker?.price ?? stats?.last,
);
```
This allows simple lookups for the …

feat: Queries can take object schemas

---

.changeset/dull-deers-cry.md
docs/core/api/useDebounce.md
packages/react/src/components/__tests__/AsyncBoundary.web.tsx
packages/react/src/components/__tests__/ErrorBoundary.native.tsx
packages/react/src/components/__tests__/ErrorBoundary.tsx
packages/react/src/next/__tests__/useDebounce.web.tsx
packages/react/src/next/index.ts
packages/react/src/next/useDebounce.ts
website/src/components/Playground/PreviewWithScope.tsx
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/react.d.ts
website/src/components/Playground/editor-types/@data-client/react/next.d.ts

Provider a better search experience out of the box. Don't flash loading in results - continue showing the previous results while new content loads.
https://github.com/user-attachments/assets/d52cd0ef-df32-40b1-a478-afd3c4e96fb7
https://github.com/user-attachments/assets/b0c4c2b2-3fd7-4978-9ec1-4d04c19e53b3
```ts
import { useDebounce } from '@data-client/react/next';
const [debouncedQuery, isPending] = useDebounce(query, 100);
```

docs: Add new useDebounce() in /next that returns [val, isPending]

---

.changeset/four-terms-leave.md
.changeset/wise-seals-cross.md
README.md
__tests__/new.ts
docs/core/getting-started/resource.md
docs/core/shared/_VoteDemo.mdx
docs/rest/README.md
docs/rest/api/Entity.md
docs/rest/api/EntityMixin.md
examples/benchmark/schemas.js
examples/benchmark/src/index.ts
packages/endpoint/README.md
packages/endpoint/src-4.0-types/schemas/EntityTypes.d.ts
packages/endpoint/src/index.ts
packages/endpoint/src/schema.d.ts
packages/endpoint/src/schema.js
packages/endpoint/src/schemaTypes.ts
packages/endpoint/src/schemas/EntityMixin.ts
packages/endpoint/src/schemas/EntityTypes.ts
packages/endpoint/src/schemas/__tests__/EntitySchema.test.ts
packages/graphql/README.md
packages/normalizr/README.md
packages/normalizr/docs/api.md
packages/rest/README.md
website/docusaurus.config.ts
website/sidebars-endpoint.json
website/src/components/Playground/editor-types/@data-client/endpoint.d.ts
website/src/components/Playground/editor-types/@data-client/graphql.d.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/globals.d.ts

Clearer naming
`schema.Entity` -> [EntityMixin](https://dataclient.io/rest/api/EntityMixin)
```ts
import { EntityMixin } from '@data-client/rest';
export class Article {
id = '';
title = '';
content = '';
tags: string[] = [];
}
export class ArticleEntity extends EntityMixin(Article) {}
```
We keep `schema.Entity` for legacy, and add schema.EntityMixin and [EntityMixin](https://dataclient.io/rest/api/EntityMixin) as direct export

enhance: schema.Entity -> EntityMixin

---

.changeset/dirty-lamps-raise.md
packages/endpoint/src/schemas/Collection.ts
packages/endpoint/src/schemas/__tests__/Collection.test.ts
packages/react/package.json
packages/react/src/__tests__/__snapshots__/integration-collections.tsx.snap
packages/react/src/__tests__/integration-collections.tsx
yarn.lock

Fixes #3280 .
Handle nested object args when using Collections.
Stop strinigfying all values in Collection.pk() - only do this for number and booleans.
Originally this was added in https://github.com/reactive/data-client/commit/ca249b5dda2ae40f5aca0777d560b4218608705d#diff-92c9afa78291c2d6c55ee59b03d774c70f8ff00d4a93120c494d6f5498b50b59R107 to normalize serialization even when strings are substituted for numbers, etc. However, this doesn't make sense for other types like objects.

fix: Collections work with nested args

---

.circleci/config.yml
.yarnrc.yml

Faster CI
- centralize config in executor with custom yarn environment configs
- yarn cache checksum includes todo-app now
- `corepack enable` command no longer needed
- sort `persist_to_workspace` list to make it more easily comparable to file list in editor
- ignore spammy YN0060 yarn error (even in development/local)

internal: Improve yarn performance in CI

---

.circleci/config.yml

Faster CI
[yarn up](https://yarnpkg.com/cli/up) Allows global package version changes.
This cuts our slowest step - react 17 unit tests - in half by taking the 50s react version install and reducing it to 7s.

internal: Use `yarn up` to greatly improve CI perf

---

.circleci/config.yml
examples/coin-app/package.json
package.json
tsconfig.test.json
website/package.json
yarn.lock

- Ensure full type-test coverage
- Don't slow down CI by repeating typechecks over same files
- No longer do typecheck in CI jest; extract to typecheck CI stage

internal: Run full typescript tests again

---

.changeset/three-needles-brake.md
babel.config.js
packages/core/package.json
packages/endpoint/package.json
packages/graphql/package.json
packages/normalizr/package.json
packages/react/package.json
packages/react/src/__tests__/integration-garbage-collection.web.tsx
packages/rest/package.json
packages/test/.gitignore
packages/test/package.json

Consolidate react native build and package.json across packages.
exports support was added in 0.72, with hermes 0.12. Therefore we target hermes 0.12 for exports + react-native condition.
For "react-native" top-level entry in package.json we use legacy as to support older versions of react native.
For packages without a specific RN build, we simply use the 'lib' dir as that targets 2020, which is approximately the same as hermes 0.12. (though potentially with more legacy support). We do this simply to reduce package download size and build time.

enhance: Add react-native entry to package.json exports

---

.changeset/shaky-ties-hide.md
.changeset/silver-paws-send.md
packages/core/src/controller/Controller.ts
packages/core/src/controller/__tests__/__snapshots__/get.ts.snap
packages/core/src/controller/__tests__/__snapshots__/getResponse.ts.snap
packages/core/src/controller/__tests__/get.ts
packages/core/src/controller/__tests__/getResponse.ts
packages/core/src/state/GCPolicy.ts
packages/normalizr/src/endpoint/SnapshotInterface.ts
packages/react/src/__tests__/integration-garbage-collection.native.tsx
packages/react/src/__tests__/integration-garbage-collection.web.tsx
packages/react/src/hooks/useQuery.ts

useQuery() must also count its references else it might break when others un-mount.
Followup to: #3343
Introduce Controller.getQueryMeta() so we have a countRef for useQuery.
Similarly, add Controller.getResponseMeta(). This should eventually become what is used instead of getResponse() - so getResponse() can just return data. (useful for getResponse snapshot stuff)

enhance: Add GC counting to useQuery()

---

.changeset/silly-hotels-shout.md
.changeset/strange-buckets-clean.md
packages/core/src/controller/__tests__/Controller.ts
packages/core/src/state/GCPolicy.ts
packages/core/src/state/__tests__/GCPolicy.test.ts
packages/core/src/state/__tests__/__snapshots__/reducer.ts.snap
packages/core/src/state/reducer/setResponseReducer.ts
packages/core/src/types.ts
packages/react/src/__tests__/integration-garbage-collection.native.tsx
packages/react/src/__tests__/integration-garbage-collection.web.tsx
packages/react/src/components/__tests__/__snapshots__/provider.native.tsx.snap
packages/react/src/components/__tests__/__snapshots__/provider.tsx.snap
packages/react/src/hooks/__tests__/useDLE.native.tsx
packages/react/src/hooks/__tests__/useFetch.native.tsx
packages/react/src/hooks/__tests__/useSuspense.native.tsx
packages/react/src/hooks/__tests__/useSuspense.web.tsx

Followup: #3343
There is a tradeoff of memory vs cpu/time. Keeping data around longer, means a potentially higher cache hit rate. However, at the sacrifice of memory usage.
These policy configurations allow customization of these tradeoffs to suite the needs of a given application.
Used in the default `hasExpired` policy.
Represents how many 'stale' lifetimes data should persist before being
garbage collected.
```typescript
expiresAt({
fetchedAt,
expiresAt,
}: {
expiresAt: number;
date: number;
fetchedAt: number;
}): number {
return (
Math.max(
(expiresAt - fetchedAt) * this.options.expiryMultiplier,
120000,
) + fetchedAt
);
}
```
Indicates at what timestamp it is acceptable to remove unused data from the store.
Data not currently rendered in any components is considered unused. However, …

feat: Add hasExpired and expiryMultiplier options to GCPolicy

---

.changeset/smooth-seals-shake.md
babel.config.js
packages/core/package.json
packages/core/rollup.config.mjs
packages/endpoint/package.json
packages/endpoint/rollup.config.mjs
packages/endpoint/src/index.ts
packages/graphql/package.json
packages/graphql/rollup.config.mjs
packages/img/package.json
packages/img/rollup.config.mjs
packages/normalizr/package.json
packages/normalizr/rollup.config.mjs
packages/react/package.json
packages/react/rollup.config.mjs
packages/react/src/index.ts
packages/react/src/server/index.ts
packages/rest/package.json
packages/rest/rollup.config.mjs
packages/test/package.json
packages/test/rollup.config.mjs
packages/test/src/MockController.ts
packages/use-enhanced-reducer/package.json
packages/use-enhanced-reducer/rollup.config.mjs
yarn.lock

In https://github.com/reactive/data-client/commit/165afed083c0c63e9356bc8d1ee30dee8b916ed6#diff-9a40c6a3ef28df92dce0c4b8ab76fd7a4912103d2e767254ed4d93100e532bb0 we tried focusing on bundling polyfills as a robust approach.
Unfortunately, the current way polyfill packages work even including just one polyfill for Object.hasOwn includes around 40 other polyfills that are not needed; increasing all bundle sizes by 30%.
Go back to the old approach of using @babel/runtime only

enhance: Reduce bundle size by removing bloated polyfills

---

.changeset/evil-beans-attack.md
.changeset/loud-rice-fry.md
docs/core/concepts/normalization.md
examples/benchmark/README.md
packages/core/src/manager/NetworkManager.ts
packages/normalizr/README.md
packages/normalizr/src/denormalize/cache.ts
packages/normalizr/src/denormalize/localCache.ts
packages/normalizr/src/denormalize/unvisit.ts
packages/normalizr/src/memo/MemoCache.ts
packages/normalizr/src/memo/globalCache.ts
packages/normalizr/src/memo/types.ts
packages/normalizr/src/normalizr/addEntities.ts
packages/normalizr/src/normalizr/getCheckLoop.ts
packages/normalizr/src/normalizr/normalize.ts
packages/react/src/__tests__/integration-collections.tsx
packages/react/src/__tests__/integration-endpoint.web.tsx
packages/react/src/hooks/__tests__/useQuery.tsx
packages/rest/src/RestHelpers.ts
packages/test/src/MockController.ts
packages/test/src/createFixtureMap.tsx

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#objects_vs._maps
Objects are intended to be used for...Objects. In other words, things with statically known keys. Map was developed to handle the hashmap function, even though in legacy javascript Objects were used for both.
Maps don't have the security problems, and not only are they faster base, they don't cause deopt thrashing which slows performance both for doing JITs as well as causing JIT misses, and not being able to JIT as many functions.
See MDN article for a full list of benefits.
We already require WeakMap, which was made after so this does not introduce any more support. (And Map is super old now!)
Up to 32% performance increase (getResponse for long)
Experiment with State itself as a Map. …

enhance: Improve performance by using Map

---

.changeset/brave-bats-itch.md
docs/core/concepts/normalization.md
examples/benchmark/old-normalizr/normalizr.js
packages/endpoint/src/schemas/__tests__/Entity.test.ts
packages/endpoint/src/schemas/__tests__/EntityMixin.test.ts
packages/endpoint/src/schemas/__tests__/__snapshots__/Entity.test.ts.snap
packages/endpoint/src/schemas/__tests__/__snapshots__/EntityMixin.test.ts.snap
packages/endpoint/src/schemas/__tests__/__snapshots__/Values.test.js.snap
packages/normalizr/src/denormalize/denormalize.ts
packages/normalizr/src/denormalize/unvisit.ts
packages/normalizr/src/memo/MemoCache.ts

BREAKING CHANGE: Denormalize always transforms immutablejs entities into the class
Previously using ImmutableJS structures when calling denormalize() would maintain
nested schemas as immutablejs structures still. Now everything is converted to normal JS.
This is how the types have always been specified.
Think through use of immutablejs. Maximize performance and compatibility.
Don't check objects are immutable everywhere.
ideal case:
- immutablejs used for lookup table. but normalize does not turn entitys or such into immutablejs themselves
- then when denormalizing on normal path, no conversion needs to be done
- collections should normalize to immutablelist as they like to be mutated and potentially are long
also support immutablejs at entity level
- have special immutablejsentity (maybe …

enhance: ImmutableJS always denormalizes to normal JS

---

.circleci/config.yml

React Native always needs a very specific version; so running the RN tests with the current version keeps breaking and not allowing us to test or develop against the latest releases.
Instead of constantly changing where RN gets tested with each release, we will maintain a distinct CI job for react native tests so it can be independently adjusted from all other react version tests.

internal: Test React Native with distinct react version

---

packages/core/src/controller/Controller.ts
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/bignumber.d.ts

Cleaner abstraction boundary; shared code path
```ts
private getExpiryStatus(
invalidDenormalize: boolean,
invalidIfStale: boolean,
meta: { error?: unknown; invalidated?: unknown } = {},
) {
// https://dataclient.io/docs/concepts/expiry-policy#expiry-status
// we don't track the difference between stale or fresh because that is tied to triggering
// conditions
return (
meta.invalidated || (invalidDenormalize && !meta.error) ?
ExpiryStatus.Invalid
: invalidDenormalize || invalidIfStale ? ExpiryStatus.InvalidIfStale
: ExpiryStatus.Valid
);
}
```

enhance: Consolidate controller expiry logic in private getExpiryStatus()

---

.changeset/poor-jobs-turn.md
examples/benchmark/normalizr.js
packages/core/src/controller/Controller.ts
packages/endpoint/src/schemas/__tests__/All.test.ts
packages/endpoint/src/schemas/__tests__/Collection.test.ts
packages/endpoint/src/schemas/__tests__/Query.test.ts
packages/normalizr/src/__tests__/MemoCache.ts
packages/normalizr/src/memo/Delegate.immutable.ts
packages/normalizr/src/memo/Delegate.ts
packages/normalizr/src/memo/MemoCache.ts
packages/normalizr/src/normalize/NormalizeDelegate.ts

BREAKING CHANGE: MemoCache.query() and MemoCache.buildQueryKey() take state as one argument
```ts
this.memo.buildQueryKey(
schema,
args,
state.entities,
state.indexes,
key,
);
```
```ts
this.memo.buildQueryKey(
schema,
args,
state,
key,
);
```
```ts
this.memo.query(schema, args, state.entities, state.indexes);
```
```ts
this.memo.query(schema, args, state);
```

enhance: MemoCache.query() and MemoCache.buildQueryKey() take state as one argument

---

.changeset/stale-socks-accept.md
docs/rest/api/schema.md
packages/core/src/controller/Controller.ts
packages/endpoint/src/schemas/__tests__/All.test.ts
packages/endpoint/src/schemas/__tests__/Query.test.ts
packages/normalizr/README.md
packages/normalizr/src/__tests__/MemoCache.ts
packages/normalizr/src/__tests__/__snapshots__/MemoCache.ts.snap
packages/normalizr/src/memo/MemoCache.ts
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/normalizr.d.ts

- MemoCache.query() return value changed to `{data, paths}` like memo.denormalize()
- `data` could be INVALID
Consistent function signatures; Simpler controller.getQueryMeta() implementation.
MemoCache.query returns `{ data, paths }` just like denormalize. `data` could be INVALID
```ts
return this.memo.query(schema, args, state);
```
```ts
const { data } = this.memo.query(schema, args, state);
return typeof data === 'symbol' ? undefined : (data as any);
```

enhance: MemoCache.query returns {data, paths} just like denormalize

---

.changeset/sour-horses-give.md
packages/core/src/index.ts
packages/core/src/manager/NetworkManager.ts
packages/test/src/makeRenderDataClient/index.tsx
website/src/components/Playground/editor-types/@data-client/core.d.ts

BREAKING CHANGE: NetworkManager.fetched, NetworkManager.rejectors, NetworkManager.resolvers, NetworkManager.fetchedAt
-> NetworkManager.fetching
Better performance, security, and readability
```ts
fetching: Map<string, FetchMeta>;
```
```ts
interface FetchingMeta {
promise: Promise<any>;
resolve: (value?: any) => void;
reject: (value?: any) => void;
fetchedAt: number;
}
```
```ts
if (action.key in this.fetched)
```
```ts
if (this.fetching.has(action.key))
```

enhance: Change NetworkManager bookkeeping data structure for inflight fetches

---

.changeset/major-boxes-glow.md
.changeset/open-shrimps-warn.md
.changeset/tough-areas-show.md
packages/core/src/state/__tests__/reducer.ts
packages/endpoint/src/index.ts
packages/endpoint/src/interface.ts
packages/endpoint/src/schemas/All.ts
packages/endpoint/src/schemas/EntityMixin.ts
packages/endpoint/src/schemas/Invalidate.ts
packages/endpoint/src/schemas/__tests__/All.test.ts
packages/endpoint/src/schemas/__tests__/Invalidate.test.ts
packages/endpoint/src/schemas/__tests__/Values.test.js
packages/endpoint/src/special.ts
packages/normalizr/src/interface.ts
packages/normalizr/src/memo/Delegate.ts
packages/normalizr/src/normalize/NormalizeDelegate.ts
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/endpoint.d.ts
website/src/components/Playground/editor-types/@data-client/graphql.d.ts
website/src/components/Playground/editor-types/@data-client/normalizr.d.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/globals.d.ts

There should only be one symbol. We're getting around this by simply checking typeof, but this is a hack because normalizr and endpoint should not 'know' of each other directly.
Just like we hand off special errors to throw with snapshot, we can do the same thing with our delegate.
```ts
normalize(
input: any,
parent: any,
key: string | undefined,
args: any[],
visit: (...args: any) => any,
delegate: INormalizeDelegate,
): string {
delegate.setEntity(this as any, pk, INVALID);
}
```
```ts
normalize(
input: any,
parent: any,
key: string | undefined,
args: any[],
visit: (...args: any) => any,
delegate: INormalizeDelegate,
): string {
delegate.invalidate(this as any, pk);
}
```
```ts
queryKey(args: any, unvisit: any, delegate: IQueryDelegate): any {
if (!found) return INVALID;
}
```
```ts …
```

enhance: Remove INVALID symbol from endpoints in favor of delegate access

---

packages/normalizr/src/denormalize/cache.ts
packages/normalizr/src/denormalize/denormalize.ts
packages/normalizr/src/denormalize/localCache.ts
packages/normalizr/src/denormalize/unvisit.ts
packages/normalizr/src/memo/MemoCache.ts
packages/normalizr/src/memo/globalCache.ts
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/normalizr.d.ts

enhance: Make 'symbol' return types more specific (INVALID)

---

packages/react/src/hooks/__tests__/useController/expireAll.tsx
packages/react/src/hooks/__tests__/useController/invalidate.tsx
packages/react/src/hooks/__tests__/useController/invalidateAll.tsx
packages/react/src/hooks/__tests__/useController/reset.tsx
packages/react/src/hooks/__tests__/useController/setResponse.tsx
packages/react/src/hooks/__tests__/useController/subscribe.tsx
tsconfig-base.json

Fixes https://github.com/react-navigation/react-navigation/issues/12536 https://github.com/react-navigation/react-navigation/issues/12535
Support modern-only packages that don't include legacy fallbacks

internal: Switch typescript to module resolution bundler

---

.changeset/shiny-olives-behave.md
packages/endpoint/src/index.ts

Fixes the following TypeScript error when using `EntityMixin`:
`The inferred type of ... cannot be named without a reference to '../../node_modules/@data-client/endpoint/lib/schemas/EntityTypes'. This is likely not portable. A type annotation is necessary.ts(2742)`

fix: export types needed for EntityMixin

---

.changeset/proud-taxes-bake.md
.changeset/thirty-islands-hope.md
packages/endpoint/src/interface.ts
packages/endpoint/src/schemas/All.ts
packages/endpoint/src/schemas/Collection.ts
packages/endpoint/src/schemas/__tests__/All.test.ts
packages/endpoint/src/schemas/__tests__/Object.test.js
packages/endpoint/src/schemas/__tests__/__snapshots__/All.test.ts.snap
packages/normalizr/src/delegate/BaseDelegate.ts
packages/normalizr/src/delegate/Delegate.imm.ts
packages/normalizr/src/delegate/Delegate.ts
packages/normalizr/src/interface.ts
packages/normalizr/src/memo/MemoCache.ts
website/src/components/Playground/editor-types/@data-client/core.d.ts
website/src/components/Playground/editor-types/@data-client/endpoint.d.ts
website/src/components/Playground/editor-types/@data-client/graphql.d.ts
website/src/components/Playground/editor-types/@data-client/normalizr.d.ts
website/src/components/Playground/editor-types/@data-client/rest.d.ts
website/src/components/Playground/editor-types/globals.d.ts

Follow-up to #3468
Exposing the full entities data structure is potentially unsafe, and has unbounced interface implications for its implementation.
Restrict exposed surface area to looping behavior.
Return value is a restricted interface with `keys()` and `entries()` iterator methods.
Update both `IQueryDelegate`, and `INormalizeDelegate` as we try to match their interfaces as much as possible.
```ts
const entities = delegate.getEntities(key);
// foreach on keys
for (const key of entities.keys()) {}
// Object.keys() (convert to array)
return [...entities.keys()];
// foreach on full entry
for (const [key, entity] of entities.entries()) {}
```
```ts
const entities = delegate.getEntity(this.key);
if (entities)
Object.keys(entities).forEach(collectionPk => {
if …
```

enhance: delegate.getEntities() returns restricted EntitiesInterface

---

.circleci/config.yml
packages/core/src/manager/__tests__/pollingSubscription.ts
packages/endpoint/src/schemas/__tests__/All.test.ts
packages/endpoint/src/schemas/__tests__/Array.test.js
packages/endpoint/src/schemas/__tests__/__snapshots__/All.test.ts.snap
packages/endpoint/src/schemas/__tests__/__snapshots__/Array.test.js.snap
packages/react/src/components/__tests__/AsyncBoundary.web.tsx
packages/react/src/components/__tests__/ErrorBoundary.native.tsx
packages/react/src/components/__tests__/ErrorBoundary.tsx
packages/react/src/hooks/__tests__/__snapshots__/useQuery.tsx.snap
packages/react/src/hooks/__tests__/useController/reset.tsx
packages/react/src/hooks/__tests__/useQuery.tsx
packages/use-enhanced-reducer/src/__tests__/__snapshots__/middleware.tsx.snap
packages/use-enhanced-reducer/src/__tests__/middleware.tsx

Significant memory usage for our tests by splitting typechecking out as well as other optimizations

internal: Uncap test workers in CI

---

.changeset/pink-waves-judge.md
docs/rest/api/Collection.md
packages/endpoint/src/schemaTypes.ts
packages/endpoint/src/schemas/Collection.ts
packages/endpoint/src/schemas/__tests__/Collection.test.ts
packages/endpoint/src/schemas/__tests__/__snapshots__/Collection.test.ts.snap

Invalidate() removes everywhere, but what if we want to just remove from one collection and keep in others?
https://backbonejs.org/#Collection-remove
- Response: Take input like Invalidate (either pk directly or an object to run pk on)
- Usage: Operate like push/unshift/assign (TodoResource.getList.remove({ id: ‘5’ }))
```ts
ctrl.set(MyResource.getList.schema.remove, { id });
```
or
```ts
ctrl.fetch(MyResource.getList.remove, { id });
```
- What about Values?
- What about RestEndpoint extenders? (like getList.push)

feat: Add Collection.remove
